// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CompareService 比对服务 (wails 绑定: 方法被前端直接调用)。
 * Startup 由 main 注入 (merge 模式启动信息); QuitFn 由 main 注入 (带退出码退出应用)。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Apply 把前端累积的同步编辑原位写回目标文件 (GUI"保存"调用)。
 * 只支持 xlsx 目标 (CSV 为只读比对); 空编辑列表直接返回。
 * @param {$models.ApplyRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function Apply(req) {
    return $Call.ByID(590522699, req);
}

/**
 * Compare 执行比对: 按左文件扩展名分流 → 表格模式 (xlsx.Load/LoadCSV + engine)
 * 或文本模式 (readLines + textdiff) → 转视图 DTO。
 * @param {$models.CompareRequest} req
 * @returns {$CancellablePromise<$models.CompareResult | null>}
 */
export function Compare(req) {
    return $Call.ByID(1677249764, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetStartup 返回启动模式信息 (前端 mount 时调用一次)。
 * @returns {$CancellablePromise<$models.StartupInfo | null>}
 */
export function GetStartup() {
    return $Call.ByID(1970733096).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Quit 以指定退出码退出应用 (merge 模式: 0=已解决, 1=放弃; 由 main 注入实现)。
 * @param {number} code
 * @returns {$CancellablePromise<void>}
 */
export function Quit(code) {
    return $Call.ByID(1331850278, code);
}

// Private type creation functions
const $$createType0 = $models.CompareResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.StartupInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
