// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CompareService 比对服务 (wails 绑定: 方法被前端直接调用)。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Compare 执行比对: 按左文件扩展名分流 → 表格模式 (xlsx.Load/LoadCSV + engine)
 * 或文本模式 (readLines + textdiff) → 转视图 DTO。
 * @param {$models.CompareRequest} req
 * @returns {$CancellablePromise<$models.CompareResult | null>}
 */
export function Compare(req) {
    return $Call.ByID(1677249764, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.CompareResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
