// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../engine/models.js";

/**
 * ApplyRequest 批量写回请求: Edits 全部落向同一个目标文件。
 */
export class ApplyRequest {
    /**
     * Creates a new ApplyRequest instance.
     * @param {Partial<ApplyRequest>} [$$source = {}] - The source object to create the ApplyRequest.
     */
    constructor($$source = {}) {
        if (!("targetPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetPath"] = "";
        }
        if (!("sheetName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sheetName"] = "";
        }
        if (!("edits" in $$source)) {
            /**
             * @member
             * @type {EditOp[]}
             */
            this["edits"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplyRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApplyRequest}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edits" in $$parsedSource) {
            $$parsedSource["edits"] = $$createField2_0($$parsedSource["edits"]);
        }
        return new ApplyRequest(/** @type {Partial<ApplyRequest>} */($$parsedSource));
    }
}

/**
 * CellView 差异格视图。Kind: "modified" | "left" | "right"。
 */
export class CellView {
    /**
     * Creates a new CellView instance.
     * @param {Partial<CellView>} [$$source = {}] - The source object to create the CellView.
     */
    constructor($$source = {}) {
        if (!("col" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["col"] = 0;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("formulaDiffers" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["formulaDiffers"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CellView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CellView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CellView(/** @type {Partial<CellView>} */($$parsedSource));
    }
}

/**
 * CompareRequest 前端比对请求。文件类型按左文件扩展名分流 (与 CLI 一致)。
 */
export class CompareRequest {
    /**
     * Creates a new CompareRequest instance.
     * @param {Partial<CompareRequest>} [$$source = {}] - The source object to create the CompareRequest.
     */
    constructor($$source = {}) {
        if (!("leftPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["leftPath"] = "";
        }
        if (!("rightPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rightPath"] = "";
        }
        if (!("keyColumns" in $$source)) {
            /**
             * 表格模式关键列 (0-based); 空则按行号位置配对
             * @member
             * @type {number[]}
             */
            this["keyColumns"] = [];
        }
        if (!("sheetName" in $$source)) {
            /**
             * xlsx 表名; 空则第一个
             * @member
             * @type {string}
             */
            this["sheetName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompareRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CompareRequest}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keyColumns" in $$parsedSource) {
            $$parsedSource["keyColumns"] = $$createField2_0($$parsedSource["keyColumns"]);
        }
        return new CompareRequest(/** @type {Partial<CompareRequest>} */($$parsedSource));
    }
}

/**
 * CompareResult 前端渲染数据: 表格模式填 Headers/Rows, 文本模式填 Lines。
 */
export class CompareResult {
    /**
     * Creates a new CompareResult instance.
     * @param {Partial<CompareResult>} [$$source = {}] - The source object to create the CompareResult.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * "sheet" | "text"
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["headers"] = [];
        }
        if (!("stats" in $$source)) {
            /**
             * @member
             * @type {engine$0.DiffStats}
             */
            this["stats"] = (new engine$0.DiffStats());
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {RowView[]}
             */
            this["rows"] = [];
        }
        if (!("lines" in $$source)) {
            /**
             * @member
             * @type {LineView[]}
             */
            this["lines"] = [];
        }
        if (!("leftName" in $$source)) {
            /**
             * 展示名: 文件基名 (表格模式追加表名)
             * @member
             * @type {string}
             */
            this["leftName"] = "";
        }
        if (!("rightName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rightName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompareResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CompareResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField1_0($$parsedSource["headers"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField2_0($$parsedSource["stats"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField3_0($$parsedSource["rows"]);
        }
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField4_0($$parsedSource["lines"]);
        }
        return new CompareResult(/** @type {Partial<CompareResult>} */($$parsedSource));
    }
}

/**
 * EditOp 一次单元格同步编辑 (前端攒批后经 Apply 一次性写回)。
 * Row/Col 为目标文件中的 1-based 绝对行列号; 三种互斥形态与 xlsx.CellEdit 一致:
 * Formula 非空写公式, ClearFormula=true 清公式, 其余写值。
 */
export class EditOp {
    /**
     * Creates a new EditOp instance.
     * @param {Partial<EditOp>} [$$source = {}] - The source object to create the EditOp.
     */
    constructor($$source = {}) {
        if (!("row" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["row"] = 0;
        }
        if (!("col" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["col"] = 0;
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("formula" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["formula"] = "";
        }
        if (!("clearFormula" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["clearFormula"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditOp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EditOp}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EditOp(/** @type {Partial<EditOp>} */($$parsedSource));
    }
}

/**
 * LineView 文本模式行视图。Kind: "equal" | "left" | "right"。
 */
export class LineView {
    /**
     * Creates a new LineView instance.
     * @param {Partial<LineView>} [$$source = {}] - The source object to create the LineView.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("leftIdx" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["leftIdx"] = 0;
        }
        if (!("rightIdx" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rightIdx"] = 0;
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LineView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LineView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LineView(/** @type {Partial<LineView>} */($$parsedSource));
    }
}

/**
 * RowView 一对对齐行的视图: LeftRow/RightRow 为源表行号 (0=该侧独有),
 * Left/Right 为单元格显示值数组, Diffs 为该行的差异格 (前端高亮用),
 * LeftFormulas/RightFormulas 为与值数组平行的公式数组 (空串=非公式格, 行同步写公式用)。
 */
export class RowView {
    /**
     * Creates a new RowView instance.
     * @param {Partial<RowView>} [$$source = {}] - The source object to create the RowView.
     */
    constructor($$source = {}) {
        if (!("leftRow" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["leftRow"] = 0;
        }
        if (!("rightRow" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rightRow"] = 0;
        }
        if (!("left" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["left"] = [];
        }
        if (!("right" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["right"] = [];
        }
        if (!("leftFormulas" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["leftFormulas"] = [];
        }
        if (!("rightFormulas" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["rightFormulas"] = [];
        }
        if (!("diffs" in $$source)) {
            /**
             * @member
             * @type {CellView[]}
             */
            this["diffs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RowView}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("left" in $$parsedSource) {
            $$parsedSource["left"] = $$createField2_0($$parsedSource["left"]);
        }
        if ("right" in $$parsedSource) {
            $$parsedSource["right"] = $$createField3_0($$parsedSource["right"]);
        }
        if ("leftFormulas" in $$parsedSource) {
            $$parsedSource["leftFormulas"] = $$createField4_0($$parsedSource["leftFormulas"]);
        }
        if ("rightFormulas" in $$parsedSource) {
            $$parsedSource["rightFormulas"] = $$createField5_0($$parsedSource["rightFormulas"]);
        }
        if ("diffs" in $$parsedSource) {
            $$parsedSource["diffs"] = $$createField6_0($$parsedSource["diffs"]);
        }
        return new RowView(/** @type {Partial<RowView>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = EditOp.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = engine$0.DiffStats.createFrom;
const $$createType5 = RowView.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = LineView.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = CellView.createFrom;
const $$createType10 = $Create.Array($$createType9);
