// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExcelConfigService 配置管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConfigExists 检查配置是否存在
 */
export function ConfigExists(): $CancellablePromise<boolean> {
    return $Call.ByID(3182115301);
}

/**
 * DeleteConfig 删除配置
 */
export function DeleteConfig(): $CancellablePromise<void> {
    return $Call.ByID(2272218250);
}

/**
 * GetConfig 获取当前配置
 * @frontend @mcp
 */
export function GetConfig(): $CancellablePromise<$models.ExcelConfig | null> {
    return $Call.ByID(1452457707).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetConfigFilePath 获取配置文件路径
 */
export function GetConfigFilePath(): $CancellablePromise<string> {
    return $Call.ByID(143504566);
}

/**
 * ResetToDefault 重置为默认配置
 */
export function ResetToDefault(): $CancellablePromise<$models.ExcelConfig | null> {
    return $Call.ByID(3861709604).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveConfig 保存配置
 * @frontend @mcp
 */
export function SaveConfig(config: $models.ExcelConfig | null): $CancellablePromise<void> {
    return $Call.ByID(2709548356, config);
}

/**
 * UpdateConfig 更新配置（部分更新）
 */
export function UpdateConfig(updates: { [_ in string]?: any }): $CancellablePromise<$models.ExcelConfig | null> {
    return $Call.ByID(1422926520, updates).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ExcelConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
