// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as excelio$0 from "../rain-excel-checker/xlsx/excelio/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json_rule$0 from "../rain-excel-checker/xlsx/json_rule/models.js";

/**
 * ColumnInfo 列详细信息
 */
export class ColumnInfo {
    /**
     * 中文名称
     */
    "chsName": string;

    /**
     * 字段名
     */
    "attrName": string;

    /**
     * 字段类型
     */
    "attrType": string;

    /**
     * 列状态
     */
    "colStatus": string;

    /**
     * 错误信息（如果有）
     */
    "error": string;

    /** Creates a new ColumnInfo instance. */
    constructor($$source: Partial<ColumnInfo> = {}) {
        if (!("chsName" in $$source)) {
            this["chsName"] = "";
        }
        if (!("attrName" in $$source)) {
            this["attrName"] = "";
        }
        if (!("attrType" in $$source)) {
            this["attrType"] = "";
        }
        if (!("colStatus" in $$source)) {
            this["colStatus"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnInfo($$parsedSource as Partial<ColumnInfo>);
    }
}

/**
 * ColumnPreview 列预览信息
 */
export class ColumnPreview {
    /**
     * 中文名称
     */
    "chsName": string;

    /**
     * 字段名
     */
    "fieldName": string;

    /**
     * 字段类型
     */
    "type": string;

    /**
     * 导出标识
     */
    "exportTag": string;

    /**
     * 列状态
     */
    "colStatus": string;

    /** Creates a new ColumnPreview instance. */
    constructor($$source: Partial<ColumnPreview> = {}) {
        if (!("chsName" in $$source)) {
            this["chsName"] = "";
        }
        if (!("fieldName" in $$source)) {
            this["fieldName"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("exportTag" in $$source)) {
            this["exportTag"] = "";
        }
        if (!("colStatus" in $$source)) {
            this["colStatus"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnPreview instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnPreview {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnPreview($$parsedSource as Partial<ColumnPreview>);
    }
}

/**
 * ExcelCheckResult Excel检查结果（包含列级、表级和解析错误）
 */
export class ExcelCheckResult {
    /**
     * 列级检查结果
     */
    "colResults": (json_rule$0.ColCheckResult | null)[];

    /**
     * 表级检查结果
     */
    "tableResults": (json_rule$0.TableCheckResult | null)[];

    /**
     * 文件解析错误
     */
    "parseErrors": (SheetParseError | null)[];

    /** Creates a new ExcelCheckResult instance. */
    constructor($$source: Partial<ExcelCheckResult> = {}) {
        if (!("colResults" in $$source)) {
            this["colResults"] = [];
        }
        if (!("tableResults" in $$source)) {
            this["tableResults"] = [];
        }
        if (!("parseErrors" in $$source)) {
            this["parseErrors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExcelCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExcelCheckResult {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("colResults" in $$parsedSource) {
            $$parsedSource["colResults"] = $$createField0_0($$parsedSource["colResults"]);
        }
        if ("tableResults" in $$parsedSource) {
            $$parsedSource["tableResults"] = $$createField1_0($$parsedSource["tableResults"]);
        }
        if ("parseErrors" in $$parsedSource) {
            $$parsedSource["parseErrors"] = $$createField2_0($$parsedSource["parseErrors"]);
        }
        return new ExcelCheckResult($$parsedSource as Partial<ExcelCheckResult>);
    }
}

/**
 * ExcelColumnDef Excel 列定义
 */
export class ExcelColumnDef {
    /**
     * 中文名称
     */
    "chsName": string;

    /**
     * 字段类型
     */
    "fieldType": string;

    /**
     * 字段名
     */
    "fieldName": string;

    /**
     * 导出标识: server/client/server/client
     */
    "exportTag": string;

    /** Creates a new ExcelColumnDef instance. */
    constructor($$source: Partial<ExcelColumnDef> = {}) {
        if (!("chsName" in $$source)) {
            this["chsName"] = "";
        }
        if (!("fieldType" in $$source)) {
            this["fieldType"] = "";
        }
        if (!("fieldName" in $$source)) {
            this["fieldName"] = "";
        }
        if (!("exportTag" in $$source)) {
            this["exportTag"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExcelColumnDef instance from a string or object.
     */
    static createFrom($$source: any = {}): ExcelColumnDef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExcelColumnDef($$parsedSource as Partial<ExcelColumnDef>);
    }
}

/**
 * ExcelConfig 应用配置结构
 */
export class ExcelConfig {
    "excel_resources_dir": string;
    "excel_case_dir": string;

    /**
     * 客户端项目路径，用于资源校验
     */
    "client_path": string;

    /** Creates a new ExcelConfig instance. */
    constructor($$source: Partial<ExcelConfig> = {}) {
        if (!("excel_resources_dir" in $$source)) {
            this["excel_resources_dir"] = "";
        }
        if (!("excel_case_dir" in $$source)) {
            this["excel_case_dir"] = "";
        }
        if (!("client_path" in $$source)) {
            this["client_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExcelConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ExcelConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExcelConfig($$parsedSource as Partial<ExcelConfig>);
    }
}

export class ExcelInfo {
    "Path": string;
    "Sheets": (excelio$0.Sheet | null)[];

    /** Creates a new ExcelInfo instance. */
    constructor($$source: Partial<ExcelInfo> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Sheets" in $$source)) {
            this["Sheets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExcelInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ExcelInfo {
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Sheets" in $$parsedSource) {
            $$parsedSource["Sheets"] = $$createField1_0($$parsedSource["Sheets"]);
        }
        return new ExcelInfo($$parsedSource as Partial<ExcelInfo>);
    }
}

/**
 * ExcelSheetDef Excel Sheet 定义
 */
export class ExcelSheetDef {
    /**
     * Sheet 名称
     */
    "sheetName": string;

    /**
     * 列定义
     */
    "columns": (ExcelColumnDef | null)[];

    /**
     * 数据行
     */
    "dataRows": string[][];

    /** Creates a new ExcelSheetDef instance. */
    constructor($$source: Partial<ExcelSheetDef> = {}) {
        if (!("sheetName" in $$source)) {
            this["sheetName"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("dataRows" in $$source)) {
            this["dataRows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExcelSheetDef instance from a string or object.
     */
    static createFrom($$source: any = {}): ExcelSheetDef {
        const $$createField1_0 = $$createType14;
        const $$createField2_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        if ("dataRows" in $$parsedSource) {
            $$parsedSource["dataRows"] = $$createField2_0($$parsedSource["dataRows"]);
        }
        return new ExcelSheetDef($$parsedSource as Partial<ExcelSheetDef>);
    }
}

/**
 * FieldChange 字段变更信息
 */
export class FieldChange {
    /**
     * 列名
     */
    "colName": string;

    /**
     * 旧值
     */
    "oldValue": string;

    /**
     * 新值
     */
    "newValue": string;

    /** Creates a new FieldChange instance. */
    constructor($$source: Partial<FieldChange> = {}) {
        if (!("colName" in $$source)) {
            this["colName"] = "";
        }
        if (!("oldValue" in $$source)) {
            this["oldValue"] = "";
        }
        if (!("newValue" in $$source)) {
            this["newValue"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FieldChange instance from a string or object.
     */
    static createFrom($$source: any = {}): FieldChange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FieldChange($$parsedSource as Partial<FieldChange>);
    }
}

/**
 * FilterCondition 过滤条件
 */
export class FilterCondition {
    /**
     * 列名（字段名或中文名）
     */
    "columnName": string;

    /**
     * 匹配值
     */
    "value": string;

    /**
     * 操作符: eq(等于), neq(不等于), contains(包含), startsWith(开头), endsWith(结尾)
     */
    "operator": string;

    /** Creates a new FilterCondition instance. */
    constructor($$source: Partial<FilterCondition> = {}) {
        if (!("columnName" in $$source)) {
            this["columnName"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("operator" in $$source)) {
            this["operator"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilterCondition instance from a string or object.
     */
    static createFrom($$source: any = {}): FilterCondition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FilterCondition($$parsedSource as Partial<FilterCondition>);
    }
}

/**
 * FilterResult 过滤查询结果
 */
export class FilterResult {
    /**
     * 文件路径
     */
    "filePath": string;

    /**
     * Sheet 名称
     */
    "sheetName": string;

    /**
     * 总行数
     */
    "totalRows": number;

    /**
     * 匹配行数
     */
    "matchedRows": number;

    /**
     * 表头（如果有）
     */
    "headers": string[];

    /**
     * 匹配的数据行
     */
    "dataRows": string[][];

    /** Creates a new FilterResult instance. */
    constructor($$source: Partial<FilterResult> = {}) {
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("sheetName" in $$source)) {
            this["sheetName"] = "";
        }
        if (!("totalRows" in $$source)) {
            this["totalRows"] = 0;
        }
        if (!("matchedRows" in $$source)) {
            this["matchedRows"] = 0;
        }
        if (!("headers" in $$source)) {
            this["headers"] = [];
        }
        if (!("dataRows" in $$source)) {
            this["dataRows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilterResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FilterResult {
        const $$createField4_0 = $$createType15;
        const $$createField5_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField4_0($$parsedSource["headers"]);
        }
        if ("dataRows" in $$parsedSource) {
            $$parsedSource["dataRows"] = $$createField5_0($$parsedSource["dataRows"]);
        }
        return new FilterResult($$parsedSource as Partial<FilterResult>);
    }
}

/**
 * RangeQueryResult 范围查询结果
 */
export class RangeQueryResult {
    /**
     * 文件路径
     */
    "filePath": string;

    /**
     * Sheet 名称
     */
    "sheetName": string;

    /**
     * 起始行号（数据行，从1开始）
     */
    "startRow": number;

    /**
     * 结束行号
     */
    "endRow": number;

    /**
     * 总行数
     */
    "totalRows": number;

    /**
     * 返回行数
     */
    "returnRows": number;

    /**
     * 表头（如果有）
     */
    "headers": string[];

    /**
     * 数据行
     */
    "dataRows": string[][];

    /** Creates a new RangeQueryResult instance. */
    constructor($$source: Partial<RangeQueryResult> = {}) {
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("sheetName" in $$source)) {
            this["sheetName"] = "";
        }
        if (!("startRow" in $$source)) {
            this["startRow"] = 0;
        }
        if (!("endRow" in $$source)) {
            this["endRow"] = 0;
        }
        if (!("totalRows" in $$source)) {
            this["totalRows"] = 0;
        }
        if (!("returnRows" in $$source)) {
            this["returnRows"] = 0;
        }
        if (!("headers" in $$source)) {
            this["headers"] = [];
        }
        if (!("dataRows" in $$source)) {
            this["dataRows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RangeQueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RangeQueryResult {
        const $$createField6_0 = $$createType15;
        const $$createField7_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField6_0($$parsedSource["headers"]);
        }
        if ("dataRows" in $$parsedSource) {
            $$parsedSource["dataRows"] = $$createField7_0($$parsedSource["dataRows"]);
        }
        return new RangeQueryResult($$parsedSource as Partial<RangeQueryResult>);
    }
}

/**
 * RowChangeInfo 行变更信息
 */
export class RowChangeInfo {
    /**
     * 行 ID
     */
    "rowId": string;

    /**
     * 行名称
     */
    "rowName": string;

    /** Creates a new RowChangeInfo instance. */
    constructor($$source: Partial<RowChangeInfo> = {}) {
        if (!("rowId" in $$source)) {
            this["rowId"] = "";
        }
        if (!("rowName" in $$source)) {
            this["rowName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowChangeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RowChangeInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RowChangeInfo($$parsedSource as Partial<RowChangeInfo>);
    }
}

/**
 * RowModifyInfo 行修改信息
 */
export class RowModifyInfo {
    /**
     * 行 ID
     */
    "rowId": string;

    /**
     * 行名称
     */
    "rowName": string;

    /**
     * 字段变更列表
     */
    "changes": (FieldChange | null)[];

    /** Creates a new RowModifyInfo instance. */
    constructor($$source: Partial<RowModifyInfo> = {}) {
        if (!("rowId" in $$source)) {
            this["rowId"] = "";
        }
        if (!("rowName" in $$source)) {
            this["rowName"] = "";
        }
        if (!("changes" in $$source)) {
            this["changes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowModifyInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RowModifyInfo {
        const $$createField2_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField2_0($$parsedSource["changes"]);
        }
        return new RowModifyInfo($$parsedSource as Partial<RowModifyInfo>);
    }
}

/**
 * SheetInfo 单个 Sheet 的信息
 */
export class SheetInfo {
    /**
     * Sheet 名称
     */
    "name": string;

    /**
     * Sheet 索引（从 0 开始）
     */
    "index": number;

    /** Creates a new SheetInfo instance. */
    constructor($$source: Partial<SheetInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("index" in $$source)) {
            this["index"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SheetInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SheetInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SheetInfo($$parsedSource as Partial<SheetInfo>);
    }
}

/**
 * SheetParseError Sheet解析错误
 */
export class SheetParseError {
    /**
     * Excel文件名
     */
    "fileName": string;

    /**
     * Sheet名称
     */
    "sheetName": string;

    /**
     * 错误信息
     */
    "error": string;

    /** Creates a new SheetParseError instance. */
    constructor($$source: Partial<SheetParseError> = {}) {
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("sheetName" in $$source)) {
            this["sheetName"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SheetParseError instance from a string or object.
     */
    static createFrom($$source: any = {}): SheetParseError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SheetParseError($$parsedSource as Partial<SheetParseError>);
    }
}

/**
 * SheetPreviewResult Sheet 预览结果
 */
export class SheetPreviewResult {
    /**
     * 文件路径
     */
    "filePath": string;

    /**
     * Sheet 名称
     */
    "sheetName": string;

    /**
     * 表头（中文名）
     */
    "headers": string[];

    /**
     * 字段类型
     */
    "types": string[];

    /**
     * 字段名
     */
    "fieldNames": string[];

    /**
     * 服务端/客户端标识
     */
    "exportTags": string[];

    /**
     * 列详细信息
     */
    "columns": (ColumnPreview | null)[];

    /**
     * 数据行（前 N 行）
     */
    "dataRows": string[][];

    /** Creates a new SheetPreviewResult instance. */
    constructor($$source: Partial<SheetPreviewResult> = {}) {
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("sheetName" in $$source)) {
            this["sheetName"] = "";
        }
        if (!("headers" in $$source)) {
            this["headers"] = [];
        }
        if (!("types" in $$source)) {
            this["types"] = [];
        }
        if (!("fieldNames" in $$source)) {
            this["fieldNames"] = [];
        }
        if (!("exportTags" in $$source)) {
            this["exportTags"] = [];
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("dataRows" in $$source)) {
            this["dataRows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SheetPreviewResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SheetPreviewResult {
        const $$createField2_0 = $$createType15;
        const $$createField3_0 = $$createType15;
        const $$createField4_0 = $$createType15;
        const $$createField5_0 = $$createType15;
        const $$createField6_0 = $$createType22;
        const $$createField7_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField2_0($$parsedSource["headers"]);
        }
        if ("types" in $$parsedSource) {
            $$parsedSource["types"] = $$createField3_0($$parsedSource["types"]);
        }
        if ("fieldNames" in $$parsedSource) {
            $$parsedSource["fieldNames"] = $$createField4_0($$parsedSource["fieldNames"]);
        }
        if ("exportTags" in $$parsedSource) {
            $$parsedSource["exportTags"] = $$createField5_0($$parsedSource["exportTags"]);
        }
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField6_0($$parsedSource["columns"]);
        }
        if ("dataRows" in $$parsedSource) {
            $$parsedSource["dataRows"] = $$createField7_0($$parsedSource["dataRows"]);
        }
        return new SheetPreviewResult($$parsedSource as Partial<SheetPreviewResult>);
    }
}

/**
 * TableChangeResult 表变更检测结果
 */
export class TableChangeResult {
    /**
     * 是否有变更
     */
    "hasChanges": boolean;

    /**
     * 是否是新文件（上一个 commit 不存在）
     */
    "isNewFile": boolean;

    /**
     * 基准 commit hash
     */
    "commitHash": string;

    /**
     * commit 消息
     */
    "commitMessage": string;

    /**
     * 新增行
     */
    "addedRows": (RowChangeInfo | null)[];

    /**
     * 删除行
     */
    "removedRows": (RowChangeInfo | null)[];

    /**
     * 修改行
     */
    "modifiedRows": (RowModifyInfo | null)[];

    /**
     * 新增列
     */
    "addedCols": string[];

    /**
     * 删除列
     */
    "removedCols": string[];

    /** Creates a new TableChangeResult instance. */
    constructor($$source: Partial<TableChangeResult> = {}) {
        if (!("hasChanges" in $$source)) {
            this["hasChanges"] = false;
        }
        if (!("isNewFile" in $$source)) {
            this["isNewFile"] = false;
        }
        if (!("commitHash" in $$source)) {
            this["commitHash"] = "";
        }
        if (!("commitMessage" in $$source)) {
            this["commitMessage"] = "";
        }
        if (!("addedRows" in $$source)) {
            this["addedRows"] = [];
        }
        if (!("removedRows" in $$source)) {
            this["removedRows"] = [];
        }
        if (!("modifiedRows" in $$source)) {
            this["modifiedRows"] = [];
        }
        if (!("addedCols" in $$source)) {
            this["addedCols"] = [];
        }
        if (!("removedCols" in $$source)) {
            this["removedCols"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableChangeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TableChangeResult {
        const $$createField4_0 = $$createType25;
        const $$createField5_0 = $$createType25;
        const $$createField6_0 = $$createType28;
        const $$createField7_0 = $$createType15;
        const $$createField8_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("addedRows" in $$parsedSource) {
            $$parsedSource["addedRows"] = $$createField4_0($$parsedSource["addedRows"]);
        }
        if ("removedRows" in $$parsedSource) {
            $$parsedSource["removedRows"] = $$createField5_0($$parsedSource["removedRows"]);
        }
        if ("modifiedRows" in $$parsedSource) {
            $$parsedSource["modifiedRows"] = $$createField6_0($$parsedSource["modifiedRows"]);
        }
        if ("addedCols" in $$parsedSource) {
            $$parsedSource["addedCols"] = $$createField7_0($$parsedSource["addedCols"]);
        }
        if ("removedCols" in $$parsedSource) {
            $$parsedSource["removedCols"] = $$createField8_0($$parsedSource["removedCols"]);
        }
        return new TableChangeResult($$parsedSource as Partial<TableChangeResult>);
    }
}

// Private type creation functions
const $$createType0 = json_rule$0.ColCheckResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = json_rule$0.TableCheckResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = SheetParseError.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = excelio$0.Sheet.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = ExcelColumnDef.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Array($Create.Any);
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = FieldChange.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = ColumnPreview.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = RowChangeInfo.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = RowModifyInfo.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = $Create.Array($$createType27);
