// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ItemCfg 道具配置
 */
export class ItemCfg {
    "ItemId": number;
    "Count": number;

    /** Creates a new ItemCfg instance. */
    constructor($$source: Partial<ItemCfg> = {}) {
        if (!("ItemId" in $$source)) {
            this["ItemId"] = 0;
        }
        if (!("Count" in $$source)) {
            this["Count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemCfg instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemCfg {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ItemCfg($$parsedSource as Partial<ItemCfg>);
    }
}

/**
 * SeasonPassBagDiff 赛季战令礼包表差异数据结构
 */
export class SeasonPassBagDiff {
    "Id": number;
    "Name": string;
    "SeasonPassId": number;
    "BagType": string;
    "IsUnlockTask": boolean;
    "UnlockHighlReward": boolean;
    "PassExtWeeklyExpLimit": number;
    "UnlockHeroQuality": number[];
    "AddLevel": number;
    "FirstReward": ItemCfg[];
    "UpReward": ItemCfg[];
    "ShowReward": ItemCfg[];

    /** Creates a new SeasonPassBagDiff instance. */
    constructor($$source: Partial<SeasonPassBagDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("SeasonPassId" in $$source)) {
            this["SeasonPassId"] = 0;
        }
        if (!("BagType" in $$source)) {
            this["BagType"] = "";
        }
        if (!("IsUnlockTask" in $$source)) {
            this["IsUnlockTask"] = false;
        }
        if (!("UnlockHighlReward" in $$source)) {
            this["UnlockHighlReward"] = false;
        }
        if (!("PassExtWeeklyExpLimit" in $$source)) {
            this["PassExtWeeklyExpLimit"] = 0;
        }
        if (!("UnlockHeroQuality" in $$source)) {
            this["UnlockHeroQuality"] = [];
        }
        if (!("AddLevel" in $$source)) {
            this["AddLevel"] = 0;
        }
        if (!("FirstReward" in $$source)) {
            this["FirstReward"] = [];
        }
        if (!("UpReward" in $$source)) {
            this["UpReward"] = [];
        }
        if (!("ShowReward" in $$source)) {
            this["ShowReward"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SeasonPassBagDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): SeasonPassBagDiff {
        const $$createField7_0 = $$createType0;
        const $$createField9_0 = $$createType2;
        const $$createField10_0 = $$createType2;
        const $$createField11_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("UnlockHeroQuality" in $$parsedSource) {
            $$parsedSource["UnlockHeroQuality"] = $$createField7_0($$parsedSource["UnlockHeroQuality"]);
        }
        if ("FirstReward" in $$parsedSource) {
            $$parsedSource["FirstReward"] = $$createField9_0($$parsedSource["FirstReward"]);
        }
        if ("UpReward" in $$parsedSource) {
            $$parsedSource["UpReward"] = $$createField10_0($$parsedSource["UpReward"]);
        }
        if ("ShowReward" in $$parsedSource) {
            $$parsedSource["ShowReward"] = $$createField11_0($$parsedSource["ShowReward"]);
        }
        return new SeasonPassBagDiff($$parsedSource as Partial<SeasonPassBagDiff>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ItemCfg.createFrom;
const $$createType2 = $Create.Array($$createType1);
