// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InterceptService 劫持服务
 * 用于在测试阶段劫持飞书消息发送，在本地弹窗显示而非真正发送到飞书服务器
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddMessage 添加消息（内部调用）
 * 返回添加的消息，供调用方通过事件推送到前端
 */
export function AddMessage(robotGUID: string, msgType: string, content: string): $CancellablePromise<$models.InterceptedMessage> {
    return $Call.ByID(1190293174, robotGUID, msgType, content).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ClearMessages 清空消息
 * @frontend
 */
export function ClearMessages(): $CancellablePromise<void> {
    return $Call.ByID(2599286545);
}

/**
 * GetMessages 获取所有消息
 * @frontend
 */
export function GetMessages(): $CancellablePromise<$models.InterceptedMessage[]> {
    return $Call.ByID(2672753332).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * IsEnabled 检查劫持开关状态
 * @frontend
 */
export function IsEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(2671022149);
}

/**
 * SetEnabled 设置劫持开关
 * @frontend
 */
export function SetEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(925988773, enabled);
}

/**
 * SetMaxMessages 设置最大保留消息数
 */
export function SetMaxMessages(max: number): $CancellablePromise<void> {
    return $Call.ByID(2308801758, max);
}

// Private type creation functions
const $$createType0 = $models.InterceptedMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
