// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

/**
 * InterceptedMessage 被劫持的消息
 */
export class InterceptedMessage {
    /**
     * 唯一ID
     */
    "id": string;

    /**
     * 机器人GUID
     */
    "robotGuid": string;

    /**
     * 消息类型：text / interactive
     */
    "msgType": string;

    /**
     * 消息内容（文本或JSON）
     */
    "content": string;

    /**
     * 发送时间
     */
    "timestamp": time$0.Time;

    /** Creates a new InterceptedMessage instance. */
    constructor($$source: Partial<InterceptedMessage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("robotGuid" in $$source)) {
            this["robotGuid"] = "";
        }
        if (!("msgType" in $$source)) {
            this["msgType"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InterceptedMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): InterceptedMessage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InterceptedMessage($$parsedSource as Partial<InterceptedMessage>);
    }
}
