// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CellError 单元格错误/变更信息
 */
export class CellError {
    /**
     * 定位 第几行（列级规则为相对偏移，表级规则为绝对索引）
     */
    "Index": number;

    /**
     * 错误日志
     */
    "Reason": string;

    /**
     * 变更详情（RowChangeDetail 或 ColumnChangeDetail）
     */
    "Detail": any;

    /**
     * 实际 Excel 行号（1-indexed），0 表示未设置，展示层应 fallback 到 Index+1
     */
    "ExcelRow": number;

    /** Creates a new CellError instance. */
    constructor($$source: Partial<CellError> = {}) {
        if (!("Index" in $$source)) {
            this["Index"] = 0;
        }
        if (!("Reason" in $$source)) {
            this["Reason"] = "";
        }
        if (!("Detail" in $$source)) {
            this["Detail"] = null;
        }
        if (!("ExcelRow" in $$source)) {
            this["ExcelRow"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CellError instance from a string or object.
     */
    static createFrom($$source: any = {}): CellError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CellError($$parsedSource as Partial<CellError>);
    }
}

export class ColCheckResult {
    /**
     * 定位
     */
    "TableName": string | null;
    "SheetName": string | null;
    "ColName": string | null;

    /**
     * 定位 第几列
     */
    "ColIndex": number | null;
    "ErrCells": (CellError | null)[];

    /**
     * 结果
     */
    "Ok": boolean;
    "Reason": string;

    /** Creates a new ColCheckResult instance. */
    constructor($$source: Partial<ColCheckResult> = {}) {
        if (!("TableName" in $$source)) {
            this["TableName"] = null;
        }
        if (!("SheetName" in $$source)) {
            this["SheetName"] = null;
        }
        if (!("ColName" in $$source)) {
            this["ColName"] = null;
        }
        if (!("ColIndex" in $$source)) {
            this["ColIndex"] = null;
        }
        if (!("ErrCells" in $$source)) {
            this["ErrCells"] = [];
        }
        if (!("Ok" in $$source)) {
            this["Ok"] = false;
        }
        if (!("Reason" in $$source)) {
            this["Reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ColCheckResult {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ErrCells" in $$parsedSource) {
            $$parsedSource["ErrCells"] = $$createField4_0($$parsedSource["ErrCells"]);
        }
        return new ColCheckResult($$parsedSource as Partial<ColCheckResult>);
    }
}

export class ColRule {
    /**
     * @json-critical 规则类型，如 "NUMERIC_RANGE", "ALL_BASE", "ENUM"
     */
    "Type": EColRule;

    /**
     * @json-critical 规则唯一标识
     */
    "Uuid": string;

    /**
     * @json-critical 规则显示名称
     */
    "DisplayName": string;

    /**
     * @json-critical 是否启用
     */
    "Enabled": boolean;

    /**
     * Params map[ERuleParam]string 这个wails3的ts自动绑定生成为 {[_:ERuleParam]:string} 有问题, github有issue 待解决
     * ⚠️ Params 的 key 必须与 ERuleParam 枚举值一致，否则规则参数读取会失败
     * ⚠️ 历史问题: NUMERIC_RANGE 规则曾使用 "min"/"max" 而非 "minValue"/"maxValue" 导致检查失效
     * @json-critical 规则参数，key对应ERuleParam枚举值
     */
    "Params": { [_ in string]?: string };

    /** Creates a new ColRule instance. */
    constructor($$source: Partial<ColRule> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = EColRule.$zero;
        }
        if (!("Uuid" in $$source)) {
            this["Uuid"] = "";
        }
        if (!("DisplayName" in $$source)) {
            this["DisplayName"] = "";
        }
        if (!("Enabled" in $$source)) {
            this["Enabled"] = false;
        }
        if (!("Params" in $$source)) {
            this["Params"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColRule instance from a string or object.
     */
    static createFrom($$source: any = {}): ColRule {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Params" in $$parsedSource) {
            $$parsedSource["Params"] = $$createField4_0($$parsedSource["Params"]);
        }
        return new ColRule($$parsedSource as Partial<ColRule>);
    }
}

export enum EColRule {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 测试
     */
    TEST = "TEST",

    /**
     * 从1依次自增的ID
     */
    INCREASE_ID = "INCREASE_ID",

    /**
     * 唯一不重复
     */
    UNIQUE = "UNIQUE",

    /**
     * 仅中文
     */
    CHS_ONLY = "CHS_ONLY",

    /**
     * 不为空
     */
    NOT_EMPTY = "NOT_EMPTY",

    /**
     * 前端还是后端
     */
    SERVER_OR_CLIENT = "SERVER_OR_CLIENT",

    /**
     * 以上所有基础规则合并
     */
    ALL_BASE = "ALL_BASE",

    /**
     * 数值类型
     */
    NUMERIC = "NUMERIC",

    /**
     * 检测日期类型, 日期格式、日期范围等
     */
    DATE = "DATE",

    /**
     * 布尔值类型
     */
    BOOLEAN = "BOOLEAN",

    /**
     * 单元格应为字符串
     */
    STRING = "STRING",

    /**
     * 日期范围
     */
    DATE_RANGE = "DATE_RANGE",

    /**
     * 日期跨度
     */
    DATE_DURATION = "DATE_DURATION",

    /**
     * 范围内整数
     */
    NUMERIC_RANGE = "NUMERIC_RANGE",

    /**
     * 固定枚举
     */
    ENUM = "ENUM",

    /**
     * 关联表
     */
    FOREIGN_KEY = "FOREIGN_KEY",

    /**
     * 跨表引用检查
     */
    CROSS_REFERENCE = "CROSS_REFERENCE",

    /**
     * 拆分引用检查
     */
    SPLIT_REGERENCE = "SPLIT_REGERENCE",

    /**
     * 跨表关系链检查
     */
    CHAIN_REFERENCE = "CHAIN_REFERENCE",

    /**
     * 特殊格式检查 - 道具id+数量：{1000005;1}{1000011;10}{9000001;5}
     */
    SPECIAL_FORMAT = "SPECIAL_FORMAT",

    /**
     * 自定义正则检查 - 道具id+数量：{1000005;1}{1000011;10}{9000001;5}
     */
    REGEX = "REGEX",
    WEIGHT_SUM = "WEIGHT_SUM",
    DATE_CONSISTENCY = "DATE_CONSISTENCY",
    RESOURCE = "RESOURCE",
    PIN_YIN_CHS = "PIN_YIN_CHS",
    RICH_TEXT = "RICH_TEXT",
};

export enum ERuleParam {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NONE = "none",

    /**
     * ---一般传参---
     * 允许空值
     */
    ALLOW_EMPTY = "allowEmpty",

    /**
     * 排除的值 逗号间隔
     */
    EXCEPTS = "excepts",

    /**
     * 允许注释值 正则，比如 ^#.*
     */
    ALLOW_COMMIT = "allowCommit",

    /**
     * 枚举值 逗号间隔
     */
    ENUMS = "enums",

    /**
     * 列截断检测连续空单元格格数
     */
    BREAK_LINE = "breakLine",

    /**
     * 使用ID列确定数据结束位置（避免不同列截断位置不一致）
     */
    USE_ID_COL_FOR_END = "useIdColForEnd",

    /**
     * 严格检查
     */
    STRICT = "strict",

    /**
     * 比较规则 eq（等于）、gt（大于）、lt（小于）、ge（大于等于）、le（小于等于）
     */
    COMPARE_RULE = "compareRule",

    /**
     * 容差
     */
    TOLERANCE = "tolerance",

    /**
     * 最小值
     */
    MIN = "min",

    /**
     * 最大值
     */
    MAX = "max",

    /**
     * 正则表达式
     */
    PATTERN = "pattern",

    /**
     * 正则表达式捕获组
     */
    GROUPS = "groups",

    /**
     * 条件过滤列名（仅当该行指定列的值等于filterVal时才执行检查）
     */
    FILTER_COL = "filterCol",

    /**
     * 条件过滤值
     */
    FILTER_VAL = "filterVal",

    /**
     * 过滤值是否数组（"true" 时按逗号拆分多值匹配）
     */
    FILTER_IS_ARRAY = "filterIsArray",

    /**
     * 过滤模式: ""(单值) | "multi"(多值) | "withinDays"(距今<N天)
     */
    FILTER_MODE = "filterMode",

    /**
     * 距今天数（仅 filterMode="withinDays" 时使用）
     */
    FILTER_DAYS = "filterDays",

    /**
     * 开始日期
     */
    START_DATE = "startDate",

    /**
     * 结束日期
     */
    END_DATE = "endDate",

    /**
     * ---表级规则参数---
     * SeasonEndTime 列名（默认: SeasonEndTime）
     */
    SEASON_END_TIME_COL = "seasonEndTimeCol",

    /**
     * 提前警告时间（默认: 168h 即7天）
     */
    TIME_RANGE_BEFORE = "timeRangeBefore",

    /**
     * ---通用通知规则参数---
     * ID列名（默认: Id）
     */
    ID_COL_NAME = "idColName",

    /**
     * 复合主键列名（逗号分隔，如 "AnimationState,ItemCfgId"），优先级高于 ID_COL_NAME
     */
    ID_COL_NAMES = "idColNames",

    /**
     * 名称列名（默认: Name）
     */
    NAME_COL_NAME = "nameColName",

    /**
     * 历史数据JSON路径
     */
    OLD_DATA_PATH = "oldDataPath",

    /**
     * 是否通知新增行（默认: true）
     */
    NOTIFY_ADDED_ROWS = "notifyAddedRows",

    /**
     * 是否通知删除行（默认: true）
     */
    NOTIFY_REMOVED_ROWS = "notifyRemovedRows",

    /**
     * 是否通知新增列（默认: true）
     */
    NOTIFY_ADDED_COLS = "notifyAddedCols",

    /**
     * 是否通知删除列（默认: true）
     */
    NOTIFY_REMOVED_COLS = "notifyRemovedCols",

    /**
     * ---Git diff 模式参数---
     * 使用 git diff 替代快照（默认: true）
     */
    USE_GIT_DIFF = "useGitDiff",

    /**
     * Git 仓库路径（默认: Excel 文件所在目录）
     */
    GIT_REPO_PATH = "gitRepoPath",

    /**
     * 基准 commit（默认: HEAD~1）
     */
    BASE_COMMIT = "baseCommit",

    /**
     * 当前检查的 commit hash（merge 场景为子 commit，普通场景为 HEAD）
     */
    HEAD_COMMIT = "headCommit",

    /**
     * ---列连续性检查规则参数---
     * 检查列名
     */
    TARGET_COL = "targetCol",

    /**
     * 检查模式
     */
    CHECK_MODE = "checkMode",

    /**
     * 检查范围
     */
    SCOPE = "scope",

    /**
     * 起始值
     */
    START_VALUE = "startValue",

    /**
     * 排除行号
     */
    EXCLUDE_ROWS = "excludeRows",

    /**
     * 拆分分隔符（SPLIT_UNIQUE 模式）
     */
    SEPARATOR = "separator",

    /**
     * ---武将检查规则参数---
     * 提前警告天数（默认: 5）
     */
    WARN_DAYS_BEFORE = "warnDaysBefore",

    /**
     * 掉落延迟月数（默认: 3）
     */
    DROP_MONTHS_DELAY = "dropMonthsDelay",

    /**
     * 技能列名（默认: Skill）
     */
    SKILL_COL_NAME = "skillColName",

    /**
     * 可熔炼列名（默认: CanMelt）
     */
    CAN_MELT_COL_NAME = "canMeltColName",

    /**
     * 是否开放列名（默认: IsOpen）
     */
    IS_OPEN_COL_NAME = "isOpenColName",

    /**
     * 开放时间列名（默认: OpenDate）
     */
    OPEN_DATE_COL_NAME = "openDateColName",

    /**
     * 战令保护期月数（默认: 4）
     */
    PROTECT_MONTHS = "protectMonths",

    /**
     * ---关系链检查规则参数---
     * 关系链步骤配置（JSON字符串）
     */
    CHAIN_STEPS = "chainSteps",

    /**
     * 比较类型：match/not_match/time_overlap/exists/not_exists
     */
    CHAIN_COMPARE = "chainCompare",

    /**
     * 匹配阶段类型（两阶段门控模型的匹配规则）
     */
    CHAIN_MATCH_COMPARE = "chainMatchCompare",

    /**
     * 来源链最终字段（用于时间比较）
     */
    CHAIN_LEFT_KEY = "chainLeftKey",

    /**
     * 目标链最终字段（用于时间比较）
     */
    CHAIN_RIGHT_KEY = "chainRightKey",

    /**
     * 关系链所需的关联表（逗号分隔），由前端从 chainSteps 中提取目标表名后填充
     */
    CHAIN_REQUIRED_SHEETS = "chainRequiredSheets",

    /**
     * 预警窗口提前量（Go duration，如"168h"）；"0"表示无条件启用
     */
    CHAIN_WARN_BEFORE = "chainWarnBefore",

    /**
     * 预警时间所在表名
     */
    CHAIN_WARN_SHEET = "chainWarnSheet",

    /**
     * 预警时间所在列名
     */
    CHAIN_WARN_COL = "chainWarnCol",
};

/**
 * ETableRule 表级规则类型枚举
 */
export enum ETableRule {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 竞技场赛季检查
     */
    ARENA_SEASON_CHECK = "ARENA_SEASON_CHECK",

    /**
     * Deprecated: 使用 ADDED_ROW_NOTIFY + REMOVED_ROW_NOTIFY + ADDED_COL_NOTIFY + REMOVED_COL_NOTIFY
     */
    NEW_ROW_NOTIFY = "NEW_ROW_NOTIFY",

    /**
     * Deprecated: 使用 MODIFIED_ROW_NOTIFY
     */
    ROW_CHANGE_NOTIFY = "ROW_CHANGE_NOTIFY",

    /**
     * 战令武将开放时间检查
     */
    SEASON_PASS_HERO_OPEN_CHECK = "SEASON_PASS_HERO_OPEN_CHECK",

    /**
     * 大将军武将开放时间检查
     */
    ARENA_GENERAL_HERO_OPEN_CHECK = "ARENA_GENERAL_HERO_OPEN_CHECK",

    /**
     * 武将抽卡掉落检查
     */
    HERO_DROP_CHECK = "HERO_DROP_CHECK",

    /**
     * 武将合成检查
     */
    HERO_SYNTHESIS_CHECK = "HERO_SYNTHESIS_CHECK",

    /**
     * 武将熔炼检查
     */
    HERO_MELT_CHECK = "HERO_MELT_CHECK",

    /**
     * 新增行通知（拆分自 NEW_ROW_NOTIFY）
     */
    ADDED_ROW_NOTIFY = "ADDED_ROW_NOTIFY",

    /**
     * 删除行通知（拆分自 NEW_ROW_NOTIFY）
     */
    REMOVED_ROW_NOTIFY = "REMOVED_ROW_NOTIFY",

    /**
     * 新增列通知（拆分自 NEW_ROW_NOTIFY）
     */
    ADDED_COL_NOTIFY = "ADDED_COL_NOTIFY",

    /**
     * 删除列通知（拆分自 NEW_ROW_NOTIFY）
     */
    REMOVED_COL_NOTIFY = "REMOVED_COL_NOTIFY",

    /**
     * 修改行通知（原 ROW_CHANGE_NOTIFY）
     */
    MODIFIED_ROW_NOTIFY = "MODIFIED_ROW_NOTIFY",

    /**
     * 活动任务奖励检查
     */
    ACTIVITY_TASK_REWARD_CHECK = "ACTIVITY_TASK_REWARD_CHECK",

    /**
     * 掉落道具必须在道具表中
     */
    DROP_ITEM_MUST_IN_ITEM_CHECK = "DROP_ITEM_MUST_IN_ITEM_CHECK",

    /**
     * 皮肤抽奖副产品检查
     */
    DRAWSKIN_BYPRODUCT_CHECK = "DRAWSKIN_BYPRODUCT_CHECK",

    /**
     * 丹青阁活动时间校验
     */
    DANQINGGE_TIME_ACTIVE_CHECK = "DANQINGGE_TIME_ACTIVE_CHECK",

    /**
     * 丹青阁活动自定义参数检查
     */
    DANQINGGE_CUSTOM_PARAM_IS_ITEMID_CHECK = "DANQINGGE_CUSTOM_PARAM_IS_ITEMID_CHECK",

    /**
     * 武将技能和Buff引用完整性检查
     */
    HERO_SKILL_BUFF_CHECK = "HERO_SKILL_BUFF_CHECK",

    /**
     * 抽奖池掉落规则引用检查
     */
    DRAW_DROP_RULE_REFERENCE_CHECK = "DRAW_DROP_RULE_REFERENCE_CHECK",

    /**
     * 掉落规则组ID引用检查
     */
    DROP_RULE_GROUP_ID_CHECK = "DROP_RULE_GROUP_ID_CHECK",

    /**
     * 丹青阁活动时间配置检查(ACT-04/05/06)
     */
    ACTIVITY_DANQINGGE_TIME_CONFIG_CHECK = "ACTIVITY_DANQINGGE_TIME_CONFIG_CHECK",

    /**
     * DrawSkin单抽消耗检查(DSK-06/07/08)
     */
    DRAWSKIN_ONCE_ITEM_COST_CHECK = "DRAWSKIN_ONCE_ITEM_COST_CHECK",

    /**
     * DrawSkin基础数据检查(DSK-01/12)
     */
    DRAWSKIN_DATA_VALIDITY_CHECK = "DRAWSKIN_DATA_VALIDITY_CHECK",

    /**
     * DrawSkin十连消耗检查(DSK-09)
     */
    DRAWSKIN_TEN_COST_CHECK = "DRAWSKIN_TEN_COST_CHECK",

    /**
     * DrawSkin时间范围检查(DSK-10/11)
     */
    DRAWSKIN_TIME_RANGE_CHECK = "DRAWSKIN_TIME_RANGE_CHECK",

    /**
     * Activity与DrawSkin交叉引用检查(DSK-05/XC-01/XC-04)
     */
    ACTIVITY_DRAWSKIN_CROSS_REFERENCE_CHECK = "ACTIVITY_DRAWSKIN_CROSS_REFERENCE_CHECK",

    /**
     * Activity与DrawSkin时间交集检查(XC-02)
     */
    ACTIVITY_DRAWSKIN_TIME_OVERLAP_CHECK = "ACTIVITY_DRAWSKIN_TIME_OVERLAP_CHECK",

    /**
     * DropRule基础数据检查
     */
    DROP_RULE_DATA_VALIDITY_CHECK = "DROP_RULE_DATA_VALIDITY_CHECK",

    /**
     * DropRule条件引用检查
     */
    DROP_RULE_CONDITIONAL_CHECK = "DROP_RULE_CONDITIONAL_CHECK",

    /**
     * DropItem条件和互斥检查
     */
    DROP_ITEM_VALIDITY_CHECK = "DROP_ITEM_VALIDITY_CHECK",

    /**
     * 日期有效性检查(ValidDate <= ExpireDate)
     */
    DATE_VALID_EXPIRE_CHECK = "DATE_VALID_EXPIRE_CHECK",

    /**
     * 列连续性检查
     */
    COL_CONTINUOUS_CHECK = "COL_CONTINUOUS_CHECK",

    /**
     * 定向招募战令保护期检查
     */
    DRAWFIX_PROTECTION_CHECK = "DRAWFIX_PROTECTION_CHECK",

    /**
     * 定向招募大将军保护期检查
     */
    DRAWFIX_ARENA_PROTECTION_CHECK = "DRAWFIX_ARENA_PROTECTION_CHECK",

    /**
     * 武将IsOpen与OpenDate一致性检查
     */
    HERO_ISOPEN_OPENDATE_CHECK = "HERO_ISOPEN_OPENDATE_CHECK",

    /**
     * 普通武将掉落时间检查
     */
    HERO_DROP_VALIDDATE_CHECK = "HERO_DROP_VALIDDATE_CHECK",

    /**
     * 战令高级奖励道具引用完整性检查
     */
    SEASON_PASS_REWARD_INTEGRITY_CHECK = "SEASON_PASS_REWARD_INTEGRITY_CHECK",
};

export class GiantLabel {
    "Name": string;

    /** Creates a new GiantLabel instance. */
    constructor($$source: Partial<GiantLabel> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GiantLabel instance from a string or object.
     */
    static createFrom($$source: any = {}): GiantLabel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GiantLabel($$parsedSource as Partial<GiantLabel>);
    }
}

export class ManagerList {
    /**
     * 负责QA
     */
    "QA": (GiantLabel | null)[];

    /**
     * 负责策划
     */
    "Designer": (GiantLabel | null)[];

    /**
     * 负责程序
     */
    "Programmer": (GiantLabel | null)[];

    /** Creates a new ManagerList instance. */
    constructor($$source: Partial<ManagerList> = {}) {
        if (!("QA" in $$source)) {
            this["QA"] = [];
        }
        if (!("Designer" in $$source)) {
            this["Designer"] = [];
        }
        if (!("Programmer" in $$source)) {
            this["Programmer"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManagerList instance from a string or object.
     */
    static createFrom($$source: any = {}): ManagerList {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("QA" in $$parsedSource) {
            $$parsedSource["QA"] = $$createField0_0($$parsedSource["QA"]);
        }
        if ("Designer" in $$parsedSource) {
            $$parsedSource["Designer"] = $$createField1_0($$parsedSource["Designer"]);
        }
        if ("Programmer" in $$parsedSource) {
            $$parsedSource["Programmer"] = $$createField2_0($$parsedSource["Programmer"]);
        }
        return new ManagerList($$parsedSource as Partial<ManagerList>);
    }
}

/**
 * SelectOption 下拉选项
 */
export class SelectOption {
    /**
     * 显示文本
     */
    "label": string;

    /**
     * 实际值
     */
    "value": string;

    /** Creates a new SelectOption instance. */
    constructor($$source: Partial<SelectOption> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelectOption instance from a string or object.
     */
    static createFrom($$source: any = {}): SelectOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SelectOption($$parsedSource as Partial<SelectOption>);
    }
}

export class SheetColRule {
    /**
     * @json-critical 列属性名
     */
    "PropName": string;

    /**
     * @json-critical 列数据类型，如 "int", "string", "EHeroAchieve"
     */
    "PropType": string;

    /**
     * @json-critical 该列应用的检查规则列表
     */
    "PropRules": (ColRule | null)[];

    /** Creates a new SheetColRule instance. */
    constructor($$source: Partial<SheetColRule> = {}) {
        if (!("PropName" in $$source)) {
            this["PropName"] = "";
        }
        if (!("PropType" in $$source)) {
            this["PropType"] = "";
        }
        if (!("PropRules" in $$source)) {
            this["PropRules"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SheetColRule instance from a string or object.
     */
    static createFrom($$source: any = {}): SheetColRule {
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("PropRules" in $$parsedSource) {
            $$parsedSource["PropRules"] = $$createField2_0($$parsedSource["PropRules"]);
        }
        return new SheetColRule($$parsedSource as Partial<SheetColRule>);
    }
}

/**
 * SheetRule 单个Sheet的完整规则配置
 * ⚠️ 以下字段名与 cases/excel_cases/*.json 配置文件强耦合，修改需同步更新所有JSON配置
 * ⚠️ 历史问题参考: commit 2ee0e9c (字段名不一致导致功能失效)
 */
export class SheetRule {
    /**
     * @json-critical 配表名，如 "角色成就|HeroAchieve"
     */
    "sheet": string;

    /**
     * @json-critical 管理人员配置
     */
    "managerList": ManagerList | null;

    /**
     * @json-critical 列级检查规则，key为列名
     */
    "rules": { [_ in string]?: SheetColRule | null };

    /**
     * @json-critical 表级规则列表
     */
    "tableRules": (TableRule | null)[];

    /** Creates a new SheetRule instance. */
    constructor($$source: Partial<SheetRule> = {}) {
        if (!("sheet" in $$source)) {
            this["sheet"] = "";
        }
        if (!("managerList" in $$source)) {
            this["managerList"] = null;
        }
        if (!("rules" in $$source)) {
            this["rules"] = {};
        }
        if (!("tableRules" in $$source)) {
            this["tableRules"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SheetRule instance from a string or object.
     */
    static createFrom($$source: any = {}): SheetRule {
        const $$createField1_0 = $$createType11;
        const $$createField2_0 = $$createType14;
        const $$createField3_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("managerList" in $$parsedSource) {
            $$parsedSource["managerList"] = $$createField1_0($$parsedSource["managerList"]);
        }
        if ("rules" in $$parsedSource) {
            $$parsedSource["rules"] = $$createField2_0($$parsedSource["rules"]);
        }
        if ("tableRules" in $$parsedSource) {
            $$parsedSource["tableRules"] = $$createField3_0($$parsedSource["tableRules"]);
        }
        return new SheetRule($$parsedSource as Partial<SheetRule>);
    }
}

/**
 * TableCheckResult 表级校验结果
 */
export class TableCheckResult {
    "tableName": string | null;
    "sheetName": string | null;
    "ruleType": ETableRule;
    "displayName": string;
    "ok": boolean;
    "reason": string;
    "errCells": (CellError | null)[];

    /** Creates a new TableCheckResult instance. */
    constructor($$source: Partial<TableCheckResult> = {}) {
        if (!("tableName" in $$source)) {
            this["tableName"] = null;
        }
        if (!("sheetName" in $$source)) {
            this["sheetName"] = null;
        }
        if (!("ruleType" in $$source)) {
            this["ruleType"] = ETableRule.$zero;
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("errCells" in $$source)) {
            this["errCells"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TableCheckResult {
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errCells" in $$parsedSource) {
            $$parsedSource["errCells"] = $$createField6_0($$parsedSource["errCells"]);
        }
        return new TableCheckResult($$parsedSource as Partial<TableCheckResult>);
    }
}

/**
 * TableRule 表级校验规则
 */
export class TableRule {
    /**
     * 规则类型（机器识别）
     */
    "type": ETableRule;

    /**
     * 显示名称（人类可读，如"竞技场赛季不足"）
     */
    "displayName": string;

    /**
     * 唯一标识
     */
    "uuid": string;

    /**
     * 规则描述
     */
    "description": string;

    /**
     * 规则参数
     */
    "params": { [_ in string]?: string };

    /**
     * 是否启用
     */
    "enabled": boolean;

    /** Creates a new TableRule instance. */
    constructor($$source: Partial<TableRule> = {}) {
        if (!("type" in $$source)) {
            this["type"] = ETableRule.$zero;
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("params" in $$source)) {
            this["params"] = {};
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableRule instance from a string or object.
     */
    static createFrom($$source: any = {}): TableRule {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField4_0($$parsedSource["params"]);
        }
        return new TableRule($$parsedSource as Partial<TableRule>);
    }
}

/**
 * TableRuleMeta 表级规则元数据（用于 MCP 和前端）
 */
export class TableRuleMeta {
    "type": ETableRule;
    "displayName": string;
    "description": string;

    /**
     * 适用的表名列表（支持后缀匹配，如 "ArenaSeason" 匹配 "竞技场赛季|ArenaSeason"）
     */
    "targetSheets": string[];

    /**
     * 规则执行所需的关联表名列表（如 HERO_DROP_CHECK 需要 "DropItem"、"Item"）；为空表示仅依赖 TargetSheets
     */
    "requiredSheets": string[];
    "paramDefs": TableRuleParamDef[];

    /** Creates a new TableRuleMeta instance. */
    constructor($$source: Partial<TableRuleMeta> = {}) {
        if (!("type" in $$source)) {
            this["type"] = ETableRule.$zero;
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("targetSheets" in $$source)) {
            this["targetSheets"] = [];
        }
        if (!("requiredSheets" in $$source)) {
            this["requiredSheets"] = [];
        }
        if (!("paramDefs" in $$source)) {
            this["paramDefs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableRuleMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): TableRuleMeta {
        const $$createField3_0 = $$createType18;
        const $$createField4_0 = $$createType18;
        const $$createField5_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("targetSheets" in $$parsedSource) {
            $$parsedSource["targetSheets"] = $$createField3_0($$parsedSource["targetSheets"]);
        }
        if ("requiredSheets" in $$parsedSource) {
            $$parsedSource["requiredSheets"] = $$createField4_0($$parsedSource["requiredSheets"]);
        }
        if ("paramDefs" in $$parsedSource) {
            $$parsedSource["paramDefs"] = $$createField5_0($$parsedSource["paramDefs"]);
        }
        return new TableRuleMeta($$parsedSource as Partial<TableRuleMeta>);
    }
}

/**
 * TableRuleParamDef 表级规则参数定义
 */
export class TableRuleParamDef {
    /**
     * 参数键
     */
    "key": ERuleParam;

    /**
     * UI 显示标签
     */
    "label": string;

    /**
     * 参数说明
     */
    "description": string;

    /**
     * 参数类型: string, duration, number, select
     */
    "type": string;

    /**
     * 默认值
     */
    "default": string;

    /**
     * 是否必填
     */
    "required": boolean;

    /**
     * 下拉选项（type="select" 时使用）
     */
    "options": SelectOption[];

    /** Creates a new TableRuleParamDef instance. */
    constructor($$source: Partial<TableRuleParamDef> = {}) {
        if (!("key" in $$source)) {
            this["key"] = ERuleParam.$zero;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("default" in $$source)) {
            this["default"] = "";
        }
        if (!("required" in $$source)) {
            this["required"] = false;
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableRuleParamDef instance from a string or object.
     */
    static createFrom($$source: any = {}): TableRuleParamDef {
        const $$createField6_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField6_0($$parsedSource["options"]);
        }
        return new TableRuleParamDef($$parsedSource as Partial<TableRuleParamDef>);
    }
}

// Private type creation functions
const $$createType0 = CellError.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = GiantLabel.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = ColRule.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = ManagerList.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = SheetColRule.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $Create.Map($Create.Any, $$createType13);
const $$createType15 = TableRule.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $Create.Array($Create.Any);
const $$createType19 = TableRuleParamDef.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = SelectOption.createFrom;
const $$createType22 = $Create.Array($$createType21);
