// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class HeroSkinItemDiff {
    "SkinItemId": number;
    "HeroId": string;
    "None1": string;
    "RailyType": string;
    "SkinType": string;
    "Name": string;
    "GetWay": string;
    "SkinPinYin": string;
    "SeatSpecialImg": string;
    "HeroUIExtraIcons": string[];
    "Lines": number[];
    "DebutLines": number[];
    "KillLines": number[];
    "DeadLines": number[];
    "HeroAudio": number[];
    "LinesDubbed": string;
    "OriginalArtDesigner": string;
    "CollitionType": string;
    "IsOpen": boolean;
    "OpenDate": string;
    "CollitionTagImg": string;
    "KillShowTime": number;
    "BodyOffset": number[];
    "HasOutFrameIcon": boolean;

    /** Creates a new HeroSkinItemDiff instance. */
    constructor($$source: Partial<HeroSkinItemDiff> = {}) {
        if (!("SkinItemId" in $$source)) {
            this["SkinItemId"] = 0;
        }
        if (!("HeroId" in $$source)) {
            this["HeroId"] = "";
        }
        if (!("None1" in $$source)) {
            this["None1"] = "";
        }
        if (!("RailyType" in $$source)) {
            this["RailyType"] = "";
        }
        if (!("SkinType" in $$source)) {
            this["SkinType"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("GetWay" in $$source)) {
            this["GetWay"] = "";
        }
        if (!("SkinPinYin" in $$source)) {
            this["SkinPinYin"] = "";
        }
        if (!("SeatSpecialImg" in $$source)) {
            this["SeatSpecialImg"] = "";
        }
        if (!("HeroUIExtraIcons" in $$source)) {
            this["HeroUIExtraIcons"] = [];
        }
        if (!("Lines" in $$source)) {
            this["Lines"] = [];
        }
        if (!("DebutLines" in $$source)) {
            this["DebutLines"] = [];
        }
        if (!("KillLines" in $$source)) {
            this["KillLines"] = [];
        }
        if (!("DeadLines" in $$source)) {
            this["DeadLines"] = [];
        }
        if (!("HeroAudio" in $$source)) {
            this["HeroAudio"] = [];
        }
        if (!("LinesDubbed" in $$source)) {
            this["LinesDubbed"] = "";
        }
        if (!("OriginalArtDesigner" in $$source)) {
            this["OriginalArtDesigner"] = "";
        }
        if (!("CollitionType" in $$source)) {
            this["CollitionType"] = "";
        }
        if (!("IsOpen" in $$source)) {
            this["IsOpen"] = false;
        }
        if (!("OpenDate" in $$source)) {
            this["OpenDate"] = "";
        }
        if (!("CollitionTagImg" in $$source)) {
            this["CollitionTagImg"] = "";
        }
        if (!("KillShowTime" in $$source)) {
            this["KillShowTime"] = 0;
        }
        if (!("BodyOffset" in $$source)) {
            this["BodyOffset"] = [];
        }
        if (!("HasOutFrameIcon" in $$source)) {
            this["HasOutFrameIcon"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroSkinItemDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroSkinItemDiff {
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType1;
        const $$createField11_0 = $$createType1;
        const $$createField12_0 = $$createType1;
        const $$createField13_0 = $$createType1;
        const $$createField14_0 = $$createType1;
        const $$createField22_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("HeroUIExtraIcons" in $$parsedSource) {
            $$parsedSource["HeroUIExtraIcons"] = $$createField9_0($$parsedSource["HeroUIExtraIcons"]);
        }
        if ("Lines" in $$parsedSource) {
            $$parsedSource["Lines"] = $$createField10_0($$parsedSource["Lines"]);
        }
        if ("DebutLines" in $$parsedSource) {
            $$parsedSource["DebutLines"] = $$createField11_0($$parsedSource["DebutLines"]);
        }
        if ("KillLines" in $$parsedSource) {
            $$parsedSource["KillLines"] = $$createField12_0($$parsedSource["KillLines"]);
        }
        if ("DeadLines" in $$parsedSource) {
            $$parsedSource["DeadLines"] = $$createField13_0($$parsedSource["DeadLines"]);
        }
        if ("HeroAudio" in $$parsedSource) {
            $$parsedSource["HeroAudio"] = $$createField14_0($$parsedSource["HeroAudio"]);
        }
        if ("BodyOffset" in $$parsedSource) {
            $$parsedSource["BodyOffset"] = $$createField22_0($$parsedSource["BodyOffset"]);
        }
        return new HeroSkinItemDiff($$parsedSource as Partial<HeroSkinItemDiff>);
    }
}

export class SkinLineVoice {
    "Lines": number[];
    "DebutLines": number[];
    "KillLines": number[];
    "DeadLines": number[];
    "HeroAudio": number[];

    /** Creates a new SkinLineVoice instance. */
    constructor($$source: Partial<SkinLineVoice> = {}) {
        if (!("Lines" in $$source)) {
            this["Lines"] = [];
        }
        if (!("DebutLines" in $$source)) {
            this["DebutLines"] = [];
        }
        if (!("KillLines" in $$source)) {
            this["KillLines"] = [];
        }
        if (!("DeadLines" in $$source)) {
            this["DeadLines"] = [];
        }
        if (!("HeroAudio" in $$source)) {
            this["HeroAudio"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkinLineVoice instance from a string or object.
     */
    static createFrom($$source: any = {}): SkinLineVoice {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Lines" in $$parsedSource) {
            $$parsedSource["Lines"] = $$createField0_0($$parsedSource["Lines"]);
        }
        if ("DebutLines" in $$parsedSource) {
            $$parsedSource["DebutLines"] = $$createField1_0($$parsedSource["DebutLines"]);
        }
        if ("KillLines" in $$parsedSource) {
            $$parsedSource["KillLines"] = $$createField2_0($$parsedSource["KillLines"]);
        }
        if ("DeadLines" in $$parsedSource) {
            $$parsedSource["DeadLines"] = $$createField3_0($$parsedSource["DeadLines"]);
        }
        if ("HeroAudio" in $$parsedSource) {
            $$parsedSource["HeroAudio"] = $$createField4_0($$parsedSource["HeroAudio"]);
        }
        return new SkinLineVoice($$parsedSource as Partial<SkinLineVoice>);
    }
}

export type SkinLineVoiceMap = { [_ in `${number}`]?: SkinLineVoice };

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
