// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as params$0 from "./params/models.js";

/**
 * FieldValues 字段4态值（对应前端 FieldFourState 接口）
 * 类型别名，定义在 params 包中
 */
export const FieldValues = params$0.FieldValues;

/**
 * FieldValues 字段4态值（对应前端 FieldFourState 接口）
 * 类型别名，定义在 params 包中
 */
export type FieldValues = params$0.FieldValues;

/**
 * ProtoCaseMeta 测试用例元信息
 */
export class ProtoCaseMeta {
    "name": string;
    "message_count": number;
    "server_addr": string;
    "created_at": string;

    /** Creates a new ProtoCaseMeta instance. */
    constructor($$source: Partial<ProtoCaseMeta> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("message_count" in $$source)) {
            this["message_count"] = 0;
        }
        if (!("server_addr" in $$source)) {
            this["server_addr"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProtoCaseMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): ProtoCaseMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProtoCaseMeta($$parsedSource as Partial<ProtoCaseMeta>);
    }
}

/**
 * ProtoTestConfig proto-test 监听配置
 * @frontend @mcp
 */
export class ProtoTestConfig {
    /**
     * TCPListenPort 本地 TCP 监听端口（代理游戏客户端 TCP 连接）
     */
    "tcp_listen_port": number;

    /**
     * HTTPListenPort 本地 HTTP 监听端口（代理游戏客户端 HTTP 请求）
     */
    "http_listen_port": number;

    /**
     * TargetServerAddr 目标 TCP 服务器地址（如 10.254.114.204:18000）
     */
    "target_server_addr": string;

    /**
     * TargetHTTPAddr 目标 HTTP 服务器地址（如 10.254.114.204:20144）
     */
    "target_http_addr": string;

    /** Creates a new ProtoTestConfig instance. */
    constructor($$source: Partial<ProtoTestConfig> = {}) {
        if (!("tcp_listen_port" in $$source)) {
            this["tcp_listen_port"] = 0;
        }
        if (!("http_listen_port" in $$source)) {
            this["http_listen_port"] = 0;
        }
        if (!("target_server_addr" in $$source)) {
            this["target_server_addr"] = "";
        }
        if (!("target_http_addr" in $$source)) {
            this["target_http_addr"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProtoTestConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProtoTestConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProtoTestConfig($$parsedSource as Partial<ProtoTestConfig>);
    }
}

/**
 * RecordEntryView 录制条目视图（Payload 直接为 map[string]any，前端无需 JSON.parse） 修改时需要同步proto_cases/目录下记载的schema
 */
export class RecordEntryView {
    "index": number;
    "offset_ms": number;
    "msg_id": number;
    "msg_name": string;
    "seq_id": number;
    "payload": { [_ in string]?: any };
    "direction": string;

    /**
     * 重放时的账号标识（如 test1、test2），录制时为空
     */
    "account_id": string;

    /**
     * 消息描述信息（用户可编辑）
     */
    "descript": string;

    /**
     * 字段路径→4态值映射
     */
    "field_values"?: { [_ in string]?: FieldValues };

    /** Creates a new RecordEntryView instance. */
    constructor($$source: Partial<RecordEntryView> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("offset_ms" in $$source)) {
            this["offset_ms"] = 0;
        }
        if (!("msg_id" in $$source)) {
            this["msg_id"] = 0;
        }
        if (!("msg_name" in $$source)) {
            this["msg_name"] = "";
        }
        if (!("seq_id" in $$source)) {
            this["seq_id"] = 0;
        }
        if (!("payload" in $$source)) {
            this["payload"] = {};
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }
        if (!("account_id" in $$source)) {
            this["account_id"] = "";
        }
        if (!("descript" in $$source)) {
            this["descript"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordEntryView instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordEntryView {
        const $$createField5_0 = $$createType0;
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("payload" in $$parsedSource) {
            $$parsedSource["payload"] = $$createField5_0($$parsedSource["payload"]);
        }
        if ("field_values" in $$parsedSource) {
            $$parsedSource["field_values"] = $$createField9_0($$parsedSource["field_values"]);
        }
        return new RecordEntryView($$parsedSource as Partial<RecordEntryView>);
    }
}

/**
 * RecordFileData 录制文件数据（传给前端） 修改结构时需要更新version
 */
export class RecordFileData {
    "version": number;
    "recorded_at": string;
    "server_addr": string;
    "message_count": number;
    "messages": RecordEntryView[];

    /** Creates a new RecordFileData instance. */
    constructor($$source: Partial<RecordFileData> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("recorded_at" in $$source)) {
            this["recorded_at"] = "";
        }
        if (!("server_addr" in $$source)) {
            this["server_addr"] = "";
        }
        if (!("message_count" in $$source)) {
            this["message_count"] = 0;
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordFileData instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordFileData {
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField4_0($$parsedSource["messages"]);
        }
        return new RecordFileData($$parsedSource as Partial<RecordFileData>);
    }
}

/**
 * RecordProgress 录制进度（返回给前端）
 */
export class RecordProgress {
    /**
     * "idle" | "running" | "stopped" | "error"
     */
    "status": string;

    /**
     * 已录制消息数
     */
    "message_count": number;

    /**
     * 目标服务器地址
     */
    "server_addr": string;

    /**
     * 错误信息
     */
    "error_message": string;

    /** Creates a new RecordProgress instance. */
    constructor($$source: Partial<RecordProgress> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("message_count" in $$source)) {
            this["message_count"] = 0;
        }
        if (!("server_addr" in $$source)) {
            this["server_addr"] = "";
        }
        if (!("error_message" in $$source)) {
            this["error_message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecordProgress($$parsedSource as Partial<RecordProgress>);
    }
}

/**
 * ReplayProgress 重放进度（返回给前端）
 */
export class ReplayProgress {
    /**
     * "idle" | "running" | "completed" | "error" | "cancelled"
     */
    "status": string;

    /**
     * 总消息数
     */
    "total": number;

    /**
     * 已发送数
     */
    "sent": number;

    /**
     * 当前发送的消息名
     */
    "current_msg": string;

    /**
     * 错误信息（仅 error 状态）
     */
    "error_message": string;

    /** Creates a new ReplayProgress instance. */
    constructor($$source: Partial<ReplayProgress> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("sent" in $$source)) {
            this["sent"] = 0;
        }
        if (!("current_msg" in $$source)) {
            this["current_msg"] = "";
        }
        if (!("error_message" in $$source)) {
            this["error_message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplayProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): ReplayProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReplayProgress($$parsedSource as Partial<ReplayProgress>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = params$0.FieldValues.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = RecordEntryView.createFrom;
const $$createType4 = $Create.Array($$createType3);
