// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProtoTestConfigService proto-test 配置管理服务
 * @frontend @mcp
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig 获取当前配置
 * @frontend @mcp
 */
export function GetConfig(): $CancellablePromise<$models.ProtoTestConfig | null> {
    return $Call.ByID(305555481).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveConfig 保存配置
 * @frontend @mcp
 */
export function SaveConfig(config: $models.ProtoTestConfig | null): $CancellablePromise<void> {
    return $Call.ByID(3985318730, config);
}

/**
 * UpdateConfig 部分更新配置
 * @frontend @mcp
 */
export function UpdateConfig(updates: { [_ in string]?: any }): $CancellablePromise<$models.ProtoTestConfig | null> {
    return $Call.ByID(2477323046, updates).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProtoTestConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
