// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RecordFileService 录制文件加载/保存/Payload 编辑服务
 * 对应前端 packet-tab.vue, testcase-tab.vue, replay-result-tab.vue 的文件操作
 * 
 * 时序图（加载文件）：
 * ┌──────────────────┐  LoadRecordFile   ┌───────────────────┐
 * │ packet-tab.vue   │ ────────────────> │ RecordFileService │
 * │ testcase-tab.vue │                   │   (后端)          │
 * └──────────────────┘                   └───────────────────┘
 * 
 * 	     │                                        │
 * 	     │                                        │ LoadRecordingFromFile()
 * 	     │                                        ▼
 * 	     │                                  ┌──────────┐
 * 	     │                                  │streamproto│
 * 	     │                                  │  解析JSON │
 * 	     │                                  │recordingToViews()
 * 	     │                                  └──────────┘
 * 	     │                                        │
 * 	     │        返回 RecordFileData             │
 * 	     │ <──────────────────────────────────────┘
 * 	     │                                        │
 * 	     ▼                                        ▼
 * 	设置到组件状态                      解析录制文件
 * 
 * 时序图（Payload 编辑）：
 * ┌──────────────────────┐  UpdateMessagePayload  ┌───────────────────┐
 * │ paired-payload-editor│ ──────────────────────> │ RecordFileService │
 * └──────────────────────┘                        │   (后端)          │
 * 
 * 	     │                                            └───────────────────┘
 * 	     │                                                  │
 * 	     │                                                  │ 加载录制文件
 * 	     │                                                  │ 更新 PayloadJSON
 * 	     │                                                  │ 保存回文件
 * 	     │                                                  │
 * 	     │            保存成功                                │
 * 	     │ <─────────────────────────────────────────────────┘
 * 	     │
 * 	     ▼
 * 	刷新表格数据
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as params$0 from "./params/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * LoadRecordFile 加载录制文件，返回消息列表
 */
export function LoadRecordFile(path: string): $CancellablePromise<$models.RecordFileData | null> {
    return $Call.ByID(1616675101, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveRecordFile 将修改后的录制数据保存到文件
 */
export function SaveRecordFile(path: string, data: $models.RecordFileData | null): $CancellablePromise<void> {
    return $Call.ByID(1069211220, path, data);
}

/**
 * UpdateMessageDescript 更新指定 index 消息的描述信息
 */
export function UpdateMessageDescript(path: string, index: number, descript: string): $CancellablePromise<$models.RecordFileData | null> {
    return $Call.ByID(3917254798, path, index, descript).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateMessageFieldValues 更新指定 index 消息的字段4态值
 */
export function UpdateMessageFieldValues(path: string, index: number, fieldValues: { [_ in string]?: $models.FieldValues }): $CancellablePromise<$models.RecordFileData | null> {
    return $Call.ByID(1181455888, path, index, fieldValues).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateMessagePayload 更新指定 index 消息的 payload（前端直接传 map[string]any 对象）
 */
export function UpdateMessagePayload(path: string, index: number, payload: { [_ in string]?: any }): $CancellablePromise<$models.RecordFileData | null> {
    return $Call.ByID(1540939652, path, index, payload).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.RecordFileData.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
