// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReplayControlService 重放控制服务（对应前端 packet-tab.vue 和 testcase-tab.vue 重放按钮）
 * 
 * 时序图：
 * ┌──────────────────┐  SendMessages    ┌─────────────────────┐
 * │ packet-tab.vue   │ ────────────────> │ ReplayControlService │
 * │ testcase-tab.vue │                  │   (后端)              │
 * └──────────────────┘                  └─────────────────────┘
 * 
 * 	     │                                        │
 * 	     │                                        │ StartSend()
 * 	     │                                        ▼
 * 	     │                                  ┌──────────┐
 * 	     │                                  │ReplayWorker│
 * 	     │                                  │  HTTP登录 │
 * 	     │                                  │  TCP连接  │
 * 	     │                                  │  发送LoginReq
 * 	     │                                  │  逐条发送Req
 * 	     │                                  └──────────┘
 * 	     │                                        │
 * 	     │    Event.Emit('replay:progress')        │
 * 	     │ <────────────────────────────────────────┘
 * 	     │                                        │
 * 	     ▼                                        ▼
 * 	更新进度标签                             执行重放逻辑
 * 
 * 	     │    Event.Emit('record:progress', latest_msg)
 * 	     │ <────────────────────────────────────────┘
 * 	     │
 * 	     ▼
 * 	表格追加重放消息
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as protocol$0 from "./msg/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as params$0 from "./params/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseAllConnections 关闭所有连接
 */
export function CloseAllConnections(): $CancellablePromise<void> {
    return $Call.ByID(342572331);
}

/**
 * CloseConnection 关闭指定账号的连接
 */
export function CloseConnection(accountID: string): $CancellablePromise<void> {
    return $Call.ByID(24599467, accountID);
}

/**
 * GetAvailableVariables 返回注册表中所有可用变量列表（供前端变量选择器使用）（E1/E2）
 */
export function GetAvailableVariables(): $CancellablePromise<params$0.VariableInfo[]> {
    return $Call.ByID(180977691).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetConnectionPoolStatus 获取连接池状态
 */
export function GetConnectionPoolStatus(): $CancellablePromise<protocol$0.ConnPoolEntry[]> {
    return $Call.ByID(2914858327).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetReplaySettings 获取当前重放参数设置（供前端设置面板初始化）
 */
export function GetReplaySettings(): $CancellablePromise<{ [_ in string]?: number }> {
    return $Call.ByID(1770192037).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetReplayStatus 获取当前重放状态
 */
export function GetReplayStatus(): $CancellablePromise<$models.ReplayProgress | null> {
    return $Call.ByID(1421544282).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * SendIterativeMessages 迭代发送消息
 * 前端传入一条基础消息的 payload + 字段迭代配置（FieldValues），
 * 后端根据配置生成多条消息后一次性批量发送。
 * 
 * 流程：
 *  1. 解析 payloadJSON 为 map[string]any
 *  2. 将 FieldValues 转为内部 IterationConfig
 *  3. 调用 params.GenerateIterativeMessages 生成分组独立迭代消息
 *  4. 每条消息序列化回 JSON，组装为 []RecordMessage
 *  5. 批量序列化 → worker.StartSend()（复用进度推送 + 取消机制）
 * 
 * @frontend
 */
export function SendIterativeMessages(serverAddr: string, httpAddr: string, openID: string, msgID: number, msgName: string, payloadJSON: string, direction: string, fieldValues: { [_ in string]?: $models.FieldValues }): $CancellablePromise<void> {
    return $Call.ByID(1977989618, serverAddr, httpAddr, openID, msgID, msgName, payloadJSON, direction, fieldValues);
}

/**
 * SendMessages 启动异步消息发送（前端"开始重放"/"执行用例"/"重发"共用）
 * 检测目标账号是否与录制代理中的活跃连接冲突：
 *   - 不冲突 → 走连接池路径
 *   - 冲突 → 走代理注入路径（使用 proxySeqId，不新建连接）
 * 
 * 特殊限制：有变量依赖的消息不支持注入路径（因为注入路径没有 FrameMux 能力）
 */
export function SendMessages(serverAddr: string, httpAddr: string, openID: string, messagesJSON: string, repeatCount: number, rangeStart: number, rangeEnd: number): $CancellablePromise<void> {
    return $Call.ByID(1024805679, serverAddr, httpAddr, openID, messagesJSON, repeatCount, rangeStart, rangeEnd);
}

/**
 * SendMessagesWithFieldValues 统一发送消息（支持迭代/变量配置）
 * 接受包含 field_values 的消息列表，内部展开迭代配置后统一一次 StartSend 发送
 * 变量字段的 FieldValues 元数据会附带在 RecordMessage 中传递到 replay 层
 * 
 * @frontend
 */
export function SendMessagesWithFieldValues(serverAddr: string, httpAddr: string, openID: string, entries: $models.RecordEntryView[], repeatCount: number, rangeStart: number, rangeEnd: number): $CancellablePromise<void> {
    return $Call.ByID(4056679871, serverAddr, httpAddr, openID, entries, repeatCount, rangeStart, rangeEnd);
}

/**
 * SetReplaySettings 设置重放参数（供前端设置面板修改）
 */
export function SetReplaySettings(sendIntervalMs: number, ackWaitMs: number, maxConcurrency: number): $CancellablePromise<void> {
    return $Call.ByID(2204127833, sendIntervalMs, ackWaitMs, maxConcurrency);
}

/**
 * StartReplay 启动异步协议重放（从录制文件重放）
 */
export function StartReplay(filePath: string, serverAddr: string, httpAddr: string, openID: string, repeatCount: number): $CancellablePromise<void> {
    return $Call.ByID(4088641792, filePath, serverAddr, httpAddr, openID, repeatCount);
}

/**
 * StopReplay 停止正在进行的协议重放
 */
export function StopReplay(): $CancellablePromise<void> {
    return $Call.ByID(1312355530);
}

// Private type creation functions
const $$createType0 = params$0.VariableInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = protocol$0.ConnPoolEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $models.ReplayProgress.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
