// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActivityWikiCheckService 活动Wiki检查服务
 * @frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as diff$0 from "../rain-resources-checker/diff/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Check 检查活动Wiki数据
 * excelDir: Excel配置目录路径
 * @frontend @mcp
 */
export function Check(excelDir: string): $CancellablePromise<diff$0.DataContainer | null> {
    return $Call.ByID(2525283700, excelDir).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CheckResourcePaths 批量检查资源文件是否存在，返回检查结果
 * paths: 资源路径列表（如 "Assets/Art/Icons/xxx.png"）
 * clientPath: 客户端项目根目录路径（如 "D:/work/client/Master/Card"）
 * @frontend
 */
export function CheckResourcePaths(paths: string[], clientPath: string): $CancellablePromise<($models.ResourceCheckResult | null)[]> {
    return $Call.ByID(3671449988, paths, clientPath).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetRuleCoverage 获取指定目录下所有Sheet的规则覆盖统计
 * 用于前端角标显示，统计每个Sheet启用了多少表级规则和列级规则
 * caseDir: cases/excel_cases 目录路径
 * @frontend
 */
export function GetRuleCoverage(caseDir: string): $CancellablePromise<$models.RuleCoverageData | null> {
    return $Call.ByID(174275404, caseDir).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetRuleCoverageWithErrors 获取规则覆盖统计并合并校验错误计数
 * 先获取基础覆盖数据，再执行 Excel 规则检查，将错误数按 sheet+field 粒度合并
 * caseDir: cases/excel_cases 目录路径
 * excelDir: Excel 配置目录路径
 * @frontend
 */
export function GetRuleCoverageWithErrors(caseDir: string, excelDir: string): $CancellablePromise<$models.RuleCoverageData | null> {
    return $Call.ByID(4124031027, caseDir, excelDir).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * OpenExcel 打开指定Sheet对应的Excel文件
 * sheetName: Sheet名称（如"活动表|Activity"），为空时直接打开 excelDir 作为文件路径
 * excelDir: Excel配置目录路径，或当 sheetName 为空时为文件完整路径
 * @frontend
 */
export function OpenExcel(sheetName: string, excelDir: string): $CancellablePromise<void> {
    return $Call.ByID(1443131463, sheetName, excelDir);
}

// Private type creation functions
const $$createType0 = diff$0.DataContainer.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ResourceCheckResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.RuleCoverageData.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
