// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ActivityWikiConfig 应用配置结构
 */
export class ActivityWikiConfig {
    "excel_dir": string;
    "client_path": string;

    /** Creates a new ActivityWikiConfig instance. */
    constructor($$source: Partial<ActivityWikiConfig> = {}) {
        if (!("excel_dir" in $$source)) {
            this["excel_dir"] = "";
        }
        if (!("client_path" in $$source)) {
            this["client_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActivityWikiConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ActivityWikiConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActivityWikiConfig($$parsedSource as Partial<ActivityWikiConfig>);
    }
}

/**
 * FieldRuleStat 字段级规则统计
 */
export class FieldRuleStat {
    /**
     * 列级规则数量（仅Enabled）
     */
    "colRuleCount": number;

    /**
     * 行级规则数量（预留，当前为0）
     */
    "rowRuleCount": number;

    /**
     * = ColRuleCount + RowRuleCount
     */
    "totalCount": number;

    /**
     * 校验错误数量（执行检查后填充）
     */
    "errorCount": number;

    /**
     * 规则名称列表
     */
    "ruleNames": RuleNameInfo[];

    /** Creates a new FieldRuleStat instance. */
    constructor($$source: Partial<FieldRuleStat> = {}) {
        if (!("colRuleCount" in $$source)) {
            this["colRuleCount"] = 0;
        }
        if (!("rowRuleCount" in $$source)) {
            this["rowRuleCount"] = 0;
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }
        if (!("errorCount" in $$source)) {
            this["errorCount"] = 0;
        }
        if (!("ruleNames" in $$source)) {
            this["ruleNames"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FieldRuleStat instance from a string or object.
     */
    static createFrom($$source: any = {}): FieldRuleStat {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ruleNames" in $$parsedSource) {
            $$parsedSource["ruleNames"] = $$createField4_0($$parsedSource["ruleNames"]);
        }
        return new FieldRuleStat($$parsedSource as Partial<FieldRuleStat>);
    }
}

/**
 * ResourceCheckResult 单个资源路径的检查结果
 */
export class ResourceCheckResult {
    /**
     * 原始路径
     */
    "path": string;

    /**
     * 文件是否存在
     */
    "exists": boolean;

    /**
     * base64 data URL（仅图片文件存在时）
     */
    "previewUrl": string;

    /** Creates a new ResourceCheckResult instance. */
    constructor($$source: Partial<ResourceCheckResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("previewUrl" in $$source)) {
            this["previewUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceCheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceCheckResult($$parsedSource as Partial<ResourceCheckResult>);
    }
}

/**
 * RuleCoverageData 规则覆盖数据
 */
export class RuleCoverageData {
    /**
     * key=Sheet名
     */
    "sheets": { [_ in string]?: SheetRuleStats | null };

    /** Creates a new RuleCoverageData instance. */
    constructor($$source: Partial<RuleCoverageData> = {}) {
        if (!("sheets" in $$source)) {
            this["sheets"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuleCoverageData instance from a string or object.
     */
    static createFrom($$source: any = {}): RuleCoverageData {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sheets" in $$parsedSource) {
            $$parsedSource["sheets"] = $$createField0_0($$parsedSource["sheets"]);
        }
        return new RuleCoverageData($$parsedSource as Partial<RuleCoverageData>);
    }
}

/**
 * RuleNameInfo 规则名称信息（用于前端Popover展示）
 */
export class RuleNameInfo {
    /**
     * 规则类型标识（如 DRAWSKIN_DATA_VALIDITY_CHECK）
     */
    "type": string;

    /**
     * 规则显示名称
     */
    "displayName": string;

    /** Creates a new RuleNameInfo instance. */
    constructor($$source: Partial<RuleNameInfo> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuleNameInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RuleNameInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuleNameInfo($$parsedSource as Partial<RuleNameInfo>);
    }
}

/**
 * SheetRuleStats 单个Sheet的规则统计
 */
export class SheetRuleStats {
    "sheetName": string;

    /**
     * 表级规则数（仅Enabled）
     */
    "tableRuleCount": number;

    /**
     * 表级规则名称列表
     */
    "tableRuleNames": RuleNameInfo[];

    /**
     * 表级规则校验错误数
     */
    "tableErrorCount": number;

    /**
     * key=字段名
     */
    "fieldRuleStats": { [_ in string]?: FieldRuleStat | null };

    /** Creates a new SheetRuleStats instance. */
    constructor($$source: Partial<SheetRuleStats> = {}) {
        if (!("sheetName" in $$source)) {
            this["sheetName"] = "";
        }
        if (!("tableRuleCount" in $$source)) {
            this["tableRuleCount"] = 0;
        }
        if (!("tableRuleNames" in $$source)) {
            this["tableRuleNames"] = [];
        }
        if (!("tableErrorCount" in $$source)) {
            this["tableErrorCount"] = 0;
        }
        if (!("fieldRuleStats" in $$source)) {
            this["fieldRuleStats"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SheetRuleStats instance from a string or object.
     */
    static createFrom($$source: any = {}): SheetRuleStats {
        const $$createField2_0 = $$createType1;
        const $$createField4_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tableRuleNames" in $$parsedSource) {
            $$parsedSource["tableRuleNames"] = $$createField2_0($$parsedSource["tableRuleNames"]);
        }
        if ("fieldRuleStats" in $$parsedSource) {
            $$parsedSource["fieldRuleStats"] = $$createField4_0($$parsedSource["fieldRuleStats"]);
        }
        return new SheetRuleStats($$parsedSource as Partial<SheetRuleStats>);
    }
}

// Private type creation functions
const $$createType0 = RuleNameInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = SheetRuleStats.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = FieldRuleStat.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Map($Create.Any, $$createType6);
