// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ServerLogService from "./serverlogservice.js";
export {
    ServerLogService
};
