// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServerLogService 服务端日志 Wails 服务
 * 自动捕获 Go 后端 stdout/stderr 输出，// 并提供手动日志 API 供代码中标记重要事件
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * Debug 记录调试级别日志（手动标记）
 * 手动日志在终端显示时会带 ▸ 前缀
 * @frontend
 */
export function Debug(msg: string): $CancellablePromise<void> {
    return $Call.ByID(3192251889, msg);
}

/**
 * Error 记录错误级别日志（手动标记）
 * @frontend
 */
export function Error(msg: string): $CancellablePromise<void> {
    return $Call.ByID(3673864096, msg);
}

/**
 * GetLogStats 获取日志统计信息
 * 返回当前待发送的日志数量
 * @frontend
 */
export function GetLogStats(): $CancellablePromise<{ [_ in string]?: number }> {
    return $Call.ByID(3052184027).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Info 记录信息级别日志（手动标记）
 * @frontend
 */
export function Info(msg: string): $CancellablePromise<void> {
    return $Call.ByID(1048109350, msg);
}

/**
 * InitWithApp 初始化服务（在 main.go 中 app 创建后调用）
 * 
 * ⚠️ 关键知识点：Go log 包引用捕获问题
 * 
 * Go 的 log 包在 init 阶段就将 os.Stderr 存到内部字段 Logger.out 中。
 * 之后替换 os.Stderr 变量只是改了 Go 全局变量，不会影响已保存的引用。
 * 所以必须同时做三件事：
 *  1. 替换 os.Stdout / os.Stderr 变量（影响 fmt.Printf 等直接引用变量的代码）
 *  2. 调用 log.SetOutput() 重定向 log 包（影响所有 log.Printf 调用）
 *  3. 后续新增日志输出建议统一使用 log.Printf 而非 fmt.Printf
 */
export function InitWithApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(369883383, app);
}

/**
 * Shutdown 关闭服务
 * 在应用退出时调用
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(3598079592);
}

/**
 * Warn 记录警告级别日志（手动标记）
 * @frontend
 */
export function Warn(msg: string): $CancellablePromise<void> {
    return $Call.ByID(2980613638, msg);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
