// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GameExcelService 游戏Excel配置服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as excel$0 from "../../../../../rain-robot/project/xcard/xcard_excel/excel/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as excel_config$0 from "../../../../../rain-robot/project/xcard/xcard_excel/excel_config/models.js";

/**
 * GetAllCardCfg 获取所有卡牌配置
 * @frontend @mcp
 */
export function GetAllCardCfg(): $CancellablePromise<{ [_ in `${number}`]?: excel$0.CardsTemplate | null }> {
    return $Call.ByID(465929704).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetAllHeroCfg 获取所有英雄配置
 * @frontend @mcp
 */
export function GetAllHeroCfg(): $CancellablePromise<{ [_ in excel$0.EHeroId]?: excel_config$0.HeroConfig | null }> {
    return $Call.ByID(481490866).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetAllSkillCfg 获取所有技能配置
 * @frontend @mcp
 */
export function GetAllSkillCfg(): $CancellablePromise<{ [_ in excel$0.ESkillId]?: excel$0.SkillsTemplate | null }> {
    return $Call.ByID(3092464629).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetEGameMsgIdNameMap 获取游戏消息ID名称映射
 * @mcp
 */
export function GetEGameMsgIdNameMap(): $CancellablePromise<{ [_ in `${number}`]?: string }> {
    return $Call.ByID(3915558869).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetErrorCodeMap 获取错误代码映射
 * @frontend @mcp
 */
export function GetErrorCodeMap(): $CancellablePromise<{ [_ in `${number}`]?: string }> {
    return $Call.ByID(2121286950).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetOptActionTypeMap 获取操作动作类型映射
 * @frontend
 */
export function GetOptActionTypeMap(): $CancellablePromise<{ [_ in `${number}`]?: string }> {
    return $Call.ByID(838402126).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetPropertyTypeMap 获取属性类型映射
 * @frontend @mcp
 */
export function GetPropertyTypeMap(): $CancellablePromise<{ [_ in `${number}`]?: string }> {
    return $Call.ByID(1096486510).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * InitExcel 使用指定路径初始化 Excel 数据
 * 首次调用使用 Init（同步），后续调用使用 Reload（异步）
 * Reload 使用 rain-robot 硬编码的 resPath，不支持自定义路径
 */
export function InitExcel(path: string): $CancellablePromise<void> {
    return $Call.ByID(627362584, path);
}

/**
 * IsInitialized 直接检查底层数据是否已加载（不依赖实例级标记）
 * 这样所有 GameExcelService 实例都能正确感知初始化状态
 */
export function IsInitialized(): $CancellablePromise<boolean> {
    return $Call.ByID(2576018203);
}

// Private type creation functions
const $$createType0 = excel$0.CardsTemplate.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = excel_config$0.HeroConfig.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Map($Create.Any, $$createType4);
const $$createType6 = excel$0.SkillsTemplate.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Map($Create.Any, $$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
