// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ExcelDirProvider 提供统一策划配表目录路径。
 * 用接口而非直接依赖 settings 包，避免 game ↔ settings 循环依赖。
 * 由 cmd/rain-qa-func/wails.go 在注册服务时注入 settings.ExcelConfigService。
 */
export type ExcelDirProvider = any;
