// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkillUIDescService 技能表现配置表（技能表现配置表|SkillUI）解析服务。
 * 独立于 GameExcelService：GameExcelService 读取 rain-robot 编译后的 .bytes 资源，
 * 本服务读取策划配表目录下的 .xlsx 文件，用于提供 SkillsTemplate 中缺失的技能描述文案。
 * 
 * 路径来源：统一策划配表目录配置（ExcelDirProvider 注入），
 * 与 hero-wiki-check / activity-wiki-check 等模块共用同一份配置，避免前端传参导致的路径不一致。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSkillUIDescMap 获取已加载的技能描述映射（调用前需先调用 LoadSkillUIDesc）
 * @frontend @mcp
 */
export function GetSkillUIDescMap(): $CancellablePromise<{ [_ in `${number}`]?: string }> {
    return $Call.ByID(2910913276).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * IsInitialized 是否已加载
 */
export function IsInitialized(): $CancellablePromise<boolean> {
    return $Call.ByID(3966223990);
}

/**
 * LoadSkillUIDesc 从统一策划配表目录解析「技能表现配置表|SkillUI」xlsx，
 * 构建 skillId -> SkillText 映射并缓存。无参，路径由后端统一配置决定。
 * @frontend @mcp
 */
export function LoadSkillUIDesc(): $CancellablePromise<{ [_ in `${number}`]?: string }> {
    return $Call.ByID(2203924994).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetExcelDirProvider 注入统一策划配表目录提供者（需在注册服务前调用）
 */
export function SetExcelDirProvider(p: $models.ExcelDirProvider): $CancellablePromise<void> {
    return $Call.ByID(3481559263, p);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
