// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FieldValues 字段4态值（对应前端 FieldFourState 接口）
 * 每个字段路径对应一组完整的输入状态：原始值、范围、枚举、组合
 */
export class FieldValues {
    "range_value": RangeValue;
    "enum_value": any[];
    "combo_value": any[];

    /**
     * "original" | "range" | "enum" | "combo" | "variable"
     */
    "input_type": string;

    /**
     * 变量短名（仅 variable 类型），如 "cityId"
     */
    "variable_name"?: string;

    /** Creates a new FieldValues instance. */
    constructor($$source: Partial<FieldValues> = {}) {
        if (!("range_value" in $$source)) {
            this["range_value"] = (new RangeValue());
        }
        if (!("enum_value" in $$source)) {
            this["enum_value"] = [];
        }
        if (!("combo_value" in $$source)) {
            this["combo_value"] = [];
        }
        if (!("input_type" in $$source)) {
            this["input_type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FieldValues instance from a string or object.
     */
    static createFrom($$source: any = {}): FieldValues {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range_value" in $$parsedSource) {
            $$parsedSource["range_value"] = $$createField0_0($$parsedSource["range_value"]);
        }
        if ("enum_value" in $$parsedSource) {
            $$parsedSource["enum_value"] = $$createField1_0($$parsedSource["enum_value"]);
        }
        if ("combo_value" in $$parsedSource) {
            $$parsedSource["combo_value"] = $$createField2_0($$parsedSource["combo_value"]);
        }
        return new FieldValues($$parsedSource as Partial<FieldValues>);
    }
}

/**
 * RangeValue 范围输入值（对应前端 range-input 组件）
 */
export class RangeValue {
    "start": number;
    "step": number;
    "end": number;

    /** Creates a new RangeValue instance. */
    constructor($$source: Partial<RangeValue> = {}) {
        if (!("start" in $$source)) {
            this["start"] = 0;
        }
        if (!("step" in $$source)) {
            this["step"] = 0;
        }
        if (!("end" in $$source)) {
            this["end"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RangeValue instance from a string or object.
     */
    static createFrom($$source: any = {}): RangeValue {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RangeValue($$parsedSource as Partial<RangeValue>);
    }
}

/**
 * VariableInfo 前端用的变量信息（序列化为 JSON 传给前端）
 */
export class VariableInfo {
    "short_name": string;
    "display_name": string;

    /**
     * 对哪些 Req 可见（msg_name），nil/空=对所有 Req 可用
     */
    "available_reqs"?: string[];

    /** Creates a new VariableInfo instance. */
    constructor($$source: Partial<VariableInfo> = {}) {
        if (!("short_name" in $$source)) {
            this["short_name"] = "";
        }
        if (!("display_name" in $$source)) {
            this["display_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VariableInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): VariableInfo {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("available_reqs" in $$parsedSource) {
            $$parsedSource["available_reqs"] = $$createField2_0($$parsedSource["available_reqs"]);
        }
        return new VariableInfo($$parsedSource as Partial<VariableInfo>);
    }
}

// Private type creation functions
const $$createType0 = RangeValue.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Array($Create.Any);
