// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ArenaScoreRewardDiff {
    "Id": number;
    "Season": number;
    "Dan": number;
    "DanName": string;

    /**
     * 注意：这里需要根据ItemCfg的实际类型定义
     */
    "Reward": ItemCfg[];

    /** Creates a new ArenaScoreRewardDiff instance. */
    constructor($$source: Partial<ArenaScoreRewardDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("Season" in $$source)) {
            this["Season"] = 0;
        }
        if (!("Dan" in $$source)) {
            this["Dan"] = 0;
        }
        if (!("DanName" in $$source)) {
            this["DanName"] = "";
        }
        if (!("Reward" in $$source)) {
            this["Reward"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArenaScoreRewardDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): ArenaScoreRewardDiff {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Reward" in $$parsedSource) {
            $$parsedSource["Reward"] = $$createField4_0($$parsedSource["Reward"]);
        }
        return new ArenaScoreRewardDiff($$parsedSource as Partial<ArenaScoreRewardDiff>);
    }
}

/**
 * ItemCfg 类型定义 - 根据实际需求可能需要调整
 */
export class ItemCfg {

    /** Creates a new ItemCfg instance. */
    constructor($$source: Partial<ItemCfg> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemCfg instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemCfg {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ItemCfg($$parsedSource as Partial<ItemCfg>);
    }
}

// Private type creation functions
const $$createType0 = ItemCfg.createFrom;
const $$createType1 = $Create.Array($$createType0);
