// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ServerXlsxConfig Unity 服务器列表行配置
 * 字段顺序与服务器配置表.xlsx 第3行字段名保持一致
 * @frontend @mcp
 */
export class ServerXlsxConfig {
    "id": number;
    "server_name": string;
    "is_save": number;
    "ip_port": string;
    "ip_port_hero_point": string;
    "keep_alive": number;
    "server_zone_id": number;

    /**
     * 策划配表目录（其下包含 excel/ 子目录）
     */
    "excel_dir": string;

    /**
     * 抽屉面板配置的 HTTP 监听端口号
     */
    "http_listen_port": number;

    /** Creates a new ServerXlsxConfig instance. */
    constructor($$source: Partial<ServerXlsxConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("server_name" in $$source)) {
            this["server_name"] = "";
        }
        if (!("is_save" in $$source)) {
            this["is_save"] = 0;
        }
        if (!("ip_port" in $$source)) {
            this["ip_port"] = "";
        }
        if (!("ip_port_hero_point" in $$source)) {
            this["ip_port_hero_point"] = "";
        }
        if (!("keep_alive" in $$source)) {
            this["keep_alive"] = 0;
        }
        if (!("server_zone_id" in $$source)) {
            this["server_zone_id"] = 0;
        }
        if (!("excel_dir" in $$source)) {
            this["excel_dir"] = "";
        }
        if (!("http_listen_port" in $$source)) {
            this["http_listen_port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerXlsxConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerXlsxConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerXlsxConfig($$parsedSource as Partial<ServerXlsxConfig>);
    }
}
