// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServerConfigService 为 Server Config 前端页面提供扩展能力。
 * 当前主要封装 Unity 服务器列表注入与客户端配置导出。
 * @frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportClientConfig 在策划配表目录下执行客户端配置导出批处理 export_client.bat。
 * 当 excelDir 为空时，自动从统一策划配表目录配置读取。
 * @frontend @mcp
 */
export function ExportClientConfig(excelDir: string): $CancellablePromise<void> {
    return $Call.ByID(2731643314, excelDir);
}

/**
 * InjectUnityServer 向策划配表的服务器配置表.xlsx 中写入或更新 Unity 服务器条目。
 * 当 cfg.ExcelDir 为空时，自动从统一策划配表目录配置读取。
 * 当 cfg.IpPort 为空时，自动使用本机IP和 cfg.HTTPListenPort 构造。
 * @frontend @mcp
 */
export function InjectUnityServer(cfg: $models.ServerXlsxConfig): $CancellablePromise<void> {
    return $Call.ByID(2117397934, cfg);
}
