// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class HeroSkinCollectionDiff {
    /**
     * ESkinCollitionType
     */
    "Type": string;

    /**
     * 收藏册名称
     */
    "Name": string;

    /**
     * 名称图片
     */
    "NameImg": string;

    /**
     * 名称底图图片
     */
    "NameBg": string;

    /**
     * 诗词文案
     */
    "Desc": string;

    /**
     * 排序权重
     */
    "Weight": number;

    /**
     * 开放时间
     */
    "OpenDate": string;

    /** Creates a new HeroSkinCollectionDiff instance. */
    constructor($$source: Partial<HeroSkinCollectionDiff> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("NameImg" in $$source)) {
            this["NameImg"] = "";
        }
        if (!("NameBg" in $$source)) {
            this["NameBg"] = "";
        }
        if (!("Desc" in $$source)) {
            this["Desc"] = "";
        }
        if (!("Weight" in $$source)) {
            this["Weight"] = 0;
        }
        if (!("OpenDate" in $$source)) {
            this["OpenDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroSkinCollectionDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroSkinCollectionDiff {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HeroSkinCollectionDiff($$parsedSource as Partial<HeroSkinCollectionDiff>);
    }
}
