// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RoadmapService 路线图服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddComment 添加评论
 * @frontend
 */
export function AddComment(req: $models.CommentRequest): $CancellablePromise<$models.RoadmapItem | null> {
    return $Call.ByID(3294735046, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ExportToJSON 导出为JSON格式
 * @frontend
 */
export function ExportToJSON(): $CancellablePromise<string> {
    return $Call.ByID(1251463771);
}

/**
 * GetConfigFilePath 获取配置文件路径
 * @frontend
 */
export function GetConfigFilePath(): $CancellablePromise<string> {
    return $Call.ByID(2122754001);
}

/**
 * GetItem 获取单个路线图项目
 * @frontend
 */
export function GetItem(id: string): $CancellablePromise<$models.RoadmapItem | null> {
    return $Call.ByID(1739743073, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetItems 获取所有路线图项目
 * @frontend
 */
export function GetItems(): $CancellablePromise<$models.RoadmapItem[]> {
    return $Call.ByID(1338747222).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ReloadConfig 重新加载配置文件
 * @frontend
 */
export function ReloadConfig(): $CancellablePromise<void> {
    return $Call.ByID(3008448881);
}

/**
 * SubmitSuggestion 提交新建议
 * @frontend
 */
export function SubmitSuggestion(req: $models.SubmitSuggestionRequest): $CancellablePromise<$models.RoadmapItem | null> {
    return $Call.ByID(4091291746, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateStatus 更新项目状态
 * @frontend
 */
export function UpdateStatus(id: string, status: $models.RoadmapStatus): $CancellablePromise<$models.RoadmapItem | null> {
    return $Call.ByID(3552882417, id, status).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Vote 投票
 * @frontend
 */
export function Vote(req: $models.VoteRequest): $CancellablePromise<$models.RoadmapItem | null> {
    return $Call.ByID(171333378, req).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.RoadmapItem.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
