// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ItemCfg 道具配置
 */
export class ItemCfg {
    "ItemId": number;
    "Count": number;

    /** Creates a new ItemCfg instance. */
    constructor($$source: Partial<ItemCfg> = {}) {
        if (!("ItemId" in $$source)) {
            this["ItemId"] = 0;
        }
        if (!("Count" in $$source)) {
            this["Count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemCfg instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemCfg {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ItemCfg($$parsedSource as Partial<ItemCfg>);
    }
}

/**
 * SeasonPassDiff 赛季战令表差异数据结构
 */
export class SeasonPassDiff {
    "Id": number;
    "Name": string;
    "LevelLimit": number;
    "StartTime": string;
    "EndTime": string;
    "ExtTime": string;
    "ExpPerLevel": number;
    "ExpShowItemId": number;
    "PerLevelBuyCost": ItemCfg[];
    "WeekExpLimit": number;
    "NormalLuckyBag": ItemCfg[];
    "HighLuckyBag": ItemCfg[];
    "LoopExp": number;
    "MailId": number;
    "HeroId": number;
    "SkinId": number;
    "SeasonIcon": string;
    "SeasonBg": string;
    "SeasonStartIcon": string;
    "GoldBagId": number;
    "TreasureBagId": number;
    "RechargeGoldId": number;
    "RechargeUpTreasureId": number;
    "RechargeTreasureId": number;
    "SeasonGoldBg": string;
    "SeasonTreasureBg": string;

    /** Creates a new SeasonPassDiff instance. */
    constructor($$source: Partial<SeasonPassDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("LevelLimit" in $$source)) {
            this["LevelLimit"] = 0;
        }
        if (!("StartTime" in $$source)) {
            this["StartTime"] = "";
        }
        if (!("EndTime" in $$source)) {
            this["EndTime"] = "";
        }
        if (!("ExtTime" in $$source)) {
            this["ExtTime"] = "";
        }
        if (!("ExpPerLevel" in $$source)) {
            this["ExpPerLevel"] = 0;
        }
        if (!("ExpShowItemId" in $$source)) {
            this["ExpShowItemId"] = 0;
        }
        if (!("PerLevelBuyCost" in $$source)) {
            this["PerLevelBuyCost"] = [];
        }
        if (!("WeekExpLimit" in $$source)) {
            this["WeekExpLimit"] = 0;
        }
        if (!("NormalLuckyBag" in $$source)) {
            this["NormalLuckyBag"] = [];
        }
        if (!("HighLuckyBag" in $$source)) {
            this["HighLuckyBag"] = [];
        }
        if (!("LoopExp" in $$source)) {
            this["LoopExp"] = 0;
        }
        if (!("MailId" in $$source)) {
            this["MailId"] = 0;
        }
        if (!("HeroId" in $$source)) {
            this["HeroId"] = 0;
        }
        if (!("SkinId" in $$source)) {
            this["SkinId"] = 0;
        }
        if (!("SeasonIcon" in $$source)) {
            this["SeasonIcon"] = "";
        }
        if (!("SeasonBg" in $$source)) {
            this["SeasonBg"] = "";
        }
        if (!("SeasonStartIcon" in $$source)) {
            this["SeasonStartIcon"] = "";
        }
        if (!("GoldBagId" in $$source)) {
            this["GoldBagId"] = 0;
        }
        if (!("TreasureBagId" in $$source)) {
            this["TreasureBagId"] = 0;
        }
        if (!("RechargeGoldId" in $$source)) {
            this["RechargeGoldId"] = 0;
        }
        if (!("RechargeUpTreasureId" in $$source)) {
            this["RechargeUpTreasureId"] = 0;
        }
        if (!("RechargeTreasureId" in $$source)) {
            this["RechargeTreasureId"] = 0;
        }
        if (!("SeasonGoldBg" in $$source)) {
            this["SeasonGoldBg"] = "";
        }
        if (!("SeasonTreasureBg" in $$source)) {
            this["SeasonTreasureBg"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SeasonPassDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): SeasonPassDiff {
        const $$createField8_0 = $$createType1;
        const $$createField10_0 = $$createType1;
        const $$createField11_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("PerLevelBuyCost" in $$parsedSource) {
            $$parsedSource["PerLevelBuyCost"] = $$createField8_0($$parsedSource["PerLevelBuyCost"]);
        }
        if ("NormalLuckyBag" in $$parsedSource) {
            $$parsedSource["NormalLuckyBag"] = $$createField10_0($$parsedSource["NormalLuckyBag"]);
        }
        if ("HighLuckyBag" in $$parsedSource) {
            $$parsedSource["HighLuckyBag"] = $$createField11_0($$parsedSource["HighLuckyBag"]);
        }
        return new SeasonPassDiff($$parsedSource as Partial<SeasonPassDiff>);
    }
}

// Private type creation functions
const $$createType0 = ItemCfg.createFrom;
const $$createType1 = $Create.Array($$createType0);
