// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ColAttr 列属性定义
 * 描述 Excel 表格中某一列的类型、名称、状态等信息
 */
export class ColAttr {
    /**
     * AttrName 属性名称（字段名，如 Id、Name 等）
     */
    "AttrName": string;

    /**
     * AttrType 属性类型（如 int、string、bool、E#枚举名 等）
     */
    "AttrType": string;

    /**
     * AttrCHS 属性中文名称（用于显示和文档说明）
     */
    "AttrCHS": string;

    /**
     * ColStatus 列状态（正常列、注释列、枚举列、空列、错误列）
     */
    "ColStatus": EColType;

    /**
     * Error 错误信息，如果不为空说明该列存在解析问题
     */
    "Error": string;

    /** Creates a new ColAttr instance. */
    constructor($$source: Partial<ColAttr> = {}) {
        if (!("AttrName" in $$source)) {
            this["AttrName"] = "";
        }
        if (!("AttrType" in $$source)) {
            this["AttrType"] = "";
        }
        if (!("AttrCHS" in $$source)) {
            this["AttrCHS"] = "";
        }
        if (!("ColStatus" in $$source)) {
            this["ColStatus"] = EColType.$zero;
        }
        if (!("Error" in $$source)) {
            this["Error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColAttr instance from a string or object.
     */
    static createFrom($$source: any = {}): ColAttr {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColAttr($$parsedSource as Partial<ColAttr>);
    }
}

/**
 * EColType 列状态枚举类型
 * 定义 Excel 列的多种状态类型
 */
export enum EColType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * NORMAL 正常列：包含有效的属性名和类型定义
     */
    NORMAL = 0,

    /**
     * COMMENT 注释列：以 "#" 标记，用于策划备注，不参与数据导出
     */
    COMMENT = 1,

    /**
     * ENUM 枚举列：以 "E#" 开头的类型定义
     */
    ENUM = 2,

    /**
     * EMPTY 空列：类型和名称都为空的列
     */
    EMPTY = 3,

    /**
     * ERROR 错误列：类型和名称不匹配或格式错误的列
     */
    ERROR = 4,
};

/**
 * Sheet 表示 Excel 中的一个工作表
 * 包含工作表名称、类型、表头信息和错误状态
 */
export class Sheet {
    /**
     * Name 工作表名称
     */
    "Name": string;

    /**
     * SheetType 工作表类型（普通表、枚举表等）
     */
    "SheetType": SheetType;

    /**
     * Header 工作表表头信息，包含列属性定义
     */
    "Header": SheetHeader | null;

    /**
     * Error 错误信息，如果不为空说明解析过程中发现问题
     */
    "Error": string;

    /** Creates a new Sheet instance. */
    constructor($$source: Partial<Sheet> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("SheetType" in $$source)) {
            this["SheetType"] = SheetType.$zero;
        }
        if (!("Header" in $$source)) {
            this["Header"] = null;
        }
        if (!("Error" in $$source)) {
            this["Error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Sheet instance from a string or object.
     */
    static createFrom($$source: any = {}): Sheet {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Header" in $$parsedSource) {
            $$parsedSource["Header"] = $$createField2_0($$parsedSource["Header"]);
        }
        return new Sheet($$parsedSource as Partial<Sheet>);
    }
}

/**
 * SheetHeader 工作表表头信息
 * 包含所有列的属性定义集合
 */
export class SheetHeader {
    /**
     * Col 列属性集合
     */
    "Col": (ColAttr | null)[];

    /** Creates a new SheetHeader instance. */
    constructor($$source: Partial<SheetHeader> = {}) {
        if (!("Col" in $$source)) {
            this["Col"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SheetHeader instance from a string or object.
     */
    static createFrom($$source: any = {}): SheetHeader {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Col" in $$parsedSource) {
            $$parsedSource["Col"] = $$createField0_0($$parsedSource["Col"]);
        }
        return new SheetHeader($$parsedSource as Partial<SheetHeader>);
    }
}

/**
 * SheetType 工作表类型枚举
 * 定义 Excel 工作表的分类类型
 */
export enum SheetType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * NONE 未定义类型
     */
    NONE = 0,

    /**
     * MING_JIANG_SHA 普通名将杀配表（标准4行表头：中文、类型、字段名、导出标识）
     */
    MING_JIANG_SHA = 1,

    /**
     * MING_JIANG_SHA_ENUM 名将杀枚举配表（特殊格式：name、value、description）
     */
    MING_JIANG_SHA_ENUM = 2,
};

// Private type creation functions
const $$createType0 = SheetHeader.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = ColAttr.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
