// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DropItemDiff {
    "Id": number;
    "Name": string;
    "DropGroup": number;
    "Item": ItemCfg[];
    "Weight": number;
    "WeightInc": number;
    "Deduplication": boolean;
    "CheckExist": boolean;
    "ExcludeExist": boolean;
    "MustHave": boolean;
    "ReplaceGroup": number;
    "ValidDate": string;
    "ExpireDate": string;

    /** Creates a new DropItemDiff instance. */
    constructor($$source: Partial<DropItemDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("DropGroup" in $$source)) {
            this["DropGroup"] = 0;
        }
        if (!("Item" in $$source)) {
            this["Item"] = [];
        }
        if (!("Weight" in $$source)) {
            this["Weight"] = 0;
        }
        if (!("WeightInc" in $$source)) {
            this["WeightInc"] = 0;
        }
        if (!("Deduplication" in $$source)) {
            this["Deduplication"] = false;
        }
        if (!("CheckExist" in $$source)) {
            this["CheckExist"] = false;
        }
        if (!("ExcludeExist" in $$source)) {
            this["ExcludeExist"] = false;
        }
        if (!("MustHave" in $$source)) {
            this["MustHave"] = false;
        }
        if (!("ReplaceGroup" in $$source)) {
            this["ReplaceGroup"] = 0;
        }
        if (!("ValidDate" in $$source)) {
            this["ValidDate"] = "";
        }
        if (!("ExpireDate" in $$source)) {
            this["ExpireDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DropItemDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): DropItemDiff {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Item" in $$parsedSource) {
            $$parsedSource["Item"] = $$createField3_0($$parsedSource["Item"]);
        }
        return new DropItemDiff($$parsedSource as Partial<DropItemDiff>);
    }
}

export class ItemCfg {
    "ItemId": number;
    "Count": number;

    /** Creates a new ItemCfg instance. */
    constructor($$source: Partial<ItemCfg> = {}) {
        if (!("ItemId" in $$source)) {
            this["ItemId"] = 0;
        }
        if (!("Count" in $$source)) {
            this["Count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemCfg instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemCfg {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ItemCfg($$parsedSource as Partial<ItemCfg>);
    }
}

// Private type creation functions
const $$createType0 = ItemCfg.createFrom;
const $$createType1 = $Create.Array($$createType0);
