// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AccumulatedRechargeDiff 累充奖励表单行数据
 */
export class AccumulatedRechargeDiff {
    "Id": number;

    /**
     * EActivityId 枚举值，如 "Activity_AccumulatedRecharge1"
     */
    "ActId": string;

    /**
     * 累充门槛金额
     */
    "RechargeNum": number;

    /**
     * 奖励原始字符串
     */
    "Reward": string;

    /**
     * 解析后的奖励道具列表
     */
    "RewardItems": ItemCfg[];

    /** Creates a new AccumulatedRechargeDiff instance. */
    constructor($$source: Partial<AccumulatedRechargeDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("ActId" in $$source)) {
            this["ActId"] = "";
        }
        if (!("RechargeNum" in $$source)) {
            this["RechargeNum"] = 0;
        }
        if (!("Reward" in $$source)) {
            this["Reward"] = "";
        }
        if (!("RewardItems" in $$source)) {
            this["RewardItems"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccumulatedRechargeDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): AccumulatedRechargeDiff {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("RewardItems" in $$parsedSource) {
            $$parsedSource["RewardItems"] = $$createField4_0($$parsedSource["RewardItems"]);
        }
        return new AccumulatedRechargeDiff($$parsedSource as Partial<AccumulatedRechargeDiff>);
    }
}

/**
 * ItemCfg 道具配置，从花括号格式 {itemId;count} 解析
 */
export class ItemCfg {
    "ItemId": number;
    "Count": number;

    /** Creates a new ItemCfg instance. */
    constructor($$source: Partial<ItemCfg> = {}) {
        if (!("ItemId" in $$source)) {
            this["ItemId"] = 0;
        }
        if (!("Count" in $$source)) {
            this["Count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemCfg instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemCfg {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ItemCfg($$parsedSource as Partial<ItemCfg>);
    }
}

// Private type creation functions
const $$createType0 = ItemCfg.createFrom;
const $$createType1 = $Create.Array($$createType0);
