// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class HeroLinesDiff {
    "Id": number;

    /**
     * ELinesType
     */
    "Type": string;
    "TabName": string;
    "Text": string;

    /**
     * EAudioId
     */
    "AudioId": string;
    "Achievements": number[];

    /**
     * ELinesGroupId
     */
    "GroupId": string;

    /** Creates a new HeroLinesDiff instance. */
    constructor($$source: Partial<HeroLinesDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("Type" in $$source)) {
            this["Type"] = "";
        }
        if (!("TabName" in $$source)) {
            this["TabName"] = "";
        }
        if (!("Text" in $$source)) {
            this["Text"] = "";
        }
        if (!("AudioId" in $$source)) {
            this["AudioId"] = "";
        }
        if (!("Achievements" in $$source)) {
            this["Achievements"] = [];
        }
        if (!("GroupId" in $$source)) {
            this["GroupId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroLinesDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroLinesDiff {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Achievements" in $$parsedSource) {
            $$parsedSource["Achievements"] = $$createField5_0($$parsedSource["Achievements"]);
        }
        return new HeroLinesDiff($$parsedSource as Partial<HeroLinesDiff>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
