// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService 聊天服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearHistory 清空历史
 * @frontend
 */
export function ClearHistory(): $CancellablePromise<void> {
    return $Call.ByID(554406882);
}

/**
 * GetConfig 获取当前配置
 * @frontend
 */
export function GetConfig(): $CancellablePromise<$models.ChatConfig | null> {
    return $Call.ByID(1037738133).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetHistory 获取历史记录
 * @frontend
 */
export function GetHistory(): $CancellablePromise<$models.ChatSession | null> {
    return $Call.ByID(861879113).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ImportFromClaudeCode 从 Claude Code 配置导入
 * @frontend
 */
export function ImportFromClaudeCode(): $CancellablePromise<$models.ChatConfig | null> {
    return $Call.ByID(2267233051).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveConfig 保存配置
 * @frontend
 */
export function SaveConfig(config: $models.ChatConfig | null): $CancellablePromise<void> {
    return $Call.ByID(3839611302, config);
}

/**
 * SendMessageStream 流式发送消息
 * @frontend
 */
export function SendMessageStream(content: string): $CancellablePromise<void> {
    return $Call.ByID(512848718, content);
}

/**
 * StopStream 停止流式生成
 * @frontend
 */
export function StopStream(): $CancellablePromise<void> {
    return $Call.ByID(2028119333);
}

// Private type creation functions
const $$createType0 = $models.ChatConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ChatSession.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
