// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AnthropicConfig Anthropic 配置
 */
export class AnthropicConfig {
    "apiKey": string;

    /**
     * 可选，支持代理
     */
    "baseUrl": string;

    /**
     * 默认 "claude-3-5-sonnet-20241022"
     */
    "model": string;

    /**
     * 默认 4096
     */
    "maxTokens": number;

    /** Creates a new AnthropicConfig instance. */
    constructor($$source: Partial<AnthropicConfig> = {}) {
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("maxTokens" in $$source)) {
            this["maxTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnthropicConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AnthropicConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AnthropicConfig($$parsedSource as Partial<AnthropicConfig>);
    }
}

/**
 * ChatConfig 聊天配置
 */
export class ChatConfig {
    /**
     * "anthropic" | "openai"
     */
    "provider": string;
    "anthropicConfig": AnthropicConfig;
    "openaiConfig": OpenAIConfig;
    "systemPrompt": string;

    /** Creates a new ChatConfig instance. */
    constructor($$source: Partial<ChatConfig> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("anthropicConfig" in $$source)) {
            this["anthropicConfig"] = (new AnthropicConfig());
        }
        if (!("openaiConfig" in $$source)) {
            this["openaiConfig"] = (new OpenAIConfig());
        }
        if (!("systemPrompt" in $$source)) {
            this["systemPrompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatConfig {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("anthropicConfig" in $$parsedSource) {
            $$parsedSource["anthropicConfig"] = $$createField1_0($$parsedSource["anthropicConfig"]);
        }
        if ("openaiConfig" in $$parsedSource) {
            $$parsedSource["openaiConfig"] = $$createField2_0($$parsedSource["openaiConfig"]);
        }
        return new ChatConfig($$parsedSource as Partial<ChatConfig>);
    }
}

/**
 * ChatMessage 对话消息（用于前端交互和 JSON 序列化）
 */
export class ChatMessage {
    /**
     * "user" | "assistant"
     */
    "role": string;
    "content": string;

    /**
     * Unix 时间戳
     */
    "timestamp": number;

    /** Creates a new ChatMessage instance. */
    constructor($$source: Partial<ChatMessage> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatMessage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatMessage($$parsedSource as Partial<ChatMessage>);
    }
}

/**
 * ChatSession 对话会话（用于前端交互和 JSON 序列化）
 */
export class ChatSession {
    "id": string;
    "messages": ChatMessage[];
    "createdAt": number;
    "updatedAt": number;

    /** Creates a new ChatSession instance. */
    constructor($$source: Partial<ChatSession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatSession instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatSession {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField1_0($$parsedSource["messages"]);
        }
        return new ChatSession($$parsedSource as Partial<ChatSession>);
    }
}

/**
 * OpenAIConfig OpenAI 配置
 */
export class OpenAIConfig {
    "apiKey": string;

    /**
     * 可选，支持自定义 API
     */
    "baseUrl": string;

    /**
     * 默认 "gpt-4o"
     */
    "model": string;

    /**
     * 默认 4096
     */
    "maxTokens": number;

    /** Creates a new OpenAIConfig instance. */
    constructor($$source: Partial<OpenAIConfig> = {}) {
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("maxTokens" in $$source)) {
            this["maxTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenAIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenAIConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenAIConfig($$parsedSource as Partial<OpenAIConfig>);
    }
}

// Private type creation functions
const $$createType0 = AnthropicConfig.createFrom;
const $$createType1 = OpenAIConfig.createFrom;
const $$createType2 = ChatMessage.createFrom;
const $$createType3 = $Create.Array($$createType2);
