// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../../encoding/json/models.js";

/**
 * RecordEntry 单条消息记录
 */
export class RecordEntry {
    "offset_ms": number;
    "msg_id": number;
    "msg_name": string;
    "seq_id": number;

    /**
     * "→" 客户端→服务端, "←" 服务端→客户端
     */
    "direction": string;

    /**
     * 消息描述信息（用户可编辑）
     */
    "descript"?: string;
    "payload_json": json$0.RawMessage;

    /**
     * 字段路径→4态值映射（前端编辑状态）
     */
    "field_values"?: { [_ in string]?: any };

    /** Creates a new RecordEntry instance. */
    constructor($$source: Partial<RecordEntry> = {}) {
        if (!("offset_ms" in $$source)) {
            this["offset_ms"] = 0;
        }
        if (!("msg_id" in $$source)) {
            this["msg_id"] = 0;
        }
        if (!("msg_name" in $$source)) {
            this["msg_name"] = "";
        }
        if (!("seq_id" in $$source)) {
            this["seq_id"] = 0;
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }
        if (!("payload_json" in $$source)) {
            this["payload_json"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordEntry {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("field_values" in $$parsedSource) {
            $$parsedSource["field_values"] = $$createField7_0($$parsedSource["field_values"]);
        }
        return new RecordEntry($$parsedSource as Partial<RecordEntry>);
    }
}

/**
 * Recording 录制文件结构
 */
export class Recording {
    "version": number;
    "recorded_at": string;
    "server_addr": string;

    /**
     * LoginPayloadB64 保存客户端 LoginReq 的解密后 payload（base64 编码）
     * 重放时替换其中的 Token 字段后重新加密发送
     */
    "login_payload_b64"?: string;
    "messages": (RecordEntry | null)[];

    /** Creates a new Recording instance. */
    constructor($$source: Partial<Recording> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("recorded_at" in $$source)) {
            this["recorded_at"] = "";
        }
        if (!("server_addr" in $$source)) {
            this["server_addr"] = "";
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Recording instance from a string or object.
     */
    static createFrom($$source: any = {}): Recording {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField4_0($$parsedSource["messages"]);
        }
        return new Recording($$parsedSource as Partial<Recording>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = RecordEntry.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType2);
