// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ItemCfg 道具配置（格式：{物品ID;数量}）
 */
export class ItemCfg {
    "ItemId": number;
    "Count": number;

    /** Creates a new ItemCfg instance. */
    constructor($$source: Partial<ItemCfg> = {}) {
        if (!("ItemId" in $$source)) {
            this["ItemId"] = 0;
        }
        if (!("Count" in $$source)) {
            this["Count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemCfg instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemCfg {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ItemCfg($$parsedSource as Partial<ItemCfg>);
    }
}

export class SeasonPassRewardDiff {
    "Id": number;
    "SeasonPassId": number;
    "Level": number;

    /**
     * ItemCfg[] 类型，格式 {物品ID;数量}
     */
    "NormalReward": ItemCfg[];

    /**
     * ItemCfg[] 类型，格式 {物品ID;数量}
     */
    "HighReward": ItemCfg[];

    /** Creates a new SeasonPassRewardDiff instance. */
    constructor($$source: Partial<SeasonPassRewardDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("SeasonPassId" in $$source)) {
            this["SeasonPassId"] = 0;
        }
        if (!("Level" in $$source)) {
            this["Level"] = 0;
        }
        if (!("NormalReward" in $$source)) {
            this["NormalReward"] = [];
        }
        if (!("HighReward" in $$source)) {
            this["HighReward"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SeasonPassRewardDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): SeasonPassRewardDiff {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("NormalReward" in $$parsedSource) {
            $$parsedSource["NormalReward"] = $$createField3_0($$parsedSource["NormalReward"]);
        }
        if ("HighReward" in $$parsedSource) {
            $$parsedSource["HighReward"] = $$createField4_0($$parsedSource["HighReward"]);
        }
        return new SeasonPassRewardDiff($$parsedSource as Partial<SeasonPassRewardDiff>);
    }
}

// Private type creation functions
const $$createType0 = ItemCfg.createFrom;
const $$createType1 = $Create.Array($$createType0);
