// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class RecommendBdDiff {
    /**
     * 武将ID
     */
    "HeroId": string;

    /**
     * 壹地1_4 (KVPair[])
     */
    "Level1": string[];

    /**
     * 贰北2_8 (KVPair[])
     */
    "Level2": string[];

    /**
     * 叁西3_12 (KVPair[])
     */
    "Level3": string[];

    /**
     * 肆南4_16 (KVPair[])
     */
    "Level4": string[];

    /**
     * 伍东5_20 (KVPair[])
     */
    "Level5": string[];

    /**
     * 陆天6_24 (KVPair[])
     */
    "Level6": string[];

    /** Creates a new RecommendBdDiff instance. */
    constructor($$source: Partial<RecommendBdDiff> = {}) {
        if (!("HeroId" in $$source)) {
            this["HeroId"] = "";
        }
        if (!("Level1" in $$source)) {
            this["Level1"] = [];
        }
        if (!("Level2" in $$source)) {
            this["Level2"] = [];
        }
        if (!("Level3" in $$source)) {
            this["Level3"] = [];
        }
        if (!("Level4" in $$source)) {
            this["Level4"] = [];
        }
        if (!("Level5" in $$source)) {
            this["Level5"] = [];
        }
        if (!("Level6" in $$source)) {
            this["Level6"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecommendBdDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): RecommendBdDiff {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Level1" in $$parsedSource) {
            $$parsedSource["Level1"] = $$createField1_0($$parsedSource["Level1"]);
        }
        if ("Level2" in $$parsedSource) {
            $$parsedSource["Level2"] = $$createField2_0($$parsedSource["Level2"]);
        }
        if ("Level3" in $$parsedSource) {
            $$parsedSource["Level3"] = $$createField3_0($$parsedSource["Level3"]);
        }
        if ("Level4" in $$parsedSource) {
            $$parsedSource["Level4"] = $$createField4_0($$parsedSource["Level4"]);
        }
        if ("Level5" in $$parsedSource) {
            $$parsedSource["Level5"] = $$createField5_0($$parsedSource["Level5"]);
        }
        if ("Level6" in $$parsedSource) {
            $$parsedSource["Level6"] = $$createField6_0($$parsedSource["Level6"]);
        }
        return new RecommendBdDiff($$parsedSource as Partial<RecommendBdDiff>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
