// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hero_skin_item$0 from "./hero_skin_item/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skill_lines$0 from "./skill_lines/models.js";

export class AudioRefExcel {
    /**
     * 武将Id=>是否开放
     */
    "HeroIdOpenMap": { [_ in `${number}`]?: boolean };

    /**
     * 武将Id=>技能INT[]
     */
    "HeroSkillsMap": { [_ in `${number}`]?: number[] };

    /**
     * 武将Id=>技能INT[]
     */
    "HeroNameMap": { [_ in `${number}`]?: string };

    /**
     * 技能枚举=>技能ID
     */
    "SkillEnumIdMap": { [_ in string]?: number };

    /**
     * 技能ID=>技能枚举
     */
    "SkillIdEnumMap": { [_ in `${number}`]?: string };

    /**
     * 技能ID=>中文名
     */
    "SkillIdNameMap": { [_ in `${number}`]?: string };

    /**
     * 技能枚举INT=>台词ID
     */
    "SkillIdLineVoiceIdMap": { [_ in `${number}`]?: skill_lines$0.SkillLineVoice };

    /**
     * 武将Id=>皮肤枚举INT=>台词ID
     */
    "HeroSkinLineVoiceIdMap": { [_ in `${number}`]?: hero_skin_item$0.SkinLineVoiceMap };

    /**
     * 皮肤枚举INT=>台词枚举
     */
    "SkinIdNameMap": { [_ in `${number}`]?: string };

    /**
     * 皮肤枚举INT=>皮肤是否开放
     */
    "SkinIdOpenMap": { [_ in `${number}`]?: boolean };

    /**
     * 台词Id=>音效枚举
     */
    "LineVoiceIdEnumMap": { [_ in `${number}`]?: string };

    /**
     * 音效枚举=>台词Id
     */
    "LineVoiceEnumIdMap": { [_ in string]?: number };

    /**
     * 音效枚举=>台词路径数组
     */
    "AudioEnumPathMap": { [_ in string]?: string[] };

    /**
     * 音效枚举=>台词类型(用于确定资源目录)
     */
    "AudioEnumTypeEnumMap": { [_ in string]?: string };

    /**
     * 皮肤道具ID=>动画音效枚举
     */
    "SkinIdSpineAnimAudioMap": { [_ in `${number}`]?: string[] };

    /**
     * 皮肤道具ID=>击杀动画音效枚举
     */
    "SkinIdKillAudioMap": { [_ in `${number}`]?: string };

    /**
     * 技能ESkillId枚举=>出牌音效枚举
     */
    "SkillEnumPlayCardAudioEnumMap": { [_ in string]?: string };

    /**
     * 技能ESkillId枚举=>身份技能音效枚举数组
     */
    "SkillEnumIdentityLineVoiceEnumMap": { [_ in string]?: string[] };

    /**
     * 技能ESkillId枚举=>出发技能台词ID数组
     */
    "SkillEnumLineVoiceIdMap": { [_ in string]?: number[] };

    /**
     * 技能ESkillId枚举=>特殊音效枚举
     */
    "SkillEnumSpecialAudioEnumMap": { [_ in string]?: string };

    /** Creates a new AudioRefExcel instance. */
    constructor($$source: Partial<AudioRefExcel> = {}) {
        if (!("HeroIdOpenMap" in $$source)) {
            this["HeroIdOpenMap"] = {};
        }
        if (!("HeroSkillsMap" in $$source)) {
            this["HeroSkillsMap"] = {};
        }
        if (!("HeroNameMap" in $$source)) {
            this["HeroNameMap"] = {};
        }
        if (!("SkillEnumIdMap" in $$source)) {
            this["SkillEnumIdMap"] = {};
        }
        if (!("SkillIdEnumMap" in $$source)) {
            this["SkillIdEnumMap"] = {};
        }
        if (!("SkillIdNameMap" in $$source)) {
            this["SkillIdNameMap"] = {};
        }
        if (!("SkillIdLineVoiceIdMap" in $$source)) {
            this["SkillIdLineVoiceIdMap"] = {};
        }
        if (!("HeroSkinLineVoiceIdMap" in $$source)) {
            this["HeroSkinLineVoiceIdMap"] = {};
        }
        if (!("SkinIdNameMap" in $$source)) {
            this["SkinIdNameMap"] = {};
        }
        if (!("SkinIdOpenMap" in $$source)) {
            this["SkinIdOpenMap"] = {};
        }
        if (!("LineVoiceIdEnumMap" in $$source)) {
            this["LineVoiceIdEnumMap"] = {};
        }
        if (!("LineVoiceEnumIdMap" in $$source)) {
            this["LineVoiceEnumIdMap"] = {};
        }
        if (!("AudioEnumPathMap" in $$source)) {
            this["AudioEnumPathMap"] = {};
        }
        if (!("AudioEnumTypeEnumMap" in $$source)) {
            this["AudioEnumTypeEnumMap"] = {};
        }
        if (!("SkinIdSpineAnimAudioMap" in $$source)) {
            this["SkinIdSpineAnimAudioMap"] = {};
        }
        if (!("SkinIdKillAudioMap" in $$source)) {
            this["SkinIdKillAudioMap"] = {};
        }
        if (!("SkillEnumPlayCardAudioEnumMap" in $$source)) {
            this["SkillEnumPlayCardAudioEnumMap"] = {};
        }
        if (!("SkillEnumIdentityLineVoiceEnumMap" in $$source)) {
            this["SkillEnumIdentityLineVoiceEnumMap"] = {};
        }
        if (!("SkillEnumLineVoiceIdMap" in $$source)) {
            this["SkillEnumLineVoiceIdMap"] = {};
        }
        if (!("SkillEnumSpecialAudioEnumMap" in $$source)) {
            this["SkillEnumSpecialAudioEnumMap"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AudioRefExcel instance from a string or object.
     */
    static createFrom($$source: any = {}): AudioRefExcel {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType6;
        const $$createField7_0 = $$createType10;
        const $$createField8_0 = $$createType3;
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType3;
        const $$createField11_0 = $$createType4;
        const $$createField12_0 = $$createType12;
        const $$createField13_0 = $$createType13;
        const $$createField14_0 = $$createType14;
        const $$createField15_0 = $$createType3;
        const $$createField16_0 = $$createType13;
        const $$createField17_0 = $$createType12;
        const $$createField18_0 = $$createType15;
        const $$createField19_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("HeroIdOpenMap" in $$parsedSource) {
            $$parsedSource["HeroIdOpenMap"] = $$createField0_0($$parsedSource["HeroIdOpenMap"]);
        }
        if ("HeroSkillsMap" in $$parsedSource) {
            $$parsedSource["HeroSkillsMap"] = $$createField1_0($$parsedSource["HeroSkillsMap"]);
        }
        if ("HeroNameMap" in $$parsedSource) {
            $$parsedSource["HeroNameMap"] = $$createField2_0($$parsedSource["HeroNameMap"]);
        }
        if ("SkillEnumIdMap" in $$parsedSource) {
            $$parsedSource["SkillEnumIdMap"] = $$createField3_0($$parsedSource["SkillEnumIdMap"]);
        }
        if ("SkillIdEnumMap" in $$parsedSource) {
            $$parsedSource["SkillIdEnumMap"] = $$createField4_0($$parsedSource["SkillIdEnumMap"]);
        }
        if ("SkillIdNameMap" in $$parsedSource) {
            $$parsedSource["SkillIdNameMap"] = $$createField5_0($$parsedSource["SkillIdNameMap"]);
        }
        if ("SkillIdLineVoiceIdMap" in $$parsedSource) {
            $$parsedSource["SkillIdLineVoiceIdMap"] = $$createField6_0($$parsedSource["SkillIdLineVoiceIdMap"]);
        }
        if ("HeroSkinLineVoiceIdMap" in $$parsedSource) {
            $$parsedSource["HeroSkinLineVoiceIdMap"] = $$createField7_0($$parsedSource["HeroSkinLineVoiceIdMap"]);
        }
        if ("SkinIdNameMap" in $$parsedSource) {
            $$parsedSource["SkinIdNameMap"] = $$createField8_0($$parsedSource["SkinIdNameMap"]);
        }
        if ("SkinIdOpenMap" in $$parsedSource) {
            $$parsedSource["SkinIdOpenMap"] = $$createField9_0($$parsedSource["SkinIdOpenMap"]);
        }
        if ("LineVoiceIdEnumMap" in $$parsedSource) {
            $$parsedSource["LineVoiceIdEnumMap"] = $$createField10_0($$parsedSource["LineVoiceIdEnumMap"]);
        }
        if ("LineVoiceEnumIdMap" in $$parsedSource) {
            $$parsedSource["LineVoiceEnumIdMap"] = $$createField11_0($$parsedSource["LineVoiceEnumIdMap"]);
        }
        if ("AudioEnumPathMap" in $$parsedSource) {
            $$parsedSource["AudioEnumPathMap"] = $$createField12_0($$parsedSource["AudioEnumPathMap"]);
        }
        if ("AudioEnumTypeEnumMap" in $$parsedSource) {
            $$parsedSource["AudioEnumTypeEnumMap"] = $$createField13_0($$parsedSource["AudioEnumTypeEnumMap"]);
        }
        if ("SkinIdSpineAnimAudioMap" in $$parsedSource) {
            $$parsedSource["SkinIdSpineAnimAudioMap"] = $$createField14_0($$parsedSource["SkinIdSpineAnimAudioMap"]);
        }
        if ("SkinIdKillAudioMap" in $$parsedSource) {
            $$parsedSource["SkinIdKillAudioMap"] = $$createField15_0($$parsedSource["SkinIdKillAudioMap"]);
        }
        if ("SkillEnumPlayCardAudioEnumMap" in $$parsedSource) {
            $$parsedSource["SkillEnumPlayCardAudioEnumMap"] = $$createField16_0($$parsedSource["SkillEnumPlayCardAudioEnumMap"]);
        }
        if ("SkillEnumIdentityLineVoiceEnumMap" in $$parsedSource) {
            $$parsedSource["SkillEnumIdentityLineVoiceEnumMap"] = $$createField17_0($$parsedSource["SkillEnumIdentityLineVoiceEnumMap"]);
        }
        if ("SkillEnumLineVoiceIdMap" in $$parsedSource) {
            $$parsedSource["SkillEnumLineVoiceIdMap"] = $$createField18_0($$parsedSource["SkillEnumLineVoiceIdMap"]);
        }
        if ("SkillEnumSpecialAudioEnumMap" in $$parsedSource) {
            $$parsedSource["SkillEnumSpecialAudioEnumMap"] = $$createField19_0($$parsedSource["SkillEnumSpecialAudioEnumMap"]);
        }
        return new AudioRefExcel($$parsedSource as Partial<AudioRefExcel>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = skill_lines$0.SkillLineVoice.createFrom;
const $$createType6 = $Create.Map($Create.Any, $$createType5);
var $$createType7 = (function $$initCreateType7(...args: any[]): any {
    if ($$createType7 === $$initCreateType7) {
        $$createType7 = $$createType9;
    }
    return $$createType7(...args);
});
const $$createType8 = hero_skin_item$0.SkinLineVoice.createFrom;
const $$createType9 = $Create.Map($Create.Any, $$createType8);
const $$createType10 = $Create.Map($Create.Any, $$createType7);
const $$createType11 = $Create.Array($Create.Any);
const $$createType12 = $Create.Map($Create.Any, $$createType11);
const $$createType13 = $Create.Map($Create.Any, $Create.Any);
const $$createType14 = $Create.Map($Create.Any, $$createType11);
const $$createType15 = $Create.Map($Create.Any, $$createType1);
