// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BuffDiff {
    "Id": string;
    "EBuffId": string;
    "Name": string;
    "NeedRecord": boolean;
    "BuffType": number;
    "IsDeleteByCasterDead": boolean;
    "IsDeleteByExecutorDead": boolean;
    "IsValidByFengJin": boolean;
    "IsReserveByRemoveSkill": boolean;
    "TransferSkillBuffType": number;
    "Round": number;
    "Value": number;
    "EndByEffect": boolean;
    "EndType": string;
    "IsServerOnly": boolean;
    "IsCasterOnly": boolean;
    "OwnerType": number;
    "ShowArea": string;
    "Icon": string;
    "Effect": number;
    "FlashEffect": number;
    "BuffPriority": number;
    "OverlyingType": number;
    "IsTrigger": boolean;
    "BuffState": number[];
    "BuffPro": number[];
    "ProValue": number[];
    "CostEffectValue": number[];
    "TriggerTiming": number[];
    "TriggerPriority": number[];
    "TriggerCondition": string[];
    "TriggerAction": number[];
    "BuffDot": number;
    "EffectDescribe": string;

    /** Creates a new BuffDiff instance. */
    constructor($$source: Partial<BuffDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("EBuffId" in $$source)) {
            this["EBuffId"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("NeedRecord" in $$source)) {
            this["NeedRecord"] = false;
        }
        if (!("BuffType" in $$source)) {
            this["BuffType"] = 0;
        }
        if (!("IsDeleteByCasterDead" in $$source)) {
            this["IsDeleteByCasterDead"] = false;
        }
        if (!("IsDeleteByExecutorDead" in $$source)) {
            this["IsDeleteByExecutorDead"] = false;
        }
        if (!("IsValidByFengJin" in $$source)) {
            this["IsValidByFengJin"] = false;
        }
        if (!("IsReserveByRemoveSkill" in $$source)) {
            this["IsReserveByRemoveSkill"] = false;
        }
        if (!("TransferSkillBuffType" in $$source)) {
            this["TransferSkillBuffType"] = 0;
        }
        if (!("Round" in $$source)) {
            this["Round"] = 0;
        }
        if (!("Value" in $$source)) {
            this["Value"] = 0;
        }
        if (!("EndByEffect" in $$source)) {
            this["EndByEffect"] = false;
        }
        if (!("EndType" in $$source)) {
            this["EndType"] = "";
        }
        if (!("IsServerOnly" in $$source)) {
            this["IsServerOnly"] = false;
        }
        if (!("IsCasterOnly" in $$source)) {
            this["IsCasterOnly"] = false;
        }
        if (!("OwnerType" in $$source)) {
            this["OwnerType"] = 0;
        }
        if (!("ShowArea" in $$source)) {
            this["ShowArea"] = "";
        }
        if (!("Icon" in $$source)) {
            this["Icon"] = "";
        }
        if (!("Effect" in $$source)) {
            this["Effect"] = 0;
        }
        if (!("FlashEffect" in $$source)) {
            this["FlashEffect"] = 0;
        }
        if (!("BuffPriority" in $$source)) {
            this["BuffPriority"] = 0;
        }
        if (!("OverlyingType" in $$source)) {
            this["OverlyingType"] = 0;
        }
        if (!("IsTrigger" in $$source)) {
            this["IsTrigger"] = false;
        }
        if (!("BuffState" in $$source)) {
            this["BuffState"] = [];
        }
        if (!("BuffPro" in $$source)) {
            this["BuffPro"] = [];
        }
        if (!("ProValue" in $$source)) {
            this["ProValue"] = [];
        }
        if (!("CostEffectValue" in $$source)) {
            this["CostEffectValue"] = [];
        }
        if (!("TriggerTiming" in $$source)) {
            this["TriggerTiming"] = [];
        }
        if (!("TriggerPriority" in $$source)) {
            this["TriggerPriority"] = [];
        }
        if (!("TriggerCondition" in $$source)) {
            this["TriggerCondition"] = [];
        }
        if (!("TriggerAction" in $$source)) {
            this["TriggerAction"] = [];
        }
        if (!("BuffDot" in $$source)) {
            this["BuffDot"] = 0;
        }
        if (!("EffectDescribe" in $$source)) {
            this["EffectDescribe"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuffDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): BuffDiff {
        const $$createField24_0 = $$createType0;
        const $$createField25_0 = $$createType0;
        const $$createField26_0 = $$createType0;
        const $$createField27_0 = $$createType0;
        const $$createField28_0 = $$createType0;
        const $$createField29_0 = $$createType0;
        const $$createField30_0 = $$createType1;
        const $$createField31_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("BuffState" in $$parsedSource) {
            $$parsedSource["BuffState"] = $$createField24_0($$parsedSource["BuffState"]);
        }
        if ("BuffPro" in $$parsedSource) {
            $$parsedSource["BuffPro"] = $$createField25_0($$parsedSource["BuffPro"]);
        }
        if ("ProValue" in $$parsedSource) {
            $$parsedSource["ProValue"] = $$createField26_0($$parsedSource["ProValue"]);
        }
        if ("CostEffectValue" in $$parsedSource) {
            $$parsedSource["CostEffectValue"] = $$createField27_0($$parsedSource["CostEffectValue"]);
        }
        if ("TriggerTiming" in $$parsedSource) {
            $$parsedSource["TriggerTiming"] = $$createField28_0($$parsedSource["TriggerTiming"]);
        }
        if ("TriggerPriority" in $$parsedSource) {
            $$parsedSource["TriggerPriority"] = $$createField29_0($$parsedSource["TriggerPriority"]);
        }
        if ("TriggerCondition" in $$parsedSource) {
            $$parsedSource["TriggerCondition"] = $$createField30_0($$parsedSource["TriggerCondition"]);
        }
        if ("TriggerAction" in $$parsedSource) {
            $$parsedSource["TriggerAction"] = $$createField31_0($$parsedSource["TriggerAction"]);
        }
        return new BuffDiff($$parsedSource as Partial<BuffDiff>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
