// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mjs_excel$0 from "../mjs_excel/models.js";

export class AudioRepeatInfo {
    "RepeatNum": number;
    "Location": string[];
    "ExistInfos": ExistInfo[];

    /** Creates a new AudioRepeatInfo instance. */
    constructor($$source: Partial<AudioRepeatInfo> = {}) {
        if (!("RepeatNum" in $$source)) {
            this["RepeatNum"] = 0;
        }
        if (!("Location" in $$source)) {
            this["Location"] = [];
        }
        if (!("ExistInfos" in $$source)) {
            this["ExistInfos"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AudioRepeatInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AudioRepeatInfo {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Location" in $$parsedSource) {
            $$parsedSource["Location"] = $$createField1_0($$parsedSource["Location"]);
        }
        if ("ExistInfos" in $$parsedSource) {
            $$parsedSource["ExistInfos"] = $$createField2_0($$parsedSource["ExistInfos"]);
        }
        return new AudioRepeatInfo($$parsedSource as Partial<AudioRepeatInfo>);
    }
}

export class ExistInfo {
    "Path": string;
    "Exist": boolean;
    "Reason": string;

    /** Creates a new ExistInfo instance. */
    constructor($$source: Partial<ExistInfo> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Exist" in $$source)) {
            this["Exist"] = false;
        }
        if (!("Reason" in $$source)) {
            this["Reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExistInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ExistInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExistInfo($$parsedSource as Partial<ExistInfo>);
    }
}

export class LineVoiceRepeatInfo {
    "RepeatNum": number;
    "Location": string[];
    "ExistInfos": ExistInfo[];

    /** Creates a new LineVoiceRepeatInfo instance. */
    constructor($$source: Partial<LineVoiceRepeatInfo> = {}) {
        if (!("RepeatNum" in $$source)) {
            this["RepeatNum"] = 0;
        }
        if (!("Location" in $$source)) {
            this["Location"] = [];
        }
        if (!("ExistInfos" in $$source)) {
            this["ExistInfos"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LineVoiceRepeatInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LineVoiceRepeatInfo {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Location" in $$parsedSource) {
            $$parsedSource["Location"] = $$createField1_0($$parsedSource["Location"]);
        }
        if ("ExistInfos" in $$parsedSource) {
            $$parsedSource["ExistInfos"] = $$createField2_0($$parsedSource["ExistInfos"]);
        }
        return new LineVoiceRepeatInfo($$parsedSource as Partial<LineVoiceRepeatInfo>);
    }
}

export class VoiceCheckReport {
    "ExcelMaps": mjs_excel$0.AudioRefExcel | null;

    /**
     * heroid 台词id 重复信息
     */
    "HeroLineVoiceRepeatVoiceMap": { [_ in `${number}`]?: { [_ in `${number}`]?: LineVoiceRepeatInfo | null } };

    /**
     * heroid 音频枚举 重复信息
     */
    "HeroAudioRepeatVoiceMap": { [_ in `${number}`]?: { [_ in string]?: AudioRepeatInfo | null } };

    /** Creates a new VoiceCheckReport instance. */
    constructor($$source: Partial<VoiceCheckReport> = {}) {
        if (!("ExcelMaps" in $$source)) {
            this["ExcelMaps"] = null;
        }
        if (!("HeroLineVoiceRepeatVoiceMap" in $$source)) {
            this["HeroLineVoiceRepeatVoiceMap"] = {};
        }
        if (!("HeroAudioRepeatVoiceMap" in $$source)) {
            this["HeroAudioRepeatVoiceMap"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VoiceCheckReport instance from a string or object.
     */
    static createFrom($$source: any = {}): VoiceCheckReport {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType8;
        const $$createField2_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ExcelMaps" in $$parsedSource) {
            $$parsedSource["ExcelMaps"] = $$createField0_0($$parsedSource["ExcelMaps"]);
        }
        if ("HeroLineVoiceRepeatVoiceMap" in $$parsedSource) {
            $$parsedSource["HeroLineVoiceRepeatVoiceMap"] = $$createField1_0($$parsedSource["HeroLineVoiceRepeatVoiceMap"]);
        }
        if ("HeroAudioRepeatVoiceMap" in $$parsedSource) {
            $$parsedSource["HeroAudioRepeatVoiceMap"] = $$createField2_0($$parsedSource["HeroAudioRepeatVoiceMap"]);
        }
        return new VoiceCheckReport($$parsedSource as Partial<VoiceCheckReport>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ExistInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = mjs_excel$0.AudioRefExcel.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = LineVoiceRepeatInfo.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Map($Create.Any, $$createType6);
const $$createType8 = $Create.Map($Create.Any, $$createType7);
const $$createType9 = AudioRepeatInfo.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $Create.Map($Create.Any, $$createType10);
const $$createType12 = $Create.Map($Create.Any, $$createType11);
