// Code generated by glog-gen. DO NOT EDIT.
package output

import (
	"os"
	"strings"

	"github.com/brianvoe/gofakeit/v6"
)

func init() {
	gofakeit.Seed(0)
}

// WriteFunc 日志写入函数类型
type WriteFunc func(contents []string)

// DefaultWriter 默认日志写入器
var DefaultWriter WriteFunc = NewFileWriter("log.txt", 1)

// SetDefaultWriter 设置默认日志写入器
func SetDefaultWriter(factory func() WriteFunc) {
	DefaultWriter = factory()
}

// NewFileWriter 创建文件写入器
func NewFileWriter(filePath string, batchSize int) WriteFunc {
	return func(contents []string) {
		f, err := os.OpenFile(filePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
		if err != nil {
			return
		}
		defer f.Close()
		for i := 0; i < len(contents); i += batchSize {
			end := i + batchSize
			if end > len(contents) {
				end = len(contents)
			}
			batch := contents[i:end]
			f.WriteString(strings.Join(batch, "|") + "\n")
		}
	}
}
