// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SkillDiff {
    /**
     * ESkillId类型，使用string
     */
    "Id": string;
    "SkillName": string;
    "ShortSkillName": string;

    /**
     * ESkillId def
     */
    "ESkillId": string;

    /**
     * ESkillType
     */
    "SkillType": string;
    "IsFromOther": boolean;
    "CounterFormula": string;
    "IsFromAura": boolean;

    /**
     * ESkillId
     */
    "TransCard": string;

    /**
     * ESkillFromType
     */
    "SkillFromType": string;

    /**
     * ESkillResetCountType
     */
    "ResetCounterType": string;

    /**
     * ESkillResetCountType
     */
    "ResetTimesType": string;
    "SkillLimitTimes": number;
    "TotalLimitTimes": number;
    "TriggerCondition": number[];

    /**
     * 结构体类型，暂时用string处理
     */
    "SkillEffect": string[];

    /**
     * EEmptyWaitTime
     */
    "EmptyWaitTime": string;

    /**
     * EBuffId[]
     */
    "Buff": string[];
    "ShowPointAndAttr": boolean;

    /**
     * ESkillId[]
     */
    "MutexSkill": string[];

    /**
     * ECardMarkClass
     */
    "BattleCardClass": string;

    /**
     * EAIJudgeArea[]
     */
    "AIJudgeArea": string[];
    "DeadType": number;

    /**
     * {int Pro;int Value}[] 结构体数组
     */
    "InitPro": string[];

    /**
     * ESkillId
     */
    "MagicSkillID": string;
    "IsAutoSelAllOther": boolean;
    "IsForbidCopy": boolean;
    "IsForbidTrans": boolean;
    "IsForbidDestroy": boolean;

    /** Creates a new SkillDiff instance. */
    constructor($$source: Partial<SkillDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("SkillName" in $$source)) {
            this["SkillName"] = "";
        }
        if (!("ShortSkillName" in $$source)) {
            this["ShortSkillName"] = "";
        }
        if (!("ESkillId" in $$source)) {
            this["ESkillId"] = "";
        }
        if (!("SkillType" in $$source)) {
            this["SkillType"] = "";
        }
        if (!("IsFromOther" in $$source)) {
            this["IsFromOther"] = false;
        }
        if (!("CounterFormula" in $$source)) {
            this["CounterFormula"] = "";
        }
        if (!("IsFromAura" in $$source)) {
            this["IsFromAura"] = false;
        }
        if (!("TransCard" in $$source)) {
            this["TransCard"] = "";
        }
        if (!("SkillFromType" in $$source)) {
            this["SkillFromType"] = "";
        }
        if (!("ResetCounterType" in $$source)) {
            this["ResetCounterType"] = "";
        }
        if (!("ResetTimesType" in $$source)) {
            this["ResetTimesType"] = "";
        }
        if (!("SkillLimitTimes" in $$source)) {
            this["SkillLimitTimes"] = 0;
        }
        if (!("TotalLimitTimes" in $$source)) {
            this["TotalLimitTimes"] = 0;
        }
        if (!("TriggerCondition" in $$source)) {
            this["TriggerCondition"] = [];
        }
        if (!("SkillEffect" in $$source)) {
            this["SkillEffect"] = [];
        }
        if (!("EmptyWaitTime" in $$source)) {
            this["EmptyWaitTime"] = "";
        }
        if (!("Buff" in $$source)) {
            this["Buff"] = [];
        }
        if (!("ShowPointAndAttr" in $$source)) {
            this["ShowPointAndAttr"] = false;
        }
        if (!("MutexSkill" in $$source)) {
            this["MutexSkill"] = [];
        }
        if (!("BattleCardClass" in $$source)) {
            this["BattleCardClass"] = "";
        }
        if (!("AIJudgeArea" in $$source)) {
            this["AIJudgeArea"] = [];
        }
        if (!("DeadType" in $$source)) {
            this["DeadType"] = 0;
        }
        if (!("InitPro" in $$source)) {
            this["InitPro"] = [];
        }
        if (!("MagicSkillID" in $$source)) {
            this["MagicSkillID"] = "";
        }
        if (!("IsAutoSelAllOther" in $$source)) {
            this["IsAutoSelAllOther"] = false;
        }
        if (!("IsForbidCopy" in $$source)) {
            this["IsForbidCopy"] = false;
        }
        if (!("IsForbidTrans" in $$source)) {
            this["IsForbidTrans"] = false;
        }
        if (!("IsForbidDestroy" in $$source)) {
            this["IsForbidDestroy"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillDiff {
        const $$createField14_0 = $$createType0;
        const $$createField15_0 = $$createType1;
        const $$createField17_0 = $$createType1;
        const $$createField19_0 = $$createType1;
        const $$createField21_0 = $$createType1;
        const $$createField23_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("TriggerCondition" in $$parsedSource) {
            $$parsedSource["TriggerCondition"] = $$createField14_0($$parsedSource["TriggerCondition"]);
        }
        if ("SkillEffect" in $$parsedSource) {
            $$parsedSource["SkillEffect"] = $$createField15_0($$parsedSource["SkillEffect"]);
        }
        if ("Buff" in $$parsedSource) {
            $$parsedSource["Buff"] = $$createField17_0($$parsedSource["Buff"]);
        }
        if ("MutexSkill" in $$parsedSource) {
            $$parsedSource["MutexSkill"] = $$createField19_0($$parsedSource["MutexSkill"]);
        }
        if ("AIJudgeArea" in $$parsedSource) {
            $$parsedSource["AIJudgeArea"] = $$createField21_0($$parsedSource["AIJudgeArea"]);
        }
        if ("InitPro" in $$parsedSource) {
            $$parsedSource["InitPro"] = $$createField23_0($$parsedSource["InitPro"]);
        }
        return new SkillDiff($$parsedSource as Partial<SkillDiff>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
