// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AchieveDetailInfo {
    /**
     * 成就id
     */
    "Id": number;

    /**
     * 成就名称
     */
    "Name": string;

    /**
     * 是否隐藏
     */
    "IsHide": boolean;

    /**
     * 成就完成条件
     */
    "CompleteCondId": number;

    /**
     * 成就奖励
     */
    "Reward": string[];

    /**
     * 空列
     */
    "None": string;

    /**
     * 成就描述
     */
    "Des": string;

    /**
     * 成就完成条件
     */
    "Condition": string;

    /**
     * 成就完成条件
     */
    "ConditionInfo": TaskCompleteConditionInfo | null;

    /**
     * 关联武将ID
     */
    "HeroItemId": number[];

    /**
     * 开放时间
     */
    "OpenDate": string;

    /** Creates a new AchieveDetailInfo instance. */
    constructor($$source: Partial<AchieveDetailInfo> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("IsHide" in $$source)) {
            this["IsHide"] = false;
        }
        if (!("CompleteCondId" in $$source)) {
            this["CompleteCondId"] = 0;
        }
        if (!("Reward" in $$source)) {
            this["Reward"] = [];
        }
        if (!("None" in $$source)) {
            this["None"] = "";
        }
        if (!("Des" in $$source)) {
            this["Des"] = "";
        }
        if (!("Condition" in $$source)) {
            this["Condition"] = "";
        }
        if (!("ConditionInfo" in $$source)) {
            this["ConditionInfo"] = null;
        }
        if (!("HeroItemId" in $$source)) {
            this["HeroItemId"] = [];
        }
        if (!("OpenDate" in $$source)) {
            this["OpenDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AchieveDetailInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AchieveDetailInfo {
        const $$createField4_0 = $$createType0;
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Reward" in $$parsedSource) {
            $$parsedSource["Reward"] = $$createField4_0($$parsedSource["Reward"]);
        }
        if ("ConditionInfo" in $$parsedSource) {
            $$parsedSource["ConditionInfo"] = $$createField8_0($$parsedSource["ConditionInfo"]);
        }
        if ("HeroItemId" in $$parsedSource) {
            $$parsedSource["HeroItemId"] = $$createField9_0($$parsedSource["HeroItemId"]);
        }
        return new AchieveDetailInfo($$parsedSource as Partial<AchieveDetailInfo>);
    }
}

/**
 * BuffInfo 技能基础信息
 */
export class BuffInfo {
    "Id": string;
    "EBuffId": string;
    "Name": string;
    "NeedRecord": boolean;
    "BuffType": number;
    "IsDeleteByCasterDead": boolean;
    "IsDeleteByExecutorDead": boolean;
    "IsValidByFengJin": boolean;
    "IsReserveByRemoveSkill": boolean;
    "TransferSkillBuffType": number;
    "Round": number;
    "Value": number;
    "EndByEffect": boolean;
    "EndType": string;
    "IsServerOnly": boolean;
    "IsCasterOnly": boolean;
    "OwnerType": number;
    "ShowArea": string;
    "Icon": string;
    "Effect": number;
    "FlashEffect": number;
    "BuffPriority": number;
    "OverlyingType": number;
    "IsTrigger": boolean;
    "BuffState": number[];
    "BuffPro": number[];
    "ProValue": number[];
    "CostEffectValue": number[];
    "TriggerTiming": number[];
    "TriggerPriority": number[];
    "TriggerCondition": string[];
    "TriggerAction": number[];
    "BuffDot": number;
    "EffectDescribe": string;

    /** Creates a new BuffInfo instance. */
    constructor($$source: Partial<BuffInfo> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("EBuffId" in $$source)) {
            this["EBuffId"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("NeedRecord" in $$source)) {
            this["NeedRecord"] = false;
        }
        if (!("BuffType" in $$source)) {
            this["BuffType"] = 0;
        }
        if (!("IsDeleteByCasterDead" in $$source)) {
            this["IsDeleteByCasterDead"] = false;
        }
        if (!("IsDeleteByExecutorDead" in $$source)) {
            this["IsDeleteByExecutorDead"] = false;
        }
        if (!("IsValidByFengJin" in $$source)) {
            this["IsValidByFengJin"] = false;
        }
        if (!("IsReserveByRemoveSkill" in $$source)) {
            this["IsReserveByRemoveSkill"] = false;
        }
        if (!("TransferSkillBuffType" in $$source)) {
            this["TransferSkillBuffType"] = 0;
        }
        if (!("Round" in $$source)) {
            this["Round"] = 0;
        }
        if (!("Value" in $$source)) {
            this["Value"] = 0;
        }
        if (!("EndByEffect" in $$source)) {
            this["EndByEffect"] = false;
        }
        if (!("EndType" in $$source)) {
            this["EndType"] = "";
        }
        if (!("IsServerOnly" in $$source)) {
            this["IsServerOnly"] = false;
        }
        if (!("IsCasterOnly" in $$source)) {
            this["IsCasterOnly"] = false;
        }
        if (!("OwnerType" in $$source)) {
            this["OwnerType"] = 0;
        }
        if (!("ShowArea" in $$source)) {
            this["ShowArea"] = "";
        }
        if (!("Icon" in $$source)) {
            this["Icon"] = "";
        }
        if (!("Effect" in $$source)) {
            this["Effect"] = 0;
        }
        if (!("FlashEffect" in $$source)) {
            this["FlashEffect"] = 0;
        }
        if (!("BuffPriority" in $$source)) {
            this["BuffPriority"] = 0;
        }
        if (!("OverlyingType" in $$source)) {
            this["OverlyingType"] = 0;
        }
        if (!("IsTrigger" in $$source)) {
            this["IsTrigger"] = false;
        }
        if (!("BuffState" in $$source)) {
            this["BuffState"] = [];
        }
        if (!("BuffPro" in $$source)) {
            this["BuffPro"] = [];
        }
        if (!("ProValue" in $$source)) {
            this["ProValue"] = [];
        }
        if (!("CostEffectValue" in $$source)) {
            this["CostEffectValue"] = [];
        }
        if (!("TriggerTiming" in $$source)) {
            this["TriggerTiming"] = [];
        }
        if (!("TriggerPriority" in $$source)) {
            this["TriggerPriority"] = [];
        }
        if (!("TriggerCondition" in $$source)) {
            this["TriggerCondition"] = [];
        }
        if (!("TriggerAction" in $$source)) {
            this["TriggerAction"] = [];
        }
        if (!("BuffDot" in $$source)) {
            this["BuffDot"] = 0;
        }
        if (!("EffectDescribe" in $$source)) {
            this["EffectDescribe"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuffInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BuffInfo {
        const $$createField24_0 = $$createType3;
        const $$createField25_0 = $$createType3;
        const $$createField26_0 = $$createType3;
        const $$createField27_0 = $$createType3;
        const $$createField28_0 = $$createType3;
        const $$createField29_0 = $$createType3;
        const $$createField30_0 = $$createType0;
        const $$createField31_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("BuffState" in $$parsedSource) {
            $$parsedSource["BuffState"] = $$createField24_0($$parsedSource["BuffState"]);
        }
        if ("BuffPro" in $$parsedSource) {
            $$parsedSource["BuffPro"] = $$createField25_0($$parsedSource["BuffPro"]);
        }
        if ("ProValue" in $$parsedSource) {
            $$parsedSource["ProValue"] = $$createField26_0($$parsedSource["ProValue"]);
        }
        if ("CostEffectValue" in $$parsedSource) {
            $$parsedSource["CostEffectValue"] = $$createField27_0($$parsedSource["CostEffectValue"]);
        }
        if ("TriggerTiming" in $$parsedSource) {
            $$parsedSource["TriggerTiming"] = $$createField28_0($$parsedSource["TriggerTiming"]);
        }
        if ("TriggerPriority" in $$parsedSource) {
            $$parsedSource["TriggerPriority"] = $$createField29_0($$parsedSource["TriggerPriority"]);
        }
        if ("TriggerCondition" in $$parsedSource) {
            $$parsedSource["TriggerCondition"] = $$createField30_0($$parsedSource["TriggerCondition"]);
        }
        if ("TriggerAction" in $$parsedSource) {
            $$parsedSource["TriggerAction"] = $$createField31_0($$parsedSource["TriggerAction"]);
        }
        return new BuffInfo($$parsedSource as Partial<BuffInfo>);
    }
}

/**
 * CountryInfo 国家信息
 */
export class CountryInfo {
    "ECountry": string;
    "Name": string;
    "KingName": string;
    "SeatFlagImagePath": string;
    "PlayerInfoFlagImagePath": string;
    "PlayerInfoFlagTextPath": string;
    "IsWhiteBg": boolean;
    "IsOpen": boolean;
    "NameArtSelectedFontPath": string;
    "NameArtUnselectedFontPath": string;
    "ShiLiSmallTopIcon": string;
    "ShiLiSmallBottomIcon": string;
    "SortPriority": number;
    "GuildIcon": string;

    /**
     * 该国家的武将
     */
    "Heroes": string[];

    /** Creates a new CountryInfo instance. */
    constructor($$source: Partial<CountryInfo> = {}) {
        if (!("ECountry" in $$source)) {
            this["ECountry"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("KingName" in $$source)) {
            this["KingName"] = "";
        }
        if (!("SeatFlagImagePath" in $$source)) {
            this["SeatFlagImagePath"] = "";
        }
        if (!("PlayerInfoFlagImagePath" in $$source)) {
            this["PlayerInfoFlagImagePath"] = "";
        }
        if (!("PlayerInfoFlagTextPath" in $$source)) {
            this["PlayerInfoFlagTextPath"] = "";
        }
        if (!("IsWhiteBg" in $$source)) {
            this["IsWhiteBg"] = false;
        }
        if (!("IsOpen" in $$source)) {
            this["IsOpen"] = false;
        }
        if (!("NameArtSelectedFontPath" in $$source)) {
            this["NameArtSelectedFontPath"] = "";
        }
        if (!("NameArtUnselectedFontPath" in $$source)) {
            this["NameArtUnselectedFontPath"] = "";
        }
        if (!("ShiLiSmallTopIcon" in $$source)) {
            this["ShiLiSmallTopIcon"] = "";
        }
        if (!("ShiLiSmallBottomIcon" in $$source)) {
            this["ShiLiSmallBottomIcon"] = "";
        }
        if (!("SortPriority" in $$source)) {
            this["SortPriority"] = 0;
        }
        if (!("GuildIcon" in $$source)) {
            this["GuildIcon"] = "";
        }
        if (!("Heroes" in $$source)) {
            this["Heroes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CountryInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CountryInfo {
        const $$createField14_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Heroes" in $$parsedSource) {
            $$parsedSource["Heroes"] = $$createField14_0($$parsedSource["Heroes"]);
        }
        return new CountryInfo($$parsedSource as Partial<CountryInfo>);
    }
}

/**
 * DropGroupSummary 掉落组摘要
 */
export class DropGroupSummary {
    "GroupId": number;
    "GroupName": string;
    "Weight": number;
    "WeightInc": number;
    "Deduplicate": boolean;
    "ValidDate": string;
    "ExpireDate": string;

    /**
     * 该掉落组中涉及此武将的具体掉落项
     */
    "DropItems": (HeroDropItem | null)[];

    /** Creates a new DropGroupSummary instance. */
    constructor($$source: Partial<DropGroupSummary> = {}) {
        if (!("GroupId" in $$source)) {
            this["GroupId"] = 0;
        }
        if (!("GroupName" in $$source)) {
            this["GroupName"] = "";
        }
        if (!("Weight" in $$source)) {
            this["Weight"] = 0;
        }
        if (!("WeightInc" in $$source)) {
            this["WeightInc"] = 0;
        }
        if (!("Deduplicate" in $$source)) {
            this["Deduplicate"] = false;
        }
        if (!("ValidDate" in $$source)) {
            this["ValidDate"] = "";
        }
        if (!("ExpireDate" in $$source)) {
            this["ExpireDate"] = "";
        }
        if (!("DropItems" in $$source)) {
            this["DropItems"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DropGroupSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): DropGroupSummary {
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("DropItems" in $$parsedSource) {
            $$parsedSource["DropItems"] = $$createField7_0($$parsedSource["DropItems"]);
        }
        return new DropGroupSummary($$parsedSource as Partial<DropGroupSummary>);
    }
}

/**
 * DropRuleSummary 掉落规则摘要
 */
export class DropRuleSummary {
    "RuleId": number;
    "RuleName": string;
    "DropCount": number;

    /**
     * 关联的掉落组ID列表
     */
    "DropGroups": number[];

    /**
     * 是否是保底掉落
     */
    "IsGuarantee": boolean;

    /** Creates a new DropRuleSummary instance. */
    constructor($$source: Partial<DropRuleSummary> = {}) {
        if (!("RuleId" in $$source)) {
            this["RuleId"] = 0;
        }
        if (!("RuleName" in $$source)) {
            this["RuleName"] = "";
        }
        if (!("DropCount" in $$source)) {
            this["DropCount"] = 0;
        }
        if (!("DropGroups" in $$source)) {
            this["DropGroups"] = [];
        }
        if (!("IsGuarantee" in $$source)) {
            this["IsGuarantee"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DropRuleSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): DropRuleSummary {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("DropGroups" in $$parsedSource) {
            $$parsedSource["DropGroups"] = $$createField3_0($$parsedSource["DropGroups"]);
        }
        return new DropRuleSummary($$parsedSource as Partial<DropRuleSummary>);
    }
}

/**
 * DropTypeInfo 按类型分类的掉落信息
 */
export class DropTypeInfo {
    "TypeName": string;
    "DropRules": (DropRuleSummary | null)[];
    "TotalCount": number;

    /** Creates a new DropTypeInfo instance. */
    constructor($$source: Partial<DropTypeInfo> = {}) {
        if (!("TypeName" in $$source)) {
            this["TypeName"] = "";
        }
        if (!("DropRules" in $$source)) {
            this["DropRules"] = [];
        }
        if (!("TotalCount" in $$source)) {
            this["TotalCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DropTypeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DropTypeInfo {
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("DropRules" in $$parsedSource) {
            $$parsedSource["DropRules"] = $$createField1_0($$parsedSource["DropRules"]);
        }
        return new DropTypeInfo($$parsedSource as Partial<DropTypeInfo>);
    }
}

export class HeroAchieveInfo {
    /**
     * 局内成就类型 (E#HeroAchieve)
     */
    "Id": string;

    /**
     * 成就名称
     */
    "Name": string;

    /**
     * 是否复用
     */
    "IsMult": boolean;

    /**
     * 房间模式
     */
    "Mode": number[];

    /**
     * 房间人数
     */
    "MinPlayerNum": number;

    /**
     * 使用英雄 (E#HeroId列表)
     */
    "UseHero": string[];

    /**
     * 身份类型
     */
    "Class": number;

    /**
     * 阵营
     */
    "Camp": number;

    /**
     * 身份
     */
    "Identity": number;

    /**
     * 对应钩子
     */
    "Hooker": number[];

    /**
     * 对应钩子
     */
    "HookerTarget": number[];

    /**
     * 条件一
     */
    "CondParam": number[];

    /** Creates a new HeroAchieveInfo instance. */
    constructor($$source: Partial<HeroAchieveInfo> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("IsMult" in $$source)) {
            this["IsMult"] = false;
        }
        if (!("Mode" in $$source)) {
            this["Mode"] = [];
        }
        if (!("MinPlayerNum" in $$source)) {
            this["MinPlayerNum"] = 0;
        }
        if (!("UseHero" in $$source)) {
            this["UseHero"] = [];
        }
        if (!("Class" in $$source)) {
            this["Class"] = 0;
        }
        if (!("Camp" in $$source)) {
            this["Camp"] = 0;
        }
        if (!("Identity" in $$source)) {
            this["Identity"] = 0;
        }
        if (!("Hooker" in $$source)) {
            this["Hooker"] = [];
        }
        if (!("HookerTarget" in $$source)) {
            this["HookerTarget"] = [];
        }
        if (!("CondParam" in $$source)) {
            this["CondParam"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroAchieveInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroAchieveInfo {
        const $$createField3_0 = $$createType3;
        const $$createField5_0 = $$createType0;
        const $$createField9_0 = $$createType3;
        const $$createField10_0 = $$createType3;
        const $$createField11_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mode" in $$parsedSource) {
            $$parsedSource["Mode"] = $$createField3_0($$parsedSource["Mode"]);
        }
        if ("UseHero" in $$parsedSource) {
            $$parsedSource["UseHero"] = $$createField5_0($$parsedSource["UseHero"]);
        }
        if ("Hooker" in $$parsedSource) {
            $$parsedSource["Hooker"] = $$createField9_0($$parsedSource["Hooker"]);
        }
        if ("HookerTarget" in $$parsedSource) {
            $$parsedSource["HookerTarget"] = $$createField10_0($$parsedSource["HookerTarget"]);
        }
        if ("CondParam" in $$parsedSource) {
            $$parsedSource["CondParam"] = $$createField11_0($$parsedSource["CondParam"]);
        }
        return new HeroAchieveInfo($$parsedSource as Partial<HeroAchieveInfo>);
    }
}

/**
 * HeroAchievementInfo 武将成就信息
 */
export class HeroAchievementInfo {
    "HeroAchieve": HeroAchieveInfo | null;
    "AchieveDetail": AchieveDetailInfo | null;

    /** Creates a new HeroAchievementInfo instance. */
    constructor($$source: Partial<HeroAchievementInfo> = {}) {
        if (!("HeroAchieve" in $$source)) {
            this["HeroAchieve"] = null;
        }
        if (!("AchieveDetail" in $$source)) {
            this["AchieveDetail"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroAchievementInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroAchievementInfo {
        const $$createField0_0 = $$createType11;
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("HeroAchieve" in $$parsedSource) {
            $$parsedSource["HeroAchieve"] = $$createField0_0($$parsedSource["HeroAchieve"]);
        }
        if ("AchieveDetail" in $$parsedSource) {
            $$parsedSource["AchieveDetail"] = $$createField1_0($$parsedSource["AchieveDetail"]);
        }
        return new HeroAchievementInfo($$parsedSource as Partial<HeroAchievementInfo>);
    }
}

/**
 * HeroBasicInfo 武将基础信息
 */
export class HeroBasicInfo {
    "Id": number;
    "EHeroId": string;
    "Name": string;
    "IsOpen": boolean;
    "OpenDate": string;
    "Gender": number;
    "Point": number;
    "HpLimit": number;
    "HandLimit": number;
    "EquipLimit": number;
    "Country": string;
    "IsAlwaysZhuGong": boolean;
    "ExcludeIdentity": number[];
    "NotUseModeType": number[];
    "HeroType": number;
    "EHeroType": string;
    "CanMelt": boolean;
    "MeltName": string[];
    "IsNewHero": boolean;
    "IsGacha": boolean;
    "BelongExpansionPack": string;

    /** Creates a new HeroBasicInfo instance. */
    constructor($$source: Partial<HeroBasicInfo> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("EHeroId" in $$source)) {
            this["EHeroId"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("IsOpen" in $$source)) {
            this["IsOpen"] = false;
        }
        if (!("OpenDate" in $$source)) {
            this["OpenDate"] = "";
        }
        if (!("Gender" in $$source)) {
            this["Gender"] = 0;
        }
        if (!("Point" in $$source)) {
            this["Point"] = 0;
        }
        if (!("HpLimit" in $$source)) {
            this["HpLimit"] = 0;
        }
        if (!("HandLimit" in $$source)) {
            this["HandLimit"] = 0;
        }
        if (!("EquipLimit" in $$source)) {
            this["EquipLimit"] = 0;
        }
        if (!("Country" in $$source)) {
            this["Country"] = "";
        }
        if (!("IsAlwaysZhuGong" in $$source)) {
            this["IsAlwaysZhuGong"] = false;
        }
        if (!("ExcludeIdentity" in $$source)) {
            this["ExcludeIdentity"] = [];
        }
        if (!("NotUseModeType" in $$source)) {
            this["NotUseModeType"] = [];
        }
        if (!("HeroType" in $$source)) {
            this["HeroType"] = 0;
        }
        if (!("EHeroType" in $$source)) {
            this["EHeroType"] = "";
        }
        if (!("CanMelt" in $$source)) {
            this["CanMelt"] = false;
        }
        if (!("MeltName" in $$source)) {
            this["MeltName"] = [];
        }
        if (!("IsNewHero" in $$source)) {
            this["IsNewHero"] = false;
        }
        if (!("IsGacha" in $$source)) {
            this["IsGacha"] = false;
        }
        if (!("BelongExpansionPack" in $$source)) {
            this["BelongExpansionPack"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroBasicInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroBasicInfo {
        const $$createField12_0 = $$createType3;
        const $$createField13_0 = $$createType3;
        const $$createField17_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ExcludeIdentity" in $$parsedSource) {
            $$parsedSource["ExcludeIdentity"] = $$createField12_0($$parsedSource["ExcludeIdentity"]);
        }
        if ("NotUseModeType" in $$parsedSource) {
            $$parsedSource["NotUseModeType"] = $$createField13_0($$parsedSource["NotUseModeType"]);
        }
        if ("MeltName" in $$parsedSource) {
            $$parsedSource["MeltName"] = $$createField17_0($$parsedSource["MeltName"]);
        }
        return new HeroBasicInfo($$parsedSource as Partial<HeroBasicInfo>);
    }
}

/**
 * HeroCompleteData 单个武将的完整数据
 */
export class HeroCompleteData {
    /**
     * 基础信息
     */
    "Basic": HeroBasicInfo | null;

    /**
     * UI相关信息
     */
    "UI": HeroUIInfo | null;

    /**
     * 皮肤集合
     */
    "Skins": (HeroSkinInfo | null)[];

    /**
     * 技能集合
     */
    "Skills": (HeroSkillInfo | null)[];

    /**
     * 所属国家
     */
    "Country": CountryInfo | null;

    /**
     * 推荐布阵
     */
    "RecommendBd": RecommendBdInfo | null;

    /**
     * 成就
     */
    "Achievements": (HeroAchievementInfo | null)[];

    /**
     * 机器人行为
     */
    "RobotActions": (RobotActionInfo | null)[];

    /**
     * 掉落相关信息
     */
    "DropInfo": HeroDropInfo | null;

    /** Creates a new HeroCompleteData instance. */
    constructor($$source: Partial<HeroCompleteData> = {}) {
        if (!("Basic" in $$source)) {
            this["Basic"] = null;
        }
        if (!("UI" in $$source)) {
            this["UI"] = null;
        }
        if (!("Skins" in $$source)) {
            this["Skins"] = [];
        }
        if (!("Skills" in $$source)) {
            this["Skills"] = [];
        }
        if (!("Country" in $$source)) {
            this["Country"] = null;
        }
        if (!("RecommendBd" in $$source)) {
            this["RecommendBd"] = null;
        }
        if (!("Achievements" in $$source)) {
            this["Achievements"] = [];
        }
        if (!("RobotActions" in $$source)) {
            this["RobotActions"] = [];
        }
        if (!("DropInfo" in $$source)) {
            this["DropInfo"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroCompleteData instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroCompleteData {
        const $$createField0_0 = $$createType15;
        const $$createField1_0 = $$createType17;
        const $$createField2_0 = $$createType20;
        const $$createField3_0 = $$createType23;
        const $$createField4_0 = $$createType25;
        const $$createField5_0 = $$createType27;
        const $$createField6_0 = $$createType30;
        const $$createField7_0 = $$createType33;
        const $$createField8_0 = $$createType35;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Basic" in $$parsedSource) {
            $$parsedSource["Basic"] = $$createField0_0($$parsedSource["Basic"]);
        }
        if ("UI" in $$parsedSource) {
            $$parsedSource["UI"] = $$createField1_0($$parsedSource["UI"]);
        }
        if ("Skins" in $$parsedSource) {
            $$parsedSource["Skins"] = $$createField2_0($$parsedSource["Skins"]);
        }
        if ("Skills" in $$parsedSource) {
            $$parsedSource["Skills"] = $$createField3_0($$parsedSource["Skills"]);
        }
        if ("Country" in $$parsedSource) {
            $$parsedSource["Country"] = $$createField4_0($$parsedSource["Country"]);
        }
        if ("RecommendBd" in $$parsedSource) {
            $$parsedSource["RecommendBd"] = $$createField5_0($$parsedSource["RecommendBd"]);
        }
        if ("Achievements" in $$parsedSource) {
            $$parsedSource["Achievements"] = $$createField6_0($$parsedSource["Achievements"]);
        }
        if ("RobotActions" in $$parsedSource) {
            $$parsedSource["RobotActions"] = $$createField7_0($$parsedSource["RobotActions"]);
        }
        if ("DropInfo" in $$parsedSource) {
            $$parsedSource["DropInfo"] = $$createField8_0($$parsedSource["DropInfo"]);
        }
        return new HeroCompleteData($$parsedSource as Partial<HeroCompleteData>);
    }
}

/**
 * HeroDropInfo 武将掉落相关信息
 */
export class HeroDropInfo {
    /**
     * 武将直接掉落的规则
     */
    "DirectDropRules": (DropRuleSummary | null)[];

    /**
     * 武将作为保底/特殊掉落的规则
     */
    "GuaranteeDropRules": (DropRuleSummary | null)[];

    /**
     * 武将所在的所有掉落组
     */
    "DropGroups": (DropGroupSummary | null)[];

    /**
     * 按掉落类型分类
     */
    "ByDropType": { [_ in string]?: DropTypeInfo | null };

    /** Creates a new HeroDropInfo instance. */
    constructor($$source: Partial<HeroDropInfo> = {}) {
        if (!("DirectDropRules" in $$source)) {
            this["DirectDropRules"] = [];
        }
        if (!("GuaranteeDropRules" in $$source)) {
            this["GuaranteeDropRules"] = [];
        }
        if (!("DropGroups" in $$source)) {
            this["DropGroups"] = [];
        }
        if (!("ByDropType" in $$source)) {
            this["ByDropType"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroDropInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroDropInfo {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType9;
        const $$createField2_0 = $$createType38;
        const $$createField3_0 = $$createType41;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("DirectDropRules" in $$parsedSource) {
            $$parsedSource["DirectDropRules"] = $$createField0_0($$parsedSource["DirectDropRules"]);
        }
        if ("GuaranteeDropRules" in $$parsedSource) {
            $$parsedSource["GuaranteeDropRules"] = $$createField1_0($$parsedSource["GuaranteeDropRules"]);
        }
        if ("DropGroups" in $$parsedSource) {
            $$parsedSource["DropGroups"] = $$createField2_0($$parsedSource["DropGroups"]);
        }
        if ("ByDropType" in $$parsedSource) {
            $$parsedSource["ByDropType"] = $$createField3_0($$parsedSource["ByDropType"]);
        }
        return new HeroDropInfo($$parsedSource as Partial<HeroDropInfo>);
    }
}

/**
 * HeroDropItem 武将掉落项
 */
export class HeroDropItem {
    "ItemId": number;
    "ItemName": string;
    "DropGroupId": number;

    /**
     * 掉落物品信息
     */
    "ItemConfigs": (ItemConfig | null)[];
    "Weight": number;
    "WeightInc": number;
    "Deduplicate": boolean;
    "CheckExist": boolean;
    "ExcludeExist": boolean;
    "MustHave": boolean;
    "ReplaceGroup": number;
    "ValidDate": string;
    "ExpireDate": string;

    /** Creates a new HeroDropItem instance. */
    constructor($$source: Partial<HeroDropItem> = {}) {
        if (!("ItemId" in $$source)) {
            this["ItemId"] = 0;
        }
        if (!("ItemName" in $$source)) {
            this["ItemName"] = "";
        }
        if (!("DropGroupId" in $$source)) {
            this["DropGroupId"] = 0;
        }
        if (!("ItemConfigs" in $$source)) {
            this["ItemConfigs"] = [];
        }
        if (!("Weight" in $$source)) {
            this["Weight"] = 0;
        }
        if (!("WeightInc" in $$source)) {
            this["WeightInc"] = 0;
        }
        if (!("Deduplicate" in $$source)) {
            this["Deduplicate"] = false;
        }
        if (!("CheckExist" in $$source)) {
            this["CheckExist"] = false;
        }
        if (!("ExcludeExist" in $$source)) {
            this["ExcludeExist"] = false;
        }
        if (!("MustHave" in $$source)) {
            this["MustHave"] = false;
        }
        if (!("ReplaceGroup" in $$source)) {
            this["ReplaceGroup"] = 0;
        }
        if (!("ValidDate" in $$source)) {
            this["ValidDate"] = "";
        }
        if (!("ExpireDate" in $$source)) {
            this["ExpireDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroDropItem instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroDropItem {
        const $$createField3_0 = $$createType44;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ItemConfigs" in $$parsedSource) {
            $$parsedSource["ItemConfigs"] = $$createField3_0($$parsedSource["ItemConfigs"]);
        }
        return new HeroDropItem($$parsedSource as Partial<HeroDropItem>);
    }
}

/**
 * HeroIndexes 索引映射
 */
export class HeroIndexes {
    /**
     * ID索引
     * HeroDiff.Id -> EHeroId
     */
    "HeroByID": { [_ in `${number}`]?: string };

    /**
     * EHeroId -> HeroDiff.Id
     */
    "HeroByEHeroId": { [_ in string]?: number };

    /**
     * 皮肤索引
     * HeroId -> []SkinItemId
     */
    "SkinsByHeroId": { [_ in string]?: number[] };

    /**
     * SkinItemId -> []LineId
     */
    "LinesBySkinId": { [_ in `${number}`]?: number[] };

    /**
     * 技能索引
     */
    "ESkillBySkillId": { [_ in `${number}`]?: string };

    /**
     * HeroId -> []SkillId
     */
    "SkillsByHeroId": { [_ in string]?: string[] };

    /**
     * SkillId -> []LineId
     */
    "LinesBySkillId": { [_ in string]?: number[] };

    /**
     * buff索引
     */
    "BuffIdByEBuffId": { [_ in string]?: string };

    /**
     * 国家索引
     * Country -> []HeroId
     */
    "HeroesByCountry": { [_ in string]?: string[] };

    /**
     * 成就索引
     * HeroId -> []AchieveId
     */
    "AchieveHeroesByHeroId": { [_ in string]?: string[] };

    /**
     * HeroId -> 去掉开头10为HeroItemId -> []AchieveId
     */
    "AchieveByHeroId": { [_ in string]?: number[] };

    /** Creates a new HeroIndexes instance. */
    constructor($$source: Partial<HeroIndexes> = {}) {
        if (!("HeroByID" in $$source)) {
            this["HeroByID"] = {};
        }
        if (!("HeroByEHeroId" in $$source)) {
            this["HeroByEHeroId"] = {};
        }
        if (!("SkinsByHeroId" in $$source)) {
            this["SkinsByHeroId"] = {};
        }
        if (!("LinesBySkinId" in $$source)) {
            this["LinesBySkinId"] = {};
        }
        if (!("ESkillBySkillId" in $$source)) {
            this["ESkillBySkillId"] = {};
        }
        if (!("SkillsByHeroId" in $$source)) {
            this["SkillsByHeroId"] = {};
        }
        if (!("LinesBySkillId" in $$source)) {
            this["LinesBySkillId"] = {};
        }
        if (!("BuffIdByEBuffId" in $$source)) {
            this["BuffIdByEBuffId"] = {};
        }
        if (!("HeroesByCountry" in $$source)) {
            this["HeroesByCountry"] = {};
        }
        if (!("AchieveHeroesByHeroId" in $$source)) {
            this["AchieveHeroesByHeroId"] = {};
        }
        if (!("AchieveByHeroId" in $$source)) {
            this["AchieveByHeroId"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroIndexes instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroIndexes {
        const $$createField0_0 = $$createType45;
        const $$createField1_0 = $$createType46;
        const $$createField2_0 = $$createType47;
        const $$createField3_0 = $$createType48;
        const $$createField4_0 = $$createType45;
        const $$createField5_0 = $$createType49;
        const $$createField6_0 = $$createType47;
        const $$createField7_0 = $$createType50;
        const $$createField8_0 = $$createType49;
        const $$createField9_0 = $$createType49;
        const $$createField10_0 = $$createType47;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("HeroByID" in $$parsedSource) {
            $$parsedSource["HeroByID"] = $$createField0_0($$parsedSource["HeroByID"]);
        }
        if ("HeroByEHeroId" in $$parsedSource) {
            $$parsedSource["HeroByEHeroId"] = $$createField1_0($$parsedSource["HeroByEHeroId"]);
        }
        if ("SkinsByHeroId" in $$parsedSource) {
            $$parsedSource["SkinsByHeroId"] = $$createField2_0($$parsedSource["SkinsByHeroId"]);
        }
        if ("LinesBySkinId" in $$parsedSource) {
            $$parsedSource["LinesBySkinId"] = $$createField3_0($$parsedSource["LinesBySkinId"]);
        }
        if ("ESkillBySkillId" in $$parsedSource) {
            $$parsedSource["ESkillBySkillId"] = $$createField4_0($$parsedSource["ESkillBySkillId"]);
        }
        if ("SkillsByHeroId" in $$parsedSource) {
            $$parsedSource["SkillsByHeroId"] = $$createField5_0($$parsedSource["SkillsByHeroId"]);
        }
        if ("LinesBySkillId" in $$parsedSource) {
            $$parsedSource["LinesBySkillId"] = $$createField6_0($$parsedSource["LinesBySkillId"]);
        }
        if ("BuffIdByEBuffId" in $$parsedSource) {
            $$parsedSource["BuffIdByEBuffId"] = $$createField7_0($$parsedSource["BuffIdByEBuffId"]);
        }
        if ("HeroesByCountry" in $$parsedSource) {
            $$parsedSource["HeroesByCountry"] = $$createField8_0($$parsedSource["HeroesByCountry"]);
        }
        if ("AchieveHeroesByHeroId" in $$parsedSource) {
            $$parsedSource["AchieveHeroesByHeroId"] = $$createField9_0($$parsedSource["AchieveHeroesByHeroId"]);
        }
        if ("AchieveByHeroId" in $$parsedSource) {
            $$parsedSource["AchieveByHeroId"] = $$createField10_0($$parsedSource["AchieveByHeroId"]);
        }
        return new HeroIndexes($$parsedSource as Partial<HeroIndexes>);
    }
}

/**
 * HeroLineInfo 台词信息
 */
export class HeroLineInfo {
    "Id": number;
    "Type": string;
    "TabName": string;
    "Text": string;
    "AudioId": string;
    "Achievements": number[];
    "GroupId": string;

    /** Creates a new HeroLineInfo instance. */
    constructor($$source: Partial<HeroLineInfo> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("Type" in $$source)) {
            this["Type"] = "";
        }
        if (!("TabName" in $$source)) {
            this["TabName"] = "";
        }
        if (!("Text" in $$source)) {
            this["Text"] = "";
        }
        if (!("AudioId" in $$source)) {
            this["AudioId"] = "";
        }
        if (!("Achievements" in $$source)) {
            this["Achievements"] = [];
        }
        if (!("GroupId" in $$source)) {
            this["GroupId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroLineInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroLineInfo {
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Achievements" in $$parsedSource) {
            $$parsedSource["Achievements"] = $$createField5_0($$parsedSource["Achievements"]);
        }
        return new HeroLineInfo($$parsedSource as Partial<HeroLineInfo>);
    }
}

/**
 * HeroSkillInfo 技能信息
 */
export class HeroSkillInfo {
    /**
     * 技能基础
     */
    "Basic": SkillBasicInfo | null;

    /**
     * 技能UI
     */
    "UI": SkillUIInfo | null;

    /**
     * 技能熔炼
     */
    "Melt": SkillMeltInfo | null;

    /**
     * 技能台词
     */
    "Lines": (SkillLineInfo | null)[];

    /**
     * 技能标签
     */
    "Tags": (SkillTagInfo | null)[];

    /** Creates a new HeroSkillInfo instance. */
    constructor($$source: Partial<HeroSkillInfo> = {}) {
        if (!("Basic" in $$source)) {
            this["Basic"] = null;
        }
        if (!("UI" in $$source)) {
            this["UI"] = null;
        }
        if (!("Melt" in $$source)) {
            this["Melt"] = null;
        }
        if (!("Lines" in $$source)) {
            this["Lines"] = [];
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroSkillInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroSkillInfo {
        const $$createField0_0 = $$createType52;
        const $$createField1_0 = $$createType54;
        const $$createField2_0 = $$createType56;
        const $$createField3_0 = $$createType59;
        const $$createField4_0 = $$createType62;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Basic" in $$parsedSource) {
            $$parsedSource["Basic"] = $$createField0_0($$parsedSource["Basic"]);
        }
        if ("UI" in $$parsedSource) {
            $$parsedSource["UI"] = $$createField1_0($$parsedSource["UI"]);
        }
        if ("Melt" in $$parsedSource) {
            $$parsedSource["Melt"] = $$createField2_0($$parsedSource["Melt"]);
        }
        if ("Lines" in $$parsedSource) {
            $$parsedSource["Lines"] = $$createField3_0($$parsedSource["Lines"]);
        }
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField4_0($$parsedSource["Tags"]);
        }
        return new HeroSkillInfo($$parsedSource as Partial<HeroSkillInfo>);
    }
}

/**
 * HeroSkinCollectionInfo 皮肤收藏册信息
 */
export class HeroSkinCollectionInfo {
    "Type": string;
    "Name": string;
    "NameImg": string;
    "NameBg": string;
    "Desc": string;
    "Weight": number;
    "OpenDate": string;

    /** Creates a new HeroSkinCollectionInfo instance. */
    constructor($$source: Partial<HeroSkinCollectionInfo> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("NameImg" in $$source)) {
            this["NameImg"] = "";
        }
        if (!("NameBg" in $$source)) {
            this["NameBg"] = "";
        }
        if (!("Desc" in $$source)) {
            this["Desc"] = "";
        }
        if (!("Weight" in $$source)) {
            this["Weight"] = 0;
        }
        if (!("OpenDate" in $$source)) {
            this["OpenDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroSkinCollectionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroSkinCollectionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HeroSkinCollectionInfo($$parsedSource as Partial<HeroSkinCollectionInfo>);
    }
}

/**
 * HeroSkinInfo 武将皮肤信息
 */
export class HeroSkinInfo {
    /**
     * 皮肤基础
     */
    "ItemId": number;
    "HeroId": string;
    "Name": string;
    "GetWay": string;
    "SkinPinYin": string;
    "SkinType": string;
    "RailType": string;

    /**
     * 皮肤UI
     */
    "SeatSpecialImg": string;
    "HeroUIExtraIcons": string[];
    "OriginalArtDesigner": string;
    "CollectionType": string;
    "IsOpen": boolean;
    "OpenDate": string;
    "CollectionTagImg": string;
    "KillShowTime": number;
    "BodyOffset": number[];
    "HasOutFrameIcon": boolean;

    /**
     * 皮肤Spine
     */
    "Spine": HeroSkinSpineInfo | null;

    /**
     * 皮肤资源
     */
    "Resource": HeroSkinResourceInfo | null;

    /**
     * 皮肤台词
     */
    "LinesDubbed": string;
    "Lines": (HeroLineInfo | null)[];

    /**
     * 收藏册
     */
    "Collection": HeroSkinCollectionInfo | null;

    /** Creates a new HeroSkinInfo instance. */
    constructor($$source: Partial<HeroSkinInfo> = {}) {
        if (!("ItemId" in $$source)) {
            this["ItemId"] = 0;
        }
        if (!("HeroId" in $$source)) {
            this["HeroId"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("GetWay" in $$source)) {
            this["GetWay"] = "";
        }
        if (!("SkinPinYin" in $$source)) {
            this["SkinPinYin"] = "";
        }
        if (!("SkinType" in $$source)) {
            this["SkinType"] = "";
        }
        if (!("RailType" in $$source)) {
            this["RailType"] = "";
        }
        if (!("SeatSpecialImg" in $$source)) {
            this["SeatSpecialImg"] = "";
        }
        if (!("HeroUIExtraIcons" in $$source)) {
            this["HeroUIExtraIcons"] = [];
        }
        if (!("OriginalArtDesigner" in $$source)) {
            this["OriginalArtDesigner"] = "";
        }
        if (!("CollectionType" in $$source)) {
            this["CollectionType"] = "";
        }
        if (!("IsOpen" in $$source)) {
            this["IsOpen"] = false;
        }
        if (!("OpenDate" in $$source)) {
            this["OpenDate"] = "";
        }
        if (!("CollectionTagImg" in $$source)) {
            this["CollectionTagImg"] = "";
        }
        if (!("KillShowTime" in $$source)) {
            this["KillShowTime"] = 0;
        }
        if (!("BodyOffset" in $$source)) {
            this["BodyOffset"] = [];
        }
        if (!("HasOutFrameIcon" in $$source)) {
            this["HasOutFrameIcon"] = false;
        }
        if (!("Spine" in $$source)) {
            this["Spine"] = null;
        }
        if (!("Resource" in $$source)) {
            this["Resource"] = null;
        }
        if (!("LinesDubbed" in $$source)) {
            this["LinesDubbed"] = "";
        }
        if (!("Lines" in $$source)) {
            this["Lines"] = [];
        }
        if (!("Collection" in $$source)) {
            this["Collection"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroSkinInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroSkinInfo {
        const $$createField8_0 = $$createType0;
        const $$createField15_0 = $$createType3;
        const $$createField17_0 = $$createType64;
        const $$createField18_0 = $$createType66;
        const $$createField20_0 = $$createType69;
        const $$createField21_0 = $$createType71;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("HeroUIExtraIcons" in $$parsedSource) {
            $$parsedSource["HeroUIExtraIcons"] = $$createField8_0($$parsedSource["HeroUIExtraIcons"]);
        }
        if ("BodyOffset" in $$parsedSource) {
            $$parsedSource["BodyOffset"] = $$createField15_0($$parsedSource["BodyOffset"]);
        }
        if ("Spine" in $$parsedSource) {
            $$parsedSource["Spine"] = $$createField17_0($$parsedSource["Spine"]);
        }
        if ("Resource" in $$parsedSource) {
            $$parsedSource["Resource"] = $$createField18_0($$parsedSource["Resource"]);
        }
        if ("Lines" in $$parsedSource) {
            $$parsedSource["Lines"] = $$createField20_0($$parsedSource["Lines"]);
        }
        if ("Collection" in $$parsedSource) {
            $$parsedSource["Collection"] = $$createField21_0($$parsedSource["Collection"]);
        }
        return new HeroSkinInfo($$parsedSource as Partial<HeroSkinInfo>);
    }
}

/**
 * HeroSkinResourceInfo 皮肤资源信息
 */
export class HeroSkinResourceInfo {
    "SkinItemId": number;
    "Path": string;

    /** Creates a new HeroSkinResourceInfo instance. */
    constructor($$source: Partial<HeroSkinResourceInfo> = {}) {
        if (!("SkinItemId" in $$source)) {
            this["SkinItemId"] = 0;
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroSkinResourceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroSkinResourceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HeroSkinResourceInfo($$parsedSource as Partial<HeroSkinResourceInfo>);
    }
}

/**
 * HeroSkinSpineInfo 皮肤Spine信息
 */
export class HeroSkinSpineInfo {
    "SkinItemId": number;
    "IsHasSeatSpine": boolean;
    "IsHasBookSpine": boolean;
    "IsHasMainBgSpine": boolean;
    "MainBgFx": string;
    "IsHasSeatKillSpine": boolean;
    "KillFxId": number;
    "IsHasCollectionBgSpine": boolean;
    "IsHasCollectionCardBgSpine": boolean;
    "SpineAnimAudio": string;
    "IsHasCollectionCardBgSpineDuplicate": boolean;
    "KillAudio": string;

    /** Creates a new HeroSkinSpineInfo instance. */
    constructor($$source: Partial<HeroSkinSpineInfo> = {}) {
        if (!("SkinItemId" in $$source)) {
            this["SkinItemId"] = 0;
        }
        if (!("IsHasSeatSpine" in $$source)) {
            this["IsHasSeatSpine"] = false;
        }
        if (!("IsHasBookSpine" in $$source)) {
            this["IsHasBookSpine"] = false;
        }
        if (!("IsHasMainBgSpine" in $$source)) {
            this["IsHasMainBgSpine"] = false;
        }
        if (!("MainBgFx" in $$source)) {
            this["MainBgFx"] = "";
        }
        if (!("IsHasSeatKillSpine" in $$source)) {
            this["IsHasSeatKillSpine"] = false;
        }
        if (!("KillFxId" in $$source)) {
            this["KillFxId"] = 0;
        }
        if (!("IsHasCollectionBgSpine" in $$source)) {
            this["IsHasCollectionBgSpine"] = false;
        }
        if (!("IsHasCollectionCardBgSpine" in $$source)) {
            this["IsHasCollectionCardBgSpine"] = false;
        }
        if (!("SpineAnimAudio" in $$source)) {
            this["SpineAnimAudio"] = "";
        }
        if (!("IsHasCollectionCardBgSpineDuplicate" in $$source)) {
            this["IsHasCollectionCardBgSpineDuplicate"] = false;
        }
        if (!("KillAudio" in $$source)) {
            this["KillAudio"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroSkinSpineInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroSkinSpineInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HeroSkinSpineInfo($$parsedSource as Partial<HeroSkinSpineInfo>);
    }
}

/**
 * HeroUIInfo 武将UI信息
 */
export class HeroUIInfo {
    "HeroDiffId": number;
    "Name": string;
    "VoiceType": number;
    "BelongExpansionPack": string;
    "AwardDes": string;
    "LongIntroduction": string;
    "ShortIntroduction": string;
    "Evidence": string;
    "Evaluation": string;
    "IsNew": boolean;
    "CopyWriter": string;
    "SkillDesigner": string;
    "GetWay": string;
    "Position": string;
    "ExclusiveCard": number[];
    "NewbieShowSkillTag": number[];
    "WinningRateIn2v2": number;
    "WinRateShowPriority": number;

    /** Creates a new HeroUIInfo instance. */
    constructor($$source: Partial<HeroUIInfo> = {}) {
        if (!("HeroDiffId" in $$source)) {
            this["HeroDiffId"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("VoiceType" in $$source)) {
            this["VoiceType"] = 0;
        }
        if (!("BelongExpansionPack" in $$source)) {
            this["BelongExpansionPack"] = "";
        }
        if (!("AwardDes" in $$source)) {
            this["AwardDes"] = "";
        }
        if (!("LongIntroduction" in $$source)) {
            this["LongIntroduction"] = "";
        }
        if (!("ShortIntroduction" in $$source)) {
            this["ShortIntroduction"] = "";
        }
        if (!("Evidence" in $$source)) {
            this["Evidence"] = "";
        }
        if (!("Evaluation" in $$source)) {
            this["Evaluation"] = "";
        }
        if (!("IsNew" in $$source)) {
            this["IsNew"] = false;
        }
        if (!("CopyWriter" in $$source)) {
            this["CopyWriter"] = "";
        }
        if (!("SkillDesigner" in $$source)) {
            this["SkillDesigner"] = "";
        }
        if (!("GetWay" in $$source)) {
            this["GetWay"] = "";
        }
        if (!("Position" in $$source)) {
            this["Position"] = "";
        }
        if (!("ExclusiveCard" in $$source)) {
            this["ExclusiveCard"] = [];
        }
        if (!("NewbieShowSkillTag" in $$source)) {
            this["NewbieShowSkillTag"] = [];
        }
        if (!("WinningRateIn2v2" in $$source)) {
            this["WinningRateIn2v2"] = 0;
        }
        if (!("WinRateShowPriority" in $$source)) {
            this["WinRateShowPriority"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroUIInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroUIInfo {
        const $$createField14_0 = $$createType3;
        const $$createField15_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ExclusiveCard" in $$parsedSource) {
            $$parsedSource["ExclusiveCard"] = $$createField14_0($$parsedSource["ExclusiveCard"]);
        }
        if ("NewbieShowSkillTag" in $$parsedSource) {
            $$parsedSource["NewbieShowSkillTag"] = $$createField15_0($$parsedSource["NewbieShowSkillTag"]);
        }
        return new HeroUIInfo($$parsedSource as Partial<HeroUIInfo>);
    }
}

/**
 * HeroWikiDiff 整合所有武将相关数据
 */
export class HeroWikiDiff {
    /**
     * 索引映射，用于快速查找
     */
    "Indexes": HeroIndexes | null;

    /**
     * 按武将ID组织的完整数据
     */
    "Heroes": { [_ in string]?: HeroCompleteData | null };

    /** Creates a new HeroWikiDiff instance. */
    constructor($$source: Partial<HeroWikiDiff> = {}) {
        if (!("Indexes" in $$source)) {
            this["Indexes"] = null;
        }
        if (!("Heroes" in $$source)) {
            this["Heroes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroWikiDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroWikiDiff {
        const $$createField0_0 = $$createType73;
        const $$createField1_0 = $$createType76;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Indexes" in $$parsedSource) {
            $$parsedSource["Indexes"] = $$createField0_0($$parsedSource["Indexes"]);
        }
        if ("Heroes" in $$parsedSource) {
            $$parsedSource["Heroes"] = $$createField1_0($$parsedSource["Heroes"]);
        }
        return new HeroWikiDiff($$parsedSource as Partial<HeroWikiDiff>);
    }
}

/**
 * ItemConfig 物品配置
 */
export class ItemConfig {
    /**
     * 物品ID
     */
    "ItemId": number;

    /**
     * 数量
     */
    "Count": number;

    /**
     * 是否是武将
     */
    "IsHero": boolean;

    /**
     * 如果是武将，对应的EHeroId
     */
    "HeroId": string;

    /** Creates a new ItemConfig instance. */
    constructor($$source: Partial<ItemConfig> = {}) {
        if (!("ItemId" in $$source)) {
            this["ItemId"] = 0;
        }
        if (!("Count" in $$source)) {
            this["Count"] = 0;
        }
        if (!("IsHero" in $$source)) {
            this["IsHero"] = false;
        }
        if (!("HeroId" in $$source)) {
            this["HeroId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ItemConfig($$parsedSource as Partial<ItemConfig>);
    }
}

/**
 * RecommendBdInfo 推荐布阵信息
 */
export class RecommendBdInfo {
    "HeroId": string;
    "Level1": string[];
    "Level2": string[];
    "Level3": string[];
    "Level4": string[];
    "Level5": string[];
    "Level6": string[];

    /** Creates a new RecommendBdInfo instance. */
    constructor($$source: Partial<RecommendBdInfo> = {}) {
        if (!("HeroId" in $$source)) {
            this["HeroId"] = "";
        }
        if (!("Level1" in $$source)) {
            this["Level1"] = [];
        }
        if (!("Level2" in $$source)) {
            this["Level2"] = [];
        }
        if (!("Level3" in $$source)) {
            this["Level3"] = [];
        }
        if (!("Level4" in $$source)) {
            this["Level4"] = [];
        }
        if (!("Level5" in $$source)) {
            this["Level5"] = [];
        }
        if (!("Level6" in $$source)) {
            this["Level6"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecommendBdInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RecommendBdInfo {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Level1" in $$parsedSource) {
            $$parsedSource["Level1"] = $$createField1_0($$parsedSource["Level1"]);
        }
        if ("Level2" in $$parsedSource) {
            $$parsedSource["Level2"] = $$createField2_0($$parsedSource["Level2"]);
        }
        if ("Level3" in $$parsedSource) {
            $$parsedSource["Level3"] = $$createField3_0($$parsedSource["Level3"]);
        }
        if ("Level4" in $$parsedSource) {
            $$parsedSource["Level4"] = $$createField4_0($$parsedSource["Level4"]);
        }
        if ("Level5" in $$parsedSource) {
            $$parsedSource["Level5"] = $$createField5_0($$parsedSource["Level5"]);
        }
        if ("Level6" in $$parsedSource) {
            $$parsedSource["Level6"] = $$createField6_0($$parsedSource["Level6"]);
        }
        return new RecommendBdInfo($$parsedSource as Partial<RecommendBdInfo>);
    }
}

/**
 * RobotActionInfo 机器人行为信息
 */
export class RobotActionInfo {
    "Id": string;
    "Action": string[];
    "TargetNum": number[];
    "TargetType": string[];
    "CardNum": number[];
    "CardFromType": string[];
    "TransCardSkill": number[];
    "DefaultCardSkill": number[];

    /** Creates a new RobotActionInfo instance. */
    constructor($$source: Partial<RobotActionInfo> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Action" in $$source)) {
            this["Action"] = [];
        }
        if (!("TargetNum" in $$source)) {
            this["TargetNum"] = [];
        }
        if (!("TargetType" in $$source)) {
            this["TargetType"] = [];
        }
        if (!("CardNum" in $$source)) {
            this["CardNum"] = [];
        }
        if (!("CardFromType" in $$source)) {
            this["CardFromType"] = [];
        }
        if (!("TransCardSkill" in $$source)) {
            this["TransCardSkill"] = [];
        }
        if (!("DefaultCardSkill" in $$source)) {
            this["DefaultCardSkill"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RobotActionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RobotActionInfo {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType3;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Action" in $$parsedSource) {
            $$parsedSource["Action"] = $$createField1_0($$parsedSource["Action"]);
        }
        if ("TargetNum" in $$parsedSource) {
            $$parsedSource["TargetNum"] = $$createField2_0($$parsedSource["TargetNum"]);
        }
        if ("TargetType" in $$parsedSource) {
            $$parsedSource["TargetType"] = $$createField3_0($$parsedSource["TargetType"]);
        }
        if ("CardNum" in $$parsedSource) {
            $$parsedSource["CardNum"] = $$createField4_0($$parsedSource["CardNum"]);
        }
        if ("CardFromType" in $$parsedSource) {
            $$parsedSource["CardFromType"] = $$createField5_0($$parsedSource["CardFromType"]);
        }
        if ("TransCardSkill" in $$parsedSource) {
            $$parsedSource["TransCardSkill"] = $$createField6_0($$parsedSource["TransCardSkill"]);
        }
        if ("DefaultCardSkill" in $$parsedSource) {
            $$parsedSource["DefaultCardSkill"] = $$createField7_0($$parsedSource["DefaultCardSkill"]);
        }
        return new RobotActionInfo($$parsedSource as Partial<RobotActionInfo>);
    }
}

/**
 * SkillBasicInfo 技能基础信息
 */
export class SkillBasicInfo {
    "Id": string;
    "SkillName": string;
    "ShortSkillName": string;
    "ESkillId": string;
    "SkillType": string;
    "IsFromOther": boolean;
    "CounterFormula": string;
    "IsFromAura": boolean;
    "TransCard": string;
    "SkillFromType": string;
    "ResetCounterType": string;
    "ResetTimesType": string;
    "SkillLimitTimes": number;
    "TotalLimitTimes": number;
    "TriggerCondition": number[];
    "SkillEffect": string[];
    "EmptyWaitTime": string;
    "Buff": (BuffInfo | null)[];
    "ShowPointAndAttr": boolean;
    "MutexSkill": string[];
    "BattleCardClass": string;
    "AIJudgeArea": string[];
    "DeadType": number;
    "InitPro": string[];
    "MagicSkillID": string;
    "IsAutoSelAllOther": boolean;
    "IsForbidCopy": boolean;
    "IsForbidTrans": boolean;
    "IsForbidDestroy": boolean;

    /** Creates a new SkillBasicInfo instance. */
    constructor($$source: Partial<SkillBasicInfo> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("SkillName" in $$source)) {
            this["SkillName"] = "";
        }
        if (!("ShortSkillName" in $$source)) {
            this["ShortSkillName"] = "";
        }
        if (!("ESkillId" in $$source)) {
            this["ESkillId"] = "";
        }
        if (!("SkillType" in $$source)) {
            this["SkillType"] = "";
        }
        if (!("IsFromOther" in $$source)) {
            this["IsFromOther"] = false;
        }
        if (!("CounterFormula" in $$source)) {
            this["CounterFormula"] = "";
        }
        if (!("IsFromAura" in $$source)) {
            this["IsFromAura"] = false;
        }
        if (!("TransCard" in $$source)) {
            this["TransCard"] = "";
        }
        if (!("SkillFromType" in $$source)) {
            this["SkillFromType"] = "";
        }
        if (!("ResetCounterType" in $$source)) {
            this["ResetCounterType"] = "";
        }
        if (!("ResetTimesType" in $$source)) {
            this["ResetTimesType"] = "";
        }
        if (!("SkillLimitTimes" in $$source)) {
            this["SkillLimitTimes"] = 0;
        }
        if (!("TotalLimitTimes" in $$source)) {
            this["TotalLimitTimes"] = 0;
        }
        if (!("TriggerCondition" in $$source)) {
            this["TriggerCondition"] = [];
        }
        if (!("SkillEffect" in $$source)) {
            this["SkillEffect"] = [];
        }
        if (!("EmptyWaitTime" in $$source)) {
            this["EmptyWaitTime"] = "";
        }
        if (!("Buff" in $$source)) {
            this["Buff"] = [];
        }
        if (!("ShowPointAndAttr" in $$source)) {
            this["ShowPointAndAttr"] = false;
        }
        if (!("MutexSkill" in $$source)) {
            this["MutexSkill"] = [];
        }
        if (!("BattleCardClass" in $$source)) {
            this["BattleCardClass"] = "";
        }
        if (!("AIJudgeArea" in $$source)) {
            this["AIJudgeArea"] = [];
        }
        if (!("DeadType" in $$source)) {
            this["DeadType"] = 0;
        }
        if (!("InitPro" in $$source)) {
            this["InitPro"] = [];
        }
        if (!("MagicSkillID" in $$source)) {
            this["MagicSkillID"] = "";
        }
        if (!("IsAutoSelAllOther" in $$source)) {
            this["IsAutoSelAllOther"] = false;
        }
        if (!("IsForbidCopy" in $$source)) {
            this["IsForbidCopy"] = false;
        }
        if (!("IsForbidTrans" in $$source)) {
            this["IsForbidTrans"] = false;
        }
        if (!("IsForbidDestroy" in $$source)) {
            this["IsForbidDestroy"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillBasicInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillBasicInfo {
        const $$createField14_0 = $$createType3;
        const $$createField15_0 = $$createType0;
        const $$createField17_0 = $$createType79;
        const $$createField19_0 = $$createType0;
        const $$createField21_0 = $$createType0;
        const $$createField23_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("TriggerCondition" in $$parsedSource) {
            $$parsedSource["TriggerCondition"] = $$createField14_0($$parsedSource["TriggerCondition"]);
        }
        if ("SkillEffect" in $$parsedSource) {
            $$parsedSource["SkillEffect"] = $$createField15_0($$parsedSource["SkillEffect"]);
        }
        if ("Buff" in $$parsedSource) {
            $$parsedSource["Buff"] = $$createField17_0($$parsedSource["Buff"]);
        }
        if ("MutexSkill" in $$parsedSource) {
            $$parsedSource["MutexSkill"] = $$createField19_0($$parsedSource["MutexSkill"]);
        }
        if ("AIJudgeArea" in $$parsedSource) {
            $$parsedSource["AIJudgeArea"] = $$createField21_0($$parsedSource["AIJudgeArea"]);
        }
        if ("InitPro" in $$parsedSource) {
            $$parsedSource["InitPro"] = $$createField23_0($$parsedSource["InitPro"]);
        }
        return new SkillBasicInfo($$parsedSource as Partial<SkillBasicInfo>);
    }
}

/**
 * SkillLineInfo 技能台词信息
 */
export class SkillLineInfo {
    "Id": number;
    "SkillId": string;
    "SkinId": number;
    "SkillFirstLine": number[];
    "SkillSecondLine": number[];
    "SkillThirdLine": number[];
    "SkillForthLine": number[];
    "SpecialAudio": string;

    /** Creates a new SkillLineInfo instance. */
    constructor($$source: Partial<SkillLineInfo> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("SkillId" in $$source)) {
            this["SkillId"] = "";
        }
        if (!("SkinId" in $$source)) {
            this["SkinId"] = 0;
        }
        if (!("SkillFirstLine" in $$source)) {
            this["SkillFirstLine"] = [];
        }
        if (!("SkillSecondLine" in $$source)) {
            this["SkillSecondLine"] = [];
        }
        if (!("SkillThirdLine" in $$source)) {
            this["SkillThirdLine"] = [];
        }
        if (!("SkillForthLine" in $$source)) {
            this["SkillForthLine"] = [];
        }
        if (!("SpecialAudio" in $$source)) {
            this["SpecialAudio"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillLineInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillLineInfo {
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("SkillFirstLine" in $$parsedSource) {
            $$parsedSource["SkillFirstLine"] = $$createField3_0($$parsedSource["SkillFirstLine"]);
        }
        if ("SkillSecondLine" in $$parsedSource) {
            $$parsedSource["SkillSecondLine"] = $$createField4_0($$parsedSource["SkillSecondLine"]);
        }
        if ("SkillThirdLine" in $$parsedSource) {
            $$parsedSource["SkillThirdLine"] = $$createField5_0($$parsedSource["SkillThirdLine"]);
        }
        if ("SkillForthLine" in $$parsedSource) {
            $$parsedSource["SkillForthLine"] = $$createField6_0($$parsedSource["SkillForthLine"]);
        }
        return new SkillLineInfo($$parsedSource as Partial<SkillLineInfo>);
    }
}

/**
 * SkillMeltInfo 技能熔炼信息
 */
export class SkillMeltInfo {
    "Id": string;
    "MeltPower": number;
    "CanMelt": boolean;

    /** Creates a new SkillMeltInfo instance. */
    constructor($$source: Partial<SkillMeltInfo> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("MeltPower" in $$source)) {
            this["MeltPower"] = 0;
        }
        if (!("CanMelt" in $$source)) {
            this["CanMelt"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillMeltInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillMeltInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillMeltInfo($$parsedSource as Partial<SkillMeltInfo>);
    }
}

/**
 * SkillTagInfo 技能标签信息
 */
export class SkillTagInfo {
    "SkillTag": string;
    "TagName": string;
    "TagColor": string;
    "TagDes": string;

    /** Creates a new SkillTagInfo instance. */
    constructor($$source: Partial<SkillTagInfo> = {}) {
        if (!("SkillTag" in $$source)) {
            this["SkillTag"] = "";
        }
        if (!("TagName" in $$source)) {
            this["TagName"] = "";
        }
        if (!("TagColor" in $$source)) {
            this["TagColor"] = "";
        }
        if (!("TagDes" in $$source)) {
            this["TagDes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillTagInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillTagInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillTagInfo($$parsedSource as Partial<SkillTagInfo>);
    }
}

/**
 * SkillUIInfo 技能UI信息
 */
export class SkillUIInfo {
    "Id": string;
    "SkillName": string;
    "PlayCardAudio": string;
    "IdentityLine": string[];
    "Audio": number[];
    "SkillText": string;
    "ShortSkillText": string;
    "KeyWords": number[];
    "SettlementDes": string;
    "Allusion": string;
    "DesignThought": string;
    "SkillTag": number[];
    "BattleSkillStep": string[];
    "HasRelation": boolean;
    "RelatedSkill": string[];
    "SpecialAudio": string;
    "ESkillId": string;
    "EAudio": string;
    "EAudioId": string;
    "ESkillTag": string;

    /** Creates a new SkillUIInfo instance. */
    constructor($$source: Partial<SkillUIInfo> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("SkillName" in $$source)) {
            this["SkillName"] = "";
        }
        if (!("PlayCardAudio" in $$source)) {
            this["PlayCardAudio"] = "";
        }
        if (!("IdentityLine" in $$source)) {
            this["IdentityLine"] = [];
        }
        if (!("Audio" in $$source)) {
            this["Audio"] = [];
        }
        if (!("SkillText" in $$source)) {
            this["SkillText"] = "";
        }
        if (!("ShortSkillText" in $$source)) {
            this["ShortSkillText"] = "";
        }
        if (!("KeyWords" in $$source)) {
            this["KeyWords"] = [];
        }
        if (!("SettlementDes" in $$source)) {
            this["SettlementDes"] = "";
        }
        if (!("Allusion" in $$source)) {
            this["Allusion"] = "";
        }
        if (!("DesignThought" in $$source)) {
            this["DesignThought"] = "";
        }
        if (!("SkillTag" in $$source)) {
            this["SkillTag"] = [];
        }
        if (!("BattleSkillStep" in $$source)) {
            this["BattleSkillStep"] = [];
        }
        if (!("HasRelation" in $$source)) {
            this["HasRelation"] = false;
        }
        if (!("RelatedSkill" in $$source)) {
            this["RelatedSkill"] = [];
        }
        if (!("SpecialAudio" in $$source)) {
            this["SpecialAudio"] = "";
        }
        if (!("ESkillId" in $$source)) {
            this["ESkillId"] = "";
        }
        if (!("EAudio" in $$source)) {
            this["EAudio"] = "";
        }
        if (!("EAudioId" in $$source)) {
            this["EAudioId"] = "";
        }
        if (!("ESkillTag" in $$source)) {
            this["ESkillTag"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillUIInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillUIInfo {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType3;
        const $$createField7_0 = $$createType3;
        const $$createField11_0 = $$createType3;
        const $$createField12_0 = $$createType0;
        const $$createField14_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("IdentityLine" in $$parsedSource) {
            $$parsedSource["IdentityLine"] = $$createField3_0($$parsedSource["IdentityLine"]);
        }
        if ("Audio" in $$parsedSource) {
            $$parsedSource["Audio"] = $$createField4_0($$parsedSource["Audio"]);
        }
        if ("KeyWords" in $$parsedSource) {
            $$parsedSource["KeyWords"] = $$createField7_0($$parsedSource["KeyWords"]);
        }
        if ("SkillTag" in $$parsedSource) {
            $$parsedSource["SkillTag"] = $$createField11_0($$parsedSource["SkillTag"]);
        }
        if ("BattleSkillStep" in $$parsedSource) {
            $$parsedSource["BattleSkillStep"] = $$createField12_0($$parsedSource["BattleSkillStep"]);
        }
        if ("RelatedSkill" in $$parsedSource) {
            $$parsedSource["RelatedSkill"] = $$createField14_0($$parsedSource["RelatedSkill"]);
        }
        return new SkillUIInfo($$parsedSource as Partial<SkillUIInfo>);
    }
}

export class TaskCompleteConditionInfo {
    "Id": number;
    "CondDes": string;
    "CompleteCond": string;
    "CompleteCondParam": number[];
    "JumpCond": string;
    "JumpParm": number[];

    /** Creates a new TaskCompleteConditionInfo instance. */
    constructor($$source: Partial<TaskCompleteConditionInfo> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("CondDes" in $$source)) {
            this["CondDes"] = "";
        }
        if (!("CompleteCond" in $$source)) {
            this["CompleteCond"] = "";
        }
        if (!("CompleteCondParam" in $$source)) {
            this["CompleteCondParam"] = [];
        }
        if (!("JumpCond" in $$source)) {
            this["JumpCond"] = "";
        }
        if (!("JumpParm" in $$source)) {
            this["JumpParm"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskCompleteConditionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskCompleteConditionInfo {
        const $$createField3_0 = $$createType3;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CompleteCondParam" in $$parsedSource) {
            $$parsedSource["CompleteCondParam"] = $$createField3_0($$parsedSource["CompleteCondParam"]);
        }
        if ("JumpParm" in $$parsedSource) {
            $$parsedSource["JumpParm"] = $$createField5_0($$parsedSource["JumpParm"]);
        }
        return new TaskCompleteConditionInfo($$parsedSource as Partial<TaskCompleteConditionInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = TaskCompleteConditionInfo.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = HeroDropItem.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = DropRuleSummary.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = HeroAchieveInfo.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = AchieveDetailInfo.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = HeroBasicInfo.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = HeroUIInfo.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = HeroSkinInfo.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = HeroSkillInfo.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = CountryInfo.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = RecommendBdInfo.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = HeroAchievementInfo.createFrom;
const $$createType29 = $Create.Nullable($$createType28);
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = RobotActionInfo.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = HeroDropInfo.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
const $$createType36 = DropGroupSummary.createFrom;
const $$createType37 = $Create.Nullable($$createType36);
const $$createType38 = $Create.Array($$createType37);
const $$createType39 = DropTypeInfo.createFrom;
const $$createType40 = $Create.Nullable($$createType39);
const $$createType41 = $Create.Map($Create.Any, $$createType40);
const $$createType42 = ItemConfig.createFrom;
const $$createType43 = $Create.Nullable($$createType42);
const $$createType44 = $Create.Array($$createType43);
const $$createType45 = $Create.Map($Create.Any, $Create.Any);
const $$createType46 = $Create.Map($Create.Any, $Create.Any);
const $$createType47 = $Create.Map($Create.Any, $$createType3);
const $$createType48 = $Create.Map($Create.Any, $$createType3);
const $$createType49 = $Create.Map($Create.Any, $$createType0);
const $$createType50 = $Create.Map($Create.Any, $Create.Any);
const $$createType51 = SkillBasicInfo.createFrom;
const $$createType52 = $Create.Nullable($$createType51);
const $$createType53 = SkillUIInfo.createFrom;
const $$createType54 = $Create.Nullable($$createType53);
const $$createType55 = SkillMeltInfo.createFrom;
const $$createType56 = $Create.Nullable($$createType55);
const $$createType57 = SkillLineInfo.createFrom;
const $$createType58 = $Create.Nullable($$createType57);
const $$createType59 = $Create.Array($$createType58);
const $$createType60 = SkillTagInfo.createFrom;
const $$createType61 = $Create.Nullable($$createType60);
const $$createType62 = $Create.Array($$createType61);
const $$createType63 = HeroSkinSpineInfo.createFrom;
const $$createType64 = $Create.Nullable($$createType63);
const $$createType65 = HeroSkinResourceInfo.createFrom;
const $$createType66 = $Create.Nullable($$createType65);
const $$createType67 = HeroLineInfo.createFrom;
const $$createType68 = $Create.Nullable($$createType67);
const $$createType69 = $Create.Array($$createType68);
const $$createType70 = HeroSkinCollectionInfo.createFrom;
const $$createType71 = $Create.Nullable($$createType70);
const $$createType72 = HeroIndexes.createFrom;
const $$createType73 = $Create.Nullable($$createType72);
const $$createType74 = HeroCompleteData.createFrom;
const $$createType75 = $Create.Nullable($$createType74);
const $$createType76 = $Create.Map($Create.Any, $$createType75);
const $$createType77 = BuffInfo.createFrom;
const $$createType78 = $Create.Nullable($$createType77);
const $$createType79 = $Create.Array($$createType78);
