// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExcelConfigService 统一策划配表目录配置服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig 获取当前统一策划配表目录配置
 * @frontend @mcp
 */
export function GetConfig(): $CancellablePromise<$models.ExcelConfig | null> {
    return $Call.ByID(1297699346).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetConfigFilePath 获取配置文件路径
 * @frontend
 */
export function GetConfigFilePath(): $CancellablePromise<string> {
    return $Call.ByID(1941239683);
}

/**
 * ResetToDefault 重置为默认配置
 * @frontend @mcp
 */
export function ResetToDefault(): $CancellablePromise<$models.ExcelConfig | null> {
    return $Call.ByID(3696668431).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveConfig 保存统一策划配表目录配置
 * @frontend @mcp
 */
export function SaveConfig(config: $models.ExcelConfig | null): $CancellablePromise<void> {
    return $Call.ByID(3581922567, config);
}

/**
 * UpdateConfig 部分更新统一策划配表目录配置
 * @frontend @mcp
 */
export function UpdateConfig(updates: { [_ in string]?: any }): $CancellablePromise<$models.ExcelConfig | null> {
    return $Call.ByID(4164986843, updates).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ExcelConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
