// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MCPConfigService MCP 配置管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig 获取当前配置
 * @frontend @mcp
 */
export function GetConfig(): $CancellablePromise<$models.MCPConfig | null> {
    return $Call.ByID(4074094407).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetConfigFilePath 获取配置文件路径
 */
export function GetConfigFilePath(): $CancellablePromise<string> {
    return $Call.ByID(545124898);
}

/**
 * GetConnectionCount 获取当前连接数
 */
export function GetConnectionCount(): $CancellablePromise<number> {
    return $Call.ByID(3383267392);
}

/**
 * GetMCPStatus 获取 MCP 服务状态
 * @mcp
 */
export function GetMCPStatus(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2091985717).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetSSEEndpoint 获取 SSE 端点地址
 */
export function GetSSEEndpoint(): $CancellablePromise<string> {
    return $Call.ByID(2118313847);
}

/**
 * GetServerAddress 获取服务器完整地址
 */
export function GetServerAddress(): $CancellablePromise<string> {
    return $Call.ByID(4077324442);
}

/**
 * IsRunning 检查 MCP 服务是否在运行
 * @frontend
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(3051088494);
}

/**
 * SaveConfig 保存配置
 * @frontend @mcp
 */
export function SaveConfig(config: $models.MCPConfig | null): $CancellablePromise<void> {
    return $Call.ByID(2907525184, config);
}

/**
 * SetServer 设置 MCP 服务器
 */
export function SetServer(server: $models.MCPServerInterface): $CancellablePromise<void> {
    return $Call.ByID(1394346398, server);
}

/**
 * StartMCPService 启动 MCP 服务
 */
export function StartMCPService(enabled: boolean, port: number, host: string): $CancellablePromise<void> {
    return $Call.ByID(1938195386, enabled, port, host);
}

/**
 * StopMCPService 停止 MCP 服务
 */
export function StopMCPService(): $CancellablePromise<void> {
    return $Call.ByID(648154640);
}

// Private type creation functions
const $$createType0 = $models.MCPConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
