// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BuildInfo 构建信息结构
 */
export class BuildInfo {
    /**
     * 提交哈希
     */
    "commitHash": string;

    /**
     * 提交消息
     */
    "commitMsg": string;

    /**
     * 构建时间
     */
    "buildTime": string;

    /** Creates a new BuildInfo instance. */
    constructor($$source: Partial<BuildInfo> = {}) {
        if (!("commitHash" in $$source)) {
            this["commitHash"] = "";
        }
        if (!("commitMsg" in $$source)) {
            this["commitMsg"] = "";
        }
        if (!("buildTime" in $$source)) {
            this["buildTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuildInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BuildInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BuildInfo($$parsedSource as Partial<BuildInfo>);
    }
}

/**
 * CommitInfo 提交信息结构
 */
export class CommitInfo {
    /**
     * 短哈希
     */
    "hash": string;

    /**
     * 提交消息
     */
    "message": string;

    /**
     * 作者
     */
    "author": string;

    /**
     * 相对日期
     */
    "date": string;

    /** Creates a new CommitInfo instance. */
    constructor($$source: Partial<CommitInfo> = {}) {
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CommitInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitInfo($$parsedSource as Partial<CommitInfo>);
    }
}

/**
 * ExcelConfig 统一策划配表目录配置
 * 作为各模块读取策划配表的唯一入口，逐步替代 hero_wiki/activity_wiki/excel_test 等
 * 模块各自维护的 excel_dir 配置。
 * @frontend @mcp
 */
export class ExcelConfig {
    "excel_dir": string;

    /** Creates a new ExcelConfig instance. */
    constructor($$source: Partial<ExcelConfig> = {}) {
        if (!("excel_dir" in $$source)) {
            this["excel_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExcelConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ExcelConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExcelConfig($$parsedSource as Partial<ExcelConfig>);
    }
}

/**
 * MCPConfig MCP 配置结构（用于前端绑定）
 */
export class MCPConfig {
    "enabled": boolean;
    "port": number;
    "host": string;

    /** Creates a new MCPConfig instance. */
    constructor($$source: Partial<MCPConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MCPConfig($$parsedSource as Partial<MCPConfig>);
    }
}

/**
 * MCPServerInterface MCP 服务器接口（在 internal 包中定义，避免循环导入）
 * mcp.MCPServer 会隐式实现这个接口
 */
export type MCPServerInterface = any;
