// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as activitywiki_def$0 from "../activitywiki_def/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as herowiki_def$0 from "../herowiki_def/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as accumulated_recharge$0 from "../mjs_excel/accumulated_recharge/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as achieve$0 from "../mjs_excel/achieve/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as achieve_hero$0 from "../mjs_excel/achieve_hero/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as activity$0 from "../mjs_excel/activity/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as arena_score_rewards$0 from "../mjs_excel/arena_score_rewards/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as buff$0 from "../mjs_excel/buff/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as country$0 from "../mjs_excel/country/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as draw_pet$0 from "../mjs_excel/draw_pet/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as draw_skin$0 from "../mjs_excel/draw_skin/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as drop_group$0 from "../mjs_excel/drop_group/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as drop_item$0 from "../mjs_excel/drop_item/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as drop_rule$0 from "../mjs_excel/drop_rule/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hero$0 from "../mjs_excel/hero/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hero_lines$0 from "../mjs_excel/hero_lines/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hero_skin_collition$0 from "../mjs_excel/hero_skin_collition/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hero_skin_item$0 from "../mjs_excel/hero_skin_item/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hero_skin_spine$0 from "../mjs_excel/hero_skin_spine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hero_ui$0 from "../mjs_excel/hero_ui/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as item_hero_skin$0 from "../mjs_excel/item_hero_skin/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as limit_skin_times_reward$0 from "../mjs_excel/limit_skin_times_reward/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pet$0 from "../mjs_excel/pet/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pet_audio$0 from "../mjs_excel/pet_audio/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recommend_bd$0 from "../mjs_excel/recommend_bd/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as robot_action$0 from "../mjs_excel/robot_action/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as season_pass$0 from "../mjs_excel/season_pass/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as season_pass_bag$0 from "../mjs_excel/season_pass_bag/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as season_pass_reward$0 from "../mjs_excel/season_pass_reward/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as season_pass_task$0 from "../mjs_excel/season_pass_task/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as shop$0 from "../mjs_excel/shop/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as shop_goods$0 from "../mjs_excel/shop_goods/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skill$0 from "../mjs_excel/skill/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skill_lines$0 from "../mjs_excel/skill_lines/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skill_melt$0 from "../mjs_excel/skill_melt/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skill_tag$0 from "../mjs_excel/skill_tag/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skill_ui$0 from "../mjs_excel/skill_ui/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as task_complete_cond$0 from "../mjs_excel/task_complete_cond/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

/**
 * ChangeType 变化类型
 */
export enum ChangeType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ChangeTypeModified = "modified",
    ChangeTypeAdded = "added",
    ChangeTypeRemoved = "removed",
};

/**
 * DataContainer 数据容器，包含所有要对比的数据类型
 */
export class DataContainer {
    "HeroWikiDiff": herowiki_def$0.HeroWikiDiff | null;

    /**
     * 新增：HeroWikiDiff的diff结果
     */
    "HeroWikiDiffResult": HeroWikiDiffResult | null;
    "HeroDiff": hero$0.HeroDiff[] | null;
    "CountryDiff": country$0.CountryDiff[] | null;
    "HeroLinesDiff": hero_lines$0.HeroLinesDiff[] | null;
    "HeroUIDiff": hero_ui$0.HeroUIDiff[] | null;
    "HeroSkinCollectionDiff": hero_skin_collition$0.HeroSkinCollectionDiff[] | null;
    "HeroSkinItemDiff": hero_skin_item$0.HeroSkinItemDiff[] | null;
    "HeroSkinSpineDiff": hero_skin_spine$0.HeroSkinSpineDiff[] | null;
    "ItemHeroSkinDiff": item_hero_skin$0.HeroSkinDiff[] | null;
    "DropGroupDiff": drop_group$0.DropGroupDiff[] | null;
    "DropItemDiff": drop_item$0.DropItemDiff[] | null;
    "DropRuleDiff": drop_rule$0.DropRuleDiff[] | null;
    "SeasonPassDiff": season_pass$0.SeasonPassDiff[] | null;
    "SeasonPassBagDiff": season_pass_bag$0.SeasonPassBagDiff[] | null;
    "SeasonPassRewardDiff": season_pass_reward$0.SeasonPassRewardDiff[] | null;
    "SeasonPassTaskDiff": season_pass_task$0.SeasonPassTaskDiff[] | null;
    "ArenaScoreRewardsDiff": arena_score_rewards$0.ArenaScoreRewardDiff[] | null;
    "SkillDiff": skill$0.SkillDiff[] | null;
    "SkillLineDiff": skill_lines$0.SkillLinesDiff[] | null;
    "SkillMeltDiff": skill_melt$0.SkillMeltDiff[] | null;
    "SkillTagDiff": skill_tag$0.SkillTagDiff[] | null;
    "SkillUIDiff": skill_ui$0.SkillUIDiff[] | null;
    "BuffDiff": buff$0.BuffDiff[] | null;
    "RecommendBdDiff": recommend_bd$0.RecommendBdDiff[] | null;
    "RobotActionDiff": robot_action$0.RobotActionDiff[] | null;
    "TaskCompleteCondDiff": task_complete_cond$0.TaskCompleteConditonDiff[] | null;
    "AchieveHeroDiff": achieve_hero$0.HeroAchieveDiff[] | null;
    "AchieveDiff": achieve$0.AchieveDiff[] | null;

    /**
     * 活动Wiki数据
     */
    "ActivityWikiDiff": activitywiki_def$0.ActivityWikiDiff | null;
    "ActivityDiff": activity$0.ActivityDiff[] | null;
    "DrawSkinDiff": draw_skin$0.DrawSkinDiff[] | null;
    "LimitSkinTimesRewardDiff": limit_skin_times_reward$0.LimitSkinTimesRewardDiff[] | null;
    "ShopDiff": shop$0.ShopDiff[] | null;
    "ShopGoodsDiff": shop_goods$0.ShopGoodsDiff[] | null;

    /**
     * 结缘庭相关数据
     */
    "DrawPetDiff": draw_pet$0.DrawPetDiff[] | null;
    "PetDiff": pet$0.PetDiff[] | null;
    "PetAudioDiff": pet_audio$0.PetAudioDiff[] | null;

    /**
     * activity-wiki-dev: 新增字段 - 累充活动奖励数据
     */
    "AccumulatedRechargeDiff": accumulated_recharge$0.AccumulatedRechargeDiff[] | null;

    /** Creates a new DataContainer instance. */
    constructor($$source: Partial<DataContainer> = {}) {
        if (!("HeroWikiDiff" in $$source)) {
            this["HeroWikiDiff"] = null;
        }
        if (!("HeroWikiDiffResult" in $$source)) {
            this["HeroWikiDiffResult"] = null;
        }
        if (!("HeroDiff" in $$source)) {
            this["HeroDiff"] = null;
        }
        if (!("CountryDiff" in $$source)) {
            this["CountryDiff"] = null;
        }
        if (!("HeroLinesDiff" in $$source)) {
            this["HeroLinesDiff"] = null;
        }
        if (!("HeroUIDiff" in $$source)) {
            this["HeroUIDiff"] = null;
        }
        if (!("HeroSkinCollectionDiff" in $$source)) {
            this["HeroSkinCollectionDiff"] = null;
        }
        if (!("HeroSkinItemDiff" in $$source)) {
            this["HeroSkinItemDiff"] = null;
        }
        if (!("HeroSkinSpineDiff" in $$source)) {
            this["HeroSkinSpineDiff"] = null;
        }
        if (!("ItemHeroSkinDiff" in $$source)) {
            this["ItemHeroSkinDiff"] = null;
        }
        if (!("DropGroupDiff" in $$source)) {
            this["DropGroupDiff"] = null;
        }
        if (!("DropItemDiff" in $$source)) {
            this["DropItemDiff"] = null;
        }
        if (!("DropRuleDiff" in $$source)) {
            this["DropRuleDiff"] = null;
        }
        if (!("SeasonPassDiff" in $$source)) {
            this["SeasonPassDiff"] = null;
        }
        if (!("SeasonPassBagDiff" in $$source)) {
            this["SeasonPassBagDiff"] = null;
        }
        if (!("SeasonPassRewardDiff" in $$source)) {
            this["SeasonPassRewardDiff"] = null;
        }
        if (!("SeasonPassTaskDiff" in $$source)) {
            this["SeasonPassTaskDiff"] = null;
        }
        if (!("ArenaScoreRewardsDiff" in $$source)) {
            this["ArenaScoreRewardsDiff"] = null;
        }
        if (!("SkillDiff" in $$source)) {
            this["SkillDiff"] = null;
        }
        if (!("SkillLineDiff" in $$source)) {
            this["SkillLineDiff"] = null;
        }
        if (!("SkillMeltDiff" in $$source)) {
            this["SkillMeltDiff"] = null;
        }
        if (!("SkillTagDiff" in $$source)) {
            this["SkillTagDiff"] = null;
        }
        if (!("SkillUIDiff" in $$source)) {
            this["SkillUIDiff"] = null;
        }
        if (!("BuffDiff" in $$source)) {
            this["BuffDiff"] = null;
        }
        if (!("RecommendBdDiff" in $$source)) {
            this["RecommendBdDiff"] = null;
        }
        if (!("RobotActionDiff" in $$source)) {
            this["RobotActionDiff"] = null;
        }
        if (!("TaskCompleteCondDiff" in $$source)) {
            this["TaskCompleteCondDiff"] = null;
        }
        if (!("AchieveHeroDiff" in $$source)) {
            this["AchieveHeroDiff"] = null;
        }
        if (!("AchieveDiff" in $$source)) {
            this["AchieveDiff"] = null;
        }
        if (!("ActivityWikiDiff" in $$source)) {
            this["ActivityWikiDiff"] = null;
        }
        if (!("ActivityDiff" in $$source)) {
            this["ActivityDiff"] = null;
        }
        if (!("DrawSkinDiff" in $$source)) {
            this["DrawSkinDiff"] = null;
        }
        if (!("LimitSkinTimesRewardDiff" in $$source)) {
            this["LimitSkinTimesRewardDiff"] = null;
        }
        if (!("ShopDiff" in $$source)) {
            this["ShopDiff"] = null;
        }
        if (!("ShopGoodsDiff" in $$source)) {
            this["ShopGoodsDiff"] = null;
        }
        if (!("DrawPetDiff" in $$source)) {
            this["DrawPetDiff"] = null;
        }
        if (!("PetDiff" in $$source)) {
            this["PetDiff"] = null;
        }
        if (!("PetAudioDiff" in $$source)) {
            this["PetAudioDiff"] = null;
        }
        if (!("AccumulatedRechargeDiff" in $$source)) {
            this["AccumulatedRechargeDiff"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataContainer instance from a string or object.
     */
    static createFrom($$source: any = {}): DataContainer {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType6;
        const $$createField3_0 = $$createType9;
        const $$createField4_0 = $$createType12;
        const $$createField5_0 = $$createType15;
        const $$createField6_0 = $$createType18;
        const $$createField7_0 = $$createType21;
        const $$createField8_0 = $$createType24;
        const $$createField9_0 = $$createType27;
        const $$createField10_0 = $$createType30;
        const $$createField11_0 = $$createType33;
        const $$createField12_0 = $$createType36;
        const $$createField13_0 = $$createType39;
        const $$createField14_0 = $$createType42;
        const $$createField15_0 = $$createType45;
        const $$createField16_0 = $$createType48;
        const $$createField17_0 = $$createType51;
        const $$createField18_0 = $$createType54;
        const $$createField19_0 = $$createType57;
        const $$createField20_0 = $$createType60;
        const $$createField21_0 = $$createType63;
        const $$createField22_0 = $$createType66;
        const $$createField23_0 = $$createType69;
        const $$createField24_0 = $$createType72;
        const $$createField25_0 = $$createType75;
        const $$createField26_0 = $$createType78;
        const $$createField27_0 = $$createType81;
        const $$createField28_0 = $$createType84;
        const $$createField29_0 = $$createType86;
        const $$createField30_0 = $$createType89;
        const $$createField31_0 = $$createType92;
        const $$createField32_0 = $$createType95;
        const $$createField33_0 = $$createType98;
        const $$createField34_0 = $$createType101;
        const $$createField35_0 = $$createType104;
        const $$createField36_0 = $$createType107;
        const $$createField37_0 = $$createType110;
        const $$createField38_0 = $$createType113;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("HeroWikiDiff" in $$parsedSource) {
            $$parsedSource["HeroWikiDiff"] = $$createField0_0($$parsedSource["HeroWikiDiff"]);
        }
        if ("HeroWikiDiffResult" in $$parsedSource) {
            $$parsedSource["HeroWikiDiffResult"] = $$createField1_0($$parsedSource["HeroWikiDiffResult"]);
        }
        if ("HeroDiff" in $$parsedSource) {
            $$parsedSource["HeroDiff"] = $$createField2_0($$parsedSource["HeroDiff"]);
        }
        if ("CountryDiff" in $$parsedSource) {
            $$parsedSource["CountryDiff"] = $$createField3_0($$parsedSource["CountryDiff"]);
        }
        if ("HeroLinesDiff" in $$parsedSource) {
            $$parsedSource["HeroLinesDiff"] = $$createField4_0($$parsedSource["HeroLinesDiff"]);
        }
        if ("HeroUIDiff" in $$parsedSource) {
            $$parsedSource["HeroUIDiff"] = $$createField5_0($$parsedSource["HeroUIDiff"]);
        }
        if ("HeroSkinCollectionDiff" in $$parsedSource) {
            $$parsedSource["HeroSkinCollectionDiff"] = $$createField6_0($$parsedSource["HeroSkinCollectionDiff"]);
        }
        if ("HeroSkinItemDiff" in $$parsedSource) {
            $$parsedSource["HeroSkinItemDiff"] = $$createField7_0($$parsedSource["HeroSkinItemDiff"]);
        }
        if ("HeroSkinSpineDiff" in $$parsedSource) {
            $$parsedSource["HeroSkinSpineDiff"] = $$createField8_0($$parsedSource["HeroSkinSpineDiff"]);
        }
        if ("ItemHeroSkinDiff" in $$parsedSource) {
            $$parsedSource["ItemHeroSkinDiff"] = $$createField9_0($$parsedSource["ItemHeroSkinDiff"]);
        }
        if ("DropGroupDiff" in $$parsedSource) {
            $$parsedSource["DropGroupDiff"] = $$createField10_0($$parsedSource["DropGroupDiff"]);
        }
        if ("DropItemDiff" in $$parsedSource) {
            $$parsedSource["DropItemDiff"] = $$createField11_0($$parsedSource["DropItemDiff"]);
        }
        if ("DropRuleDiff" in $$parsedSource) {
            $$parsedSource["DropRuleDiff"] = $$createField12_0($$parsedSource["DropRuleDiff"]);
        }
        if ("SeasonPassDiff" in $$parsedSource) {
            $$parsedSource["SeasonPassDiff"] = $$createField13_0($$parsedSource["SeasonPassDiff"]);
        }
        if ("SeasonPassBagDiff" in $$parsedSource) {
            $$parsedSource["SeasonPassBagDiff"] = $$createField14_0($$parsedSource["SeasonPassBagDiff"]);
        }
        if ("SeasonPassRewardDiff" in $$parsedSource) {
            $$parsedSource["SeasonPassRewardDiff"] = $$createField15_0($$parsedSource["SeasonPassRewardDiff"]);
        }
        if ("SeasonPassTaskDiff" in $$parsedSource) {
            $$parsedSource["SeasonPassTaskDiff"] = $$createField16_0($$parsedSource["SeasonPassTaskDiff"]);
        }
        if ("ArenaScoreRewardsDiff" in $$parsedSource) {
            $$parsedSource["ArenaScoreRewardsDiff"] = $$createField17_0($$parsedSource["ArenaScoreRewardsDiff"]);
        }
        if ("SkillDiff" in $$parsedSource) {
            $$parsedSource["SkillDiff"] = $$createField18_0($$parsedSource["SkillDiff"]);
        }
        if ("SkillLineDiff" in $$parsedSource) {
            $$parsedSource["SkillLineDiff"] = $$createField19_0($$parsedSource["SkillLineDiff"]);
        }
        if ("SkillMeltDiff" in $$parsedSource) {
            $$parsedSource["SkillMeltDiff"] = $$createField20_0($$parsedSource["SkillMeltDiff"]);
        }
        if ("SkillTagDiff" in $$parsedSource) {
            $$parsedSource["SkillTagDiff"] = $$createField21_0($$parsedSource["SkillTagDiff"]);
        }
        if ("SkillUIDiff" in $$parsedSource) {
            $$parsedSource["SkillUIDiff"] = $$createField22_0($$parsedSource["SkillUIDiff"]);
        }
        if ("BuffDiff" in $$parsedSource) {
            $$parsedSource["BuffDiff"] = $$createField23_0($$parsedSource["BuffDiff"]);
        }
        if ("RecommendBdDiff" in $$parsedSource) {
            $$parsedSource["RecommendBdDiff"] = $$createField24_0($$parsedSource["RecommendBdDiff"]);
        }
        if ("RobotActionDiff" in $$parsedSource) {
            $$parsedSource["RobotActionDiff"] = $$createField25_0($$parsedSource["RobotActionDiff"]);
        }
        if ("TaskCompleteCondDiff" in $$parsedSource) {
            $$parsedSource["TaskCompleteCondDiff"] = $$createField26_0($$parsedSource["TaskCompleteCondDiff"]);
        }
        if ("AchieveHeroDiff" in $$parsedSource) {
            $$parsedSource["AchieveHeroDiff"] = $$createField27_0($$parsedSource["AchieveHeroDiff"]);
        }
        if ("AchieveDiff" in $$parsedSource) {
            $$parsedSource["AchieveDiff"] = $$createField28_0($$parsedSource["AchieveDiff"]);
        }
        if ("ActivityWikiDiff" in $$parsedSource) {
            $$parsedSource["ActivityWikiDiff"] = $$createField29_0($$parsedSource["ActivityWikiDiff"]);
        }
        if ("ActivityDiff" in $$parsedSource) {
            $$parsedSource["ActivityDiff"] = $$createField30_0($$parsedSource["ActivityDiff"]);
        }
        if ("DrawSkinDiff" in $$parsedSource) {
            $$parsedSource["DrawSkinDiff"] = $$createField31_0($$parsedSource["DrawSkinDiff"]);
        }
        if ("LimitSkinTimesRewardDiff" in $$parsedSource) {
            $$parsedSource["LimitSkinTimesRewardDiff"] = $$createField32_0($$parsedSource["LimitSkinTimesRewardDiff"]);
        }
        if ("ShopDiff" in $$parsedSource) {
            $$parsedSource["ShopDiff"] = $$createField33_0($$parsedSource["ShopDiff"]);
        }
        if ("ShopGoodsDiff" in $$parsedSource) {
            $$parsedSource["ShopGoodsDiff"] = $$createField34_0($$parsedSource["ShopGoodsDiff"]);
        }
        if ("DrawPetDiff" in $$parsedSource) {
            $$parsedSource["DrawPetDiff"] = $$createField35_0($$parsedSource["DrawPetDiff"]);
        }
        if ("PetDiff" in $$parsedSource) {
            $$parsedSource["PetDiff"] = $$createField36_0($$parsedSource["PetDiff"]);
        }
        if ("PetAudioDiff" in $$parsedSource) {
            $$parsedSource["PetAudioDiff"] = $$createField37_0($$parsedSource["PetAudioDiff"]);
        }
        if ("AccumulatedRechargeDiff" in $$parsedSource) {
            $$parsedSource["AccumulatedRechargeDiff"] = $$createField38_0($$parsedSource["AccumulatedRechargeDiff"]);
        }
        return new DataContainer($$parsedSource as Partial<DataContainer>);
    }
}

/**
 * FieldChange 单个字段变化
 */
export class FieldChange {
    /**
     * 完整字段路径，如 "MainSkill.SkillName"
     */
    "FieldPath": string;
    "FieldName": string;

    /**
     * 所属结构体名
     */
    "StructName": string;

    /**
     * 嵌套层级
     */
    "NestedLevel": number;
    "OldValue": any;
    "NewValue": any;

    /**
     * 值类型
     */
    "ValueType": string;
    "ChangeType": ChangeType;

    /** Creates a new FieldChange instance. */
    constructor($$source: Partial<FieldChange> = {}) {
        if (!("FieldPath" in $$source)) {
            this["FieldPath"] = "";
        }
        if (!("FieldName" in $$source)) {
            this["FieldName"] = "";
        }
        if (!("StructName" in $$source)) {
            this["StructName"] = "";
        }
        if (!("NestedLevel" in $$source)) {
            this["NestedLevel"] = 0;
        }
        if (!("OldValue" in $$source)) {
            this["OldValue"] = null;
        }
        if (!("NewValue" in $$source)) {
            this["NewValue"] = null;
        }
        if (!("ValueType" in $$source)) {
            this["ValueType"] = "";
        }
        if (!("ChangeType" in $$source)) {
            this["ChangeType"] = ChangeType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FieldChange instance from a string or object.
     */
    static createFrom($$source: any = {}): FieldChange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FieldChange($$parsedSource as Partial<FieldChange>);
    }
}

/**
 * HeroDiffDetail 单个武将的diff详情
 */
export class HeroDiffDetail {
    "EHeroId": string;
    "Name": string;
    "FieldChanges": (FieldChange | null)[];
    "NestedChanges": { [_ in string]?: NestedStructChange | null };

    /**
     * added, removed, modified
     */
    "ChangeType": ChangeType;

    /**
     * 变化字段总数
     */
    "ChangeCount": number;

    /** Creates a new HeroDiffDetail instance. */
    constructor($$source: Partial<HeroDiffDetail> = {}) {
        if (!("EHeroId" in $$source)) {
            this["EHeroId"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("FieldChanges" in $$source)) {
            this["FieldChanges"] = [];
        }
        if (!("NestedChanges" in $$source)) {
            this["NestedChanges"] = {};
        }
        if (!("ChangeType" in $$source)) {
            this["ChangeType"] = ChangeType.$zero;
        }
        if (!("ChangeCount" in $$source)) {
            this["ChangeCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroDiffDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroDiffDetail {
        const $$createField2_0 = $$createType116;
        const $$createField3_0 = $$createType119;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("FieldChanges" in $$parsedSource) {
            $$parsedSource["FieldChanges"] = $$createField2_0($$parsedSource["FieldChanges"]);
        }
        if ("NestedChanges" in $$parsedSource) {
            $$parsedSource["NestedChanges"] = $$createField3_0($$parsedSource["NestedChanges"]);
        }
        return new HeroDiffDetail($$parsedSource as Partial<HeroDiffDetail>);
    }
}

/**
 * HeroWikiDiffResult HeroWikiDiff的diff结果
 */
export class HeroWikiDiffResult {
    "Timestamp": time$0.Time;

    /**
     * 按EHeroId索引的diff详情
     */
    "HeroesDiff": { [_ in string]?: HeroDiffDetail | null };
    "Summary": HeroWikiDiffSummary | null;

    /**
     * 删除武将的完整数据（用于前端显示）
     */
    "RemovedHeroesData": { [_ in string]?: herowiki_def$0.HeroCompleteData | null };

    /** Creates a new HeroWikiDiffResult instance. */
    constructor($$source: Partial<HeroWikiDiffResult> = {}) {
        if (!("Timestamp" in $$source)) {
            this["Timestamp"] = null;
        }
        if (!("HeroesDiff" in $$source)) {
            this["HeroesDiff"] = {};
        }
        if (!("Summary" in $$source)) {
            this["Summary"] = null;
        }
        if (!("RemovedHeroesData" in $$source)) {
            this["RemovedHeroesData"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroWikiDiffResult instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroWikiDiffResult {
        const $$createField1_0 = $$createType122;
        const $$createField2_0 = $$createType124;
        const $$createField3_0 = $$createType127;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("HeroesDiff" in $$parsedSource) {
            $$parsedSource["HeroesDiff"] = $$createField1_0($$parsedSource["HeroesDiff"]);
        }
        if ("Summary" in $$parsedSource) {
            $$parsedSource["Summary"] = $$createField2_0($$parsedSource["Summary"]);
        }
        if ("RemovedHeroesData" in $$parsedSource) {
            $$parsedSource["RemovedHeroesData"] = $$createField3_0($$parsedSource["RemovedHeroesData"]);
        }
        return new HeroWikiDiffResult($$parsedSource as Partial<HeroWikiDiffResult>);
    }
}

/**
 * HeroWikiDiffSummary 汇总信息
 */
export class HeroWikiDiffSummary {
    "TotalHeroes": number;

    /**
     * 新增的武将ID
     */
    "AddedHeroes": string[];

    /**
     * 删除的武将ID
     */
    "RemovedHeroes": string[];

    /**
     * 修改的武将ID
     */
    "ModifiedHeroes": string[];

    /**
     * 总变化数
     */
    "TotalChanges": number;

    /** Creates a new HeroWikiDiffSummary instance. */
    constructor($$source: Partial<HeroWikiDiffSummary> = {}) {
        if (!("TotalHeroes" in $$source)) {
            this["TotalHeroes"] = 0;
        }
        if (!("AddedHeroes" in $$source)) {
            this["AddedHeroes"] = [];
        }
        if (!("RemovedHeroes" in $$source)) {
            this["RemovedHeroes"] = [];
        }
        if (!("ModifiedHeroes" in $$source)) {
            this["ModifiedHeroes"] = [];
        }
        if (!("TotalChanges" in $$source)) {
            this["TotalChanges"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroWikiDiffSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroWikiDiffSummary {
        const $$createField1_0 = $$createType128;
        const $$createField2_0 = $$createType128;
        const $$createField3_0 = $$createType128;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("AddedHeroes" in $$parsedSource) {
            $$parsedSource["AddedHeroes"] = $$createField1_0($$parsedSource["AddedHeroes"]);
        }
        if ("RemovedHeroes" in $$parsedSource) {
            $$parsedSource["RemovedHeroes"] = $$createField2_0($$parsedSource["RemovedHeroes"]);
        }
        if ("ModifiedHeroes" in $$parsedSource) {
            $$parsedSource["ModifiedHeroes"] = $$createField3_0($$parsedSource["ModifiedHeroes"]);
        }
        return new HeroWikiDiffSummary($$parsedSource as Partial<HeroWikiDiffSummary>);
    }
}

/**
 * NestedStructChange 嵌套结构体变化
 */
export class NestedStructChange {
    /**
     * 结构体路径
     */
    "StructPath": string;

    /**
     * 结构体类型名
     */
    "StructType": string;

    /**
     * 变化的字段数
     */
    "FieldCount": number;

    /**
     * 该结构体的字段变化
     */
    "Changes": (FieldChange | null)[];

    /**
     * 子结构体变化
     */
    "Children": { [_ in string]?: NestedStructChange | null };

    /** Creates a new NestedStructChange instance. */
    constructor($$source: Partial<NestedStructChange> = {}) {
        if (!("StructPath" in $$source)) {
            this["StructPath"] = "";
        }
        if (!("StructType" in $$source)) {
            this["StructType"] = "";
        }
        if (!("FieldCount" in $$source)) {
            this["FieldCount"] = 0;
        }
        if (!("Changes" in $$source)) {
            this["Changes"] = [];
        }
        if (!("Children" in $$source)) {
            this["Children"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NestedStructChange instance from a string or object.
     */
    static createFrom($$source: any = {}): NestedStructChange {
        const $$createField3_0 = $$createType116;
        const $$createField4_0 = $$createType119;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Changes" in $$parsedSource) {
            $$parsedSource["Changes"] = $$createField3_0($$parsedSource["Changes"]);
        }
        if ("Children" in $$parsedSource) {
            $$parsedSource["Children"] = $$createField4_0($$parsedSource["Children"]);
        }
        return new NestedStructChange($$parsedSource as Partial<NestedStructChange>);
    }
}

// Private type creation functions
const $$createType0 = herowiki_def$0.HeroWikiDiff.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = HeroWikiDiffResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = hero$0.HeroDiff.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = country$0.CountryDiff.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = hero_lines$0.HeroLinesDiff.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = hero_ui$0.HeroUIDiff.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = hero_skin_collition$0.HeroSkinCollectionDiff.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = hero_skin_item$0.HeroSkinItemDiff.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = hero_skin_spine$0.HeroSkinSpineDiff.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = item_hero_skin$0.HeroSkinDiff.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = drop_group$0.DropGroupDiff.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = $Create.Nullable($$createType29);
const $$createType31 = drop_item$0.DropItemDiff.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = $Create.Nullable($$createType32);
const $$createType34 = drop_rule$0.DropRuleDiff.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = $Create.Nullable($$createType35);
const $$createType37 = season_pass$0.SeasonPassDiff.createFrom;
const $$createType38 = $Create.Array($$createType37);
const $$createType39 = $Create.Nullable($$createType38);
const $$createType40 = season_pass_bag$0.SeasonPassBagDiff.createFrom;
const $$createType41 = $Create.Array($$createType40);
const $$createType42 = $Create.Nullable($$createType41);
const $$createType43 = season_pass_reward$0.SeasonPassRewardDiff.createFrom;
const $$createType44 = $Create.Array($$createType43);
const $$createType45 = $Create.Nullable($$createType44);
const $$createType46 = season_pass_task$0.SeasonPassTaskDiff.createFrom;
const $$createType47 = $Create.Array($$createType46);
const $$createType48 = $Create.Nullable($$createType47);
const $$createType49 = arena_score_rewards$0.ArenaScoreRewardDiff.createFrom;
const $$createType50 = $Create.Array($$createType49);
const $$createType51 = $Create.Nullable($$createType50);
const $$createType52 = skill$0.SkillDiff.createFrom;
const $$createType53 = $Create.Array($$createType52);
const $$createType54 = $Create.Nullable($$createType53);
const $$createType55 = skill_lines$0.SkillLinesDiff.createFrom;
const $$createType56 = $Create.Array($$createType55);
const $$createType57 = $Create.Nullable($$createType56);
const $$createType58 = skill_melt$0.SkillMeltDiff.createFrom;
const $$createType59 = $Create.Array($$createType58);
const $$createType60 = $Create.Nullable($$createType59);
const $$createType61 = skill_tag$0.SkillTagDiff.createFrom;
const $$createType62 = $Create.Array($$createType61);
const $$createType63 = $Create.Nullable($$createType62);
const $$createType64 = skill_ui$0.SkillUIDiff.createFrom;
const $$createType65 = $Create.Array($$createType64);
const $$createType66 = $Create.Nullable($$createType65);
const $$createType67 = buff$0.BuffDiff.createFrom;
const $$createType68 = $Create.Array($$createType67);
const $$createType69 = $Create.Nullable($$createType68);
const $$createType70 = recommend_bd$0.RecommendBdDiff.createFrom;
const $$createType71 = $Create.Array($$createType70);
const $$createType72 = $Create.Nullable($$createType71);
const $$createType73 = robot_action$0.RobotActionDiff.createFrom;
const $$createType74 = $Create.Array($$createType73);
const $$createType75 = $Create.Nullable($$createType74);
const $$createType76 = task_complete_cond$0.TaskCompleteConditonDiff.createFrom;
const $$createType77 = $Create.Array($$createType76);
const $$createType78 = $Create.Nullable($$createType77);
const $$createType79 = achieve_hero$0.HeroAchieveDiff.createFrom;
const $$createType80 = $Create.Array($$createType79);
const $$createType81 = $Create.Nullable($$createType80);
const $$createType82 = achieve$0.AchieveDiff.createFrom;
const $$createType83 = $Create.Array($$createType82);
const $$createType84 = $Create.Nullable($$createType83);
const $$createType85 = activitywiki_def$0.ActivityWikiDiff.createFrom;
const $$createType86 = $Create.Nullable($$createType85);
const $$createType87 = activity$0.ActivityDiff.createFrom;
const $$createType88 = $Create.Array($$createType87);
const $$createType89 = $Create.Nullable($$createType88);
const $$createType90 = draw_skin$0.DrawSkinDiff.createFrom;
const $$createType91 = $Create.Array($$createType90);
const $$createType92 = $Create.Nullable($$createType91);
const $$createType93 = limit_skin_times_reward$0.LimitSkinTimesRewardDiff.createFrom;
const $$createType94 = $Create.Array($$createType93);
const $$createType95 = $Create.Nullable($$createType94);
const $$createType96 = shop$0.ShopDiff.createFrom;
const $$createType97 = $Create.Array($$createType96);
const $$createType98 = $Create.Nullable($$createType97);
const $$createType99 = shop_goods$0.ShopGoodsDiff.createFrom;
const $$createType100 = $Create.Array($$createType99);
const $$createType101 = $Create.Nullable($$createType100);
const $$createType102 = draw_pet$0.DrawPetDiff.createFrom;
const $$createType103 = $Create.Array($$createType102);
const $$createType104 = $Create.Nullable($$createType103);
const $$createType105 = pet$0.PetDiff.createFrom;
const $$createType106 = $Create.Array($$createType105);
const $$createType107 = $Create.Nullable($$createType106);
const $$createType108 = pet_audio$0.PetAudioDiff.createFrom;
const $$createType109 = $Create.Array($$createType108);
const $$createType110 = $Create.Nullable($$createType109);
const $$createType111 = accumulated_recharge$0.AccumulatedRechargeDiff.createFrom;
const $$createType112 = $Create.Array($$createType111);
const $$createType113 = $Create.Nullable($$createType112);
const $$createType114 = FieldChange.createFrom;
const $$createType115 = $Create.Nullable($$createType114);
const $$createType116 = $Create.Array($$createType115);
const $$createType117 = NestedStructChange.createFrom;
const $$createType118 = $Create.Nullable($$createType117);
const $$createType119 = $Create.Map($Create.Any, $$createType118);
const $$createType120 = HeroDiffDetail.createFrom;
const $$createType121 = $Create.Nullable($$createType120);
const $$createType122 = $Create.Map($Create.Any, $$createType121);
const $$createType123 = HeroWikiDiffSummary.createFrom;
const $$createType124 = $Create.Nullable($$createType123);
const $$createType125 = herowiki_def$0.HeroCompleteData.createFrom;
const $$createType126 = $Create.Nullable($$createType125);
const $$createType127 = $Create.Map($Create.Any, $$createType126);
const $$createType128 = $Create.Array($Create.Any);
