// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HeroResCheckService 武将语音资源检查服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hero_res_check$0 from "./hero_res_check/models.js";

/**
 * Check 检查武将语音资源
 * cardDir 表示同级目录的../../client/Master/Card/位置
 * @frontend
 */
export function Check(excelDir: string, cardDir: string): $CancellablePromise<hero_res_check$0.VoiceCheckReport | null> {
    return $Call.ByID(1537425868, excelDir, cardDir).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = hero_res_check$0.VoiceCheckReport.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
