// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class TaskCompleteConditonDiff {
    "Id": number;
    "CondDes": string;
    "CompleteCond": string;
    "CompleteCondParam": number[];
    "JumpCond": string;
    "JumpParm": number[];

    /** Creates a new TaskCompleteConditonDiff instance. */
    constructor($$source: Partial<TaskCompleteConditonDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("CondDes" in $$source)) {
            this["CondDes"] = "";
        }
        if (!("CompleteCond" in $$source)) {
            this["CompleteCond"] = "";
        }
        if (!("CompleteCondParam" in $$source)) {
            this["CompleteCondParam"] = [];
        }
        if (!("JumpCond" in $$source)) {
            this["JumpCond"] = "";
        }
        if (!("JumpParm" in $$source)) {
            this["JumpParm"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskCompleteConditonDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskCompleteConditonDiff {
        const $$createField3_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CompleteCondParam" in $$parsedSource) {
            $$parsedSource["CompleteCondParam"] = $$createField3_0($$parsedSource["CompleteCondParam"]);
        }
        if ("JumpParm" in $$parsedSource) {
            $$parsedSource["JumpParm"] = $$createField5_0($$parsedSource["JumpParm"]);
        }
        return new TaskCompleteConditonDiff($$parsedSource as Partial<TaskCompleteConditonDiff>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
