// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DrawPetDiff 结缘亭表差异数据结构
 */
export class DrawPetDiff {
    "Id": number;
    "Name": string;
    "EnsureNewer": number;
    "EnsureCount": number;
    "FirstEnsureNewer": number;
    "OnceDropRule": number;
    "TenDropRule": number;
    "OnceItemCost": ItemCfg[];
    "TenItemCost": ItemCfg[];
    "DailyLimit": number;
    "ActivityId": number[];
    "BigAwardCount": number;
    "BigAwardItemId": number;
    "StartTime": string;
    "EndTime": string;
    "BigAwards": ItemCfg[];
    "PartnerItem": ItemCfg | null;
    "Byproducts": number[];
    "ProbabilityContents": string[];
    "ProbabilityPercents": number[];
    "DrawPetTitleIcon": string;
    "DrawPetTitleDescBg": string;
    "DrawRuleContent": string;

    /** Creates a new DrawPetDiff instance. */
    constructor($$source: Partial<DrawPetDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("EnsureNewer" in $$source)) {
            this["EnsureNewer"] = 0;
        }
        if (!("EnsureCount" in $$source)) {
            this["EnsureCount"] = 0;
        }
        if (!("FirstEnsureNewer" in $$source)) {
            this["FirstEnsureNewer"] = 0;
        }
        if (!("OnceDropRule" in $$source)) {
            this["OnceDropRule"] = 0;
        }
        if (!("TenDropRule" in $$source)) {
            this["TenDropRule"] = 0;
        }
        if (!("OnceItemCost" in $$source)) {
            this["OnceItemCost"] = [];
        }
        if (!("TenItemCost" in $$source)) {
            this["TenItemCost"] = [];
        }
        if (!("DailyLimit" in $$source)) {
            this["DailyLimit"] = 0;
        }
        if (!("ActivityId" in $$source)) {
            this["ActivityId"] = [];
        }
        if (!("BigAwardCount" in $$source)) {
            this["BigAwardCount"] = 0;
        }
        if (!("BigAwardItemId" in $$source)) {
            this["BigAwardItemId"] = 0;
        }
        if (!("StartTime" in $$source)) {
            this["StartTime"] = "";
        }
        if (!("EndTime" in $$source)) {
            this["EndTime"] = "";
        }
        if (!("BigAwards" in $$source)) {
            this["BigAwards"] = [];
        }
        if (!("PartnerItem" in $$source)) {
            this["PartnerItem"] = null;
        }
        if (!("Byproducts" in $$source)) {
            this["Byproducts"] = [];
        }
        if (!("ProbabilityContents" in $$source)) {
            this["ProbabilityContents"] = [];
        }
        if (!("ProbabilityPercents" in $$source)) {
            this["ProbabilityPercents"] = [];
        }
        if (!("DrawPetTitleIcon" in $$source)) {
            this["DrawPetTitleIcon"] = "";
        }
        if (!("DrawPetTitleDescBg" in $$source)) {
            this["DrawPetTitleDescBg"] = "";
        }
        if (!("DrawRuleContent" in $$source)) {
            this["DrawRuleContent"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DrawPetDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): DrawPetDiff {
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType1;
        const $$createField10_0 = $$createType2;
        const $$createField15_0 = $$createType1;
        const $$createField16_0 = $$createType3;
        const $$createField17_0 = $$createType2;
        const $$createField18_0 = $$createType4;
        const $$createField19_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("OnceItemCost" in $$parsedSource) {
            $$parsedSource["OnceItemCost"] = $$createField7_0($$parsedSource["OnceItemCost"]);
        }
        if ("TenItemCost" in $$parsedSource) {
            $$parsedSource["TenItemCost"] = $$createField8_0($$parsedSource["TenItemCost"]);
        }
        if ("ActivityId" in $$parsedSource) {
            $$parsedSource["ActivityId"] = $$createField10_0($$parsedSource["ActivityId"]);
        }
        if ("BigAwards" in $$parsedSource) {
            $$parsedSource["BigAwards"] = $$createField15_0($$parsedSource["BigAwards"]);
        }
        if ("PartnerItem" in $$parsedSource) {
            $$parsedSource["PartnerItem"] = $$createField16_0($$parsedSource["PartnerItem"]);
        }
        if ("Byproducts" in $$parsedSource) {
            $$parsedSource["Byproducts"] = $$createField17_0($$parsedSource["Byproducts"]);
        }
        if ("ProbabilityContents" in $$parsedSource) {
            $$parsedSource["ProbabilityContents"] = $$createField18_0($$parsedSource["ProbabilityContents"]);
        }
        if ("ProbabilityPercents" in $$parsedSource) {
            $$parsedSource["ProbabilityPercents"] = $$createField19_0($$parsedSource["ProbabilityPercents"]);
        }
        return new DrawPetDiff($$parsedSource as Partial<DrawPetDiff>);
    }
}

/**
 * ItemCfg 道具配置
 */
export class ItemCfg {
    "ItemId": number;
    "Count": number;

    /** Creates a new ItemCfg instance. */
    constructor($$source: Partial<ItemCfg> = {}) {
        if (!("ItemId" in $$source)) {
            this["ItemId"] = 0;
        }
        if (!("Count" in $$source)) {
            this["Count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemCfg instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemCfg {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ItemCfg($$parsedSource as Partial<ItemCfg>);
    }
}

// Private type creation functions
const $$createType0 = ItemCfg.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Nullable($$createType0);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Array($Create.Any);
