// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DiffStats 差异统计 (驱动界面汇总栏与"有差异才允许写回"的门槛判断)。
 */
export class DiffStats {
    /**
     * Creates a new DiffStats instance.
     * @param {Partial<DiffStats>} [$$source = {}] - The source object to create the DiffStats.
     */
    constructor($$source = {}) {
        if (!("MatchedRows" in $$source)) {
            /**
             * 配对行数 (含内容有差异的)
             * @member
             * @type {number}
             */
            this["MatchedRows"] = 0;
        }
        if (!("LeftOnlyRows" in $$source)) {
            /**
             * 左独有行数
             * @member
             * @type {number}
             */
            this["LeftOnlyRows"] = 0;
        }
        if (!("RightOnlyRows" in $$source)) {
            /**
             * 右独有行数
             * @member
             * @type {number}
             */
            this["RightOnlyRows"] = 0;
        }
        if (!("ModifiedCells" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ModifiedCells"] = 0;
        }
        if (!("LeftOnlyCells" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["LeftOnlyCells"] = 0;
        }
        if (!("RightOnlyCells" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["RightOnlyCells"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiffStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffStats(/** @type {Partial<DiffStats>} */($$parsedSource));
    }
}
