// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CountryDiff {
    "ECountry": string;
    "Name": string;
    "KingName": string;
    "SeatFlagImagePath": string;
    "PlayerInfoFlagImagePath": string;
    "PlayerInfoFlagTextPath": string;
    "IsWhiteBg": boolean;
    "IsOpen": boolean;
    "NameArtSelectedFontPath": string;
    "NameArtUnselectedFontPath": string;
    "ShiLiSmallTopIcon": string;
    "ShiLiSmallBottomIcon": string;
    "SortPriority": number;
    "GuildIcon": string;

    /** Creates a new CountryDiff instance. */
    constructor($$source: Partial<CountryDiff> = {}) {
        if (!("ECountry" in $$source)) {
            this["ECountry"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("KingName" in $$source)) {
            this["KingName"] = "";
        }
        if (!("SeatFlagImagePath" in $$source)) {
            this["SeatFlagImagePath"] = "";
        }
        if (!("PlayerInfoFlagImagePath" in $$source)) {
            this["PlayerInfoFlagImagePath"] = "";
        }
        if (!("PlayerInfoFlagTextPath" in $$source)) {
            this["PlayerInfoFlagTextPath"] = "";
        }
        if (!("IsWhiteBg" in $$source)) {
            this["IsWhiteBg"] = false;
        }
        if (!("IsOpen" in $$source)) {
            this["IsOpen"] = false;
        }
        if (!("NameArtSelectedFontPath" in $$source)) {
            this["NameArtSelectedFontPath"] = "";
        }
        if (!("NameArtUnselectedFontPath" in $$source)) {
            this["NameArtUnselectedFontPath"] = "";
        }
        if (!("ShiLiSmallTopIcon" in $$source)) {
            this["ShiLiSmallTopIcon"] = "";
        }
        if (!("ShiLiSmallBottomIcon" in $$source)) {
            this["ShiLiSmallBottomIcon"] = "";
        }
        if (!("SortPriority" in $$source)) {
            this["SortPriority"] = 0;
        }
        if (!("GuildIcon" in $$source)) {
            this["GuildIcon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CountryDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): CountryDiff {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CountryDiff($$parsedSource as Partial<CountryDiff>);
    }
}
