// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SkillTagDiff {
    "SkillTag": string;
    "TagName": string;
    "TagColor": string;
    "TagDes": string;
    "None": string;
    "None1": string;

    /** Creates a new SkillTagDiff instance. */
    constructor($$source: Partial<SkillTagDiff> = {}) {
        if (!("SkillTag" in $$source)) {
            this["SkillTag"] = "";
        }
        if (!("TagName" in $$source)) {
            this["TagName"] = "";
        }
        if (!("TagColor" in $$source)) {
            this["TagColor"] = "";
        }
        if (!("TagDes" in $$source)) {
            this["TagDes"] = "";
        }
        if (!("None" in $$source)) {
            this["None"] = "";
        }
        if (!("None1" in $$source)) {
            this["None1"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillTagDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillTagDiff {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillTagDiff($$parsedSource as Partial<SkillTagDiff>);
    }
}
