// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ActivityDiff {
    "Id": number;

    /**
     * 枚举值，如 Activity_Test
     */
    "EActivityId": string;

    /**
     * 如 ActTypeSkinRaffle
     */
    "ActivityType": string;
    "ActivityPrefabType": string;
    "BelongId": number;
    "Name": string;
    "ShowTab": boolean;
    "Weight": number;
    "TimeType": number;
    "StartTime": string;
    "EndTime": string;
    "RewardTime": string;
    "RewardEndTime": string;
    "CustomParma": number[];
    "CustomParma2": string;

    /** Creates a new ActivityDiff instance. */
    constructor($$source: Partial<ActivityDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("EActivityId" in $$source)) {
            this["EActivityId"] = "";
        }
        if (!("ActivityType" in $$source)) {
            this["ActivityType"] = "";
        }
        if (!("ActivityPrefabType" in $$source)) {
            this["ActivityPrefabType"] = "";
        }
        if (!("BelongId" in $$source)) {
            this["BelongId"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("ShowTab" in $$source)) {
            this["ShowTab"] = false;
        }
        if (!("Weight" in $$source)) {
            this["Weight"] = 0;
        }
        if (!("TimeType" in $$source)) {
            this["TimeType"] = 0;
        }
        if (!("StartTime" in $$source)) {
            this["StartTime"] = "";
        }
        if (!("EndTime" in $$source)) {
            this["EndTime"] = "";
        }
        if (!("RewardTime" in $$source)) {
            this["RewardTime"] = "";
        }
        if (!("RewardEndTime" in $$source)) {
            this["RewardEndTime"] = "";
        }
        if (!("CustomParma" in $$source)) {
            this["CustomParma"] = [];
        }
        if (!("CustomParma2" in $$source)) {
            this["CustomParma2"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActivityDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): ActivityDiff {
        const $$createField13_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CustomParma" in $$parsedSource) {
            $$parsedSource["CustomParma"] = $$createField13_0($$parsedSource["CustomParma"]);
        }
        return new ActivityDiff($$parsedSource as Partial<ActivityDiff>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
