// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class RobotActionDiff {
    "Id": string;
    "None": string;
    "Action": string[];
    "TargetNum": number[];
    "TargetType": string[];
    "CardNum": number[];
    "CardFromType": string[];
    "TransCardSkill": number[];
    "DefaultCardSkill": number[];

    /** Creates a new RobotActionDiff instance. */
    constructor($$source: Partial<RobotActionDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("None" in $$source)) {
            this["None"] = "";
        }
        if (!("Action" in $$source)) {
            this["Action"] = [];
        }
        if (!("TargetNum" in $$source)) {
            this["TargetNum"] = [];
        }
        if (!("TargetType" in $$source)) {
            this["TargetType"] = [];
        }
        if (!("CardNum" in $$source)) {
            this["CardNum"] = [];
        }
        if (!("CardFromType" in $$source)) {
            this["CardFromType"] = [];
        }
        if (!("TransCardSkill" in $$source)) {
            this["TransCardSkill"] = [];
        }
        if (!("DefaultCardSkill" in $$source)) {
            this["DefaultCardSkill"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RobotActionDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): RobotActionDiff {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Action" in $$parsedSource) {
            $$parsedSource["Action"] = $$createField2_0($$parsedSource["Action"]);
        }
        if ("TargetNum" in $$parsedSource) {
            $$parsedSource["TargetNum"] = $$createField3_0($$parsedSource["TargetNum"]);
        }
        if ("TargetType" in $$parsedSource) {
            $$parsedSource["TargetType"] = $$createField4_0($$parsedSource["TargetType"]);
        }
        if ("CardNum" in $$parsedSource) {
            $$parsedSource["CardNum"] = $$createField5_0($$parsedSource["CardNum"]);
        }
        if ("CardFromType" in $$parsedSource) {
            $$parsedSource["CardFromType"] = $$createField6_0($$parsedSource["CardFromType"]);
        }
        if ("TransCardSkill" in $$parsedSource) {
            $$parsedSource["TransCardSkill"] = $$createField7_0($$parsedSource["TransCardSkill"]);
        }
        if ("DefaultCardSkill" in $$parsedSource) {
            $$parsedSource["DefaultCardSkill"] = $$createField8_0($$parsedSource["DefaultCardSkill"]);
        }
        return new RobotActionDiff($$parsedSource as Partial<RobotActionDiff>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
