// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ItemCfg {
    "ItemId": number;
    "Count": number;

    /** Creates a new ItemCfg instance. */
    constructor($$source: Partial<ItemCfg> = {}) {
        if (!("ItemId" in $$source)) {
            this["ItemId"] = 0;
        }
        if (!("Count" in $$source)) {
            this["Count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemCfg instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemCfg {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ItemCfg($$parsedSource as Partial<ItemCfg>);
    }
}

export class ShopGoodsDiff {
    "Id": number;
    "Name": string;
    "Desc": string;
    "Item": ItemCfg[];
    "ExtraItem": ItemCfg[];
    "CostId": number;
    "ShopType": string;
    "RechargeAndriod": number;
    "RechargeIOS": number;
    "RechargeMulti": number;
    "RechargeMultiGroup": number;
    "Price": number;
    "OldPrice": number;
    "Discount": number;
    "LimitType": number;
    "LimitCount": number;
    "MaxBuyCount": number;
    "Pos": number;
    "IsNew": boolean;
    "Countdown": number;
    "IsHomePage": boolean;
    "Icon": string;
    "OnShelfTime": string;
    "OffShelfTime": string;
    "RechargeMultiBeginTime": string;
    "RechargeMultiEndTime": string;
    "PreSelOutShopId": number;
    "HideWhenSelOut": boolean;
    "LimitZeroWhenHasItem": boolean;
    "IconDisplayType": number;
    "ShowItemCount": boolean;
    "ShowQuality": boolean;
    "IconInBuyWindow": string;
    "RechargeMultiGoodsDes": string;
    "RewardID": number;

    /** Creates a new ShopGoodsDiff instance. */
    constructor($$source: Partial<ShopGoodsDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Desc" in $$source)) {
            this["Desc"] = "";
        }
        if (!("Item" in $$source)) {
            this["Item"] = [];
        }
        if (!("ExtraItem" in $$source)) {
            this["ExtraItem"] = [];
        }
        if (!("CostId" in $$source)) {
            this["CostId"] = 0;
        }
        if (!("ShopType" in $$source)) {
            this["ShopType"] = "";
        }
        if (!("RechargeAndriod" in $$source)) {
            this["RechargeAndriod"] = 0;
        }
        if (!("RechargeIOS" in $$source)) {
            this["RechargeIOS"] = 0;
        }
        if (!("RechargeMulti" in $$source)) {
            this["RechargeMulti"] = 0;
        }
        if (!("RechargeMultiGroup" in $$source)) {
            this["RechargeMultiGroup"] = 0;
        }
        if (!("Price" in $$source)) {
            this["Price"] = 0;
        }
        if (!("OldPrice" in $$source)) {
            this["OldPrice"] = 0;
        }
        if (!("Discount" in $$source)) {
            this["Discount"] = 0;
        }
        if (!("LimitType" in $$source)) {
            this["LimitType"] = 0;
        }
        if (!("LimitCount" in $$source)) {
            this["LimitCount"] = 0;
        }
        if (!("MaxBuyCount" in $$source)) {
            this["MaxBuyCount"] = 0;
        }
        if (!("Pos" in $$source)) {
            this["Pos"] = 0;
        }
        if (!("IsNew" in $$source)) {
            this["IsNew"] = false;
        }
        if (!("Countdown" in $$source)) {
            this["Countdown"] = 0;
        }
        if (!("IsHomePage" in $$source)) {
            this["IsHomePage"] = false;
        }
        if (!("Icon" in $$source)) {
            this["Icon"] = "";
        }
        if (!("OnShelfTime" in $$source)) {
            this["OnShelfTime"] = "";
        }
        if (!("OffShelfTime" in $$source)) {
            this["OffShelfTime"] = "";
        }
        if (!("RechargeMultiBeginTime" in $$source)) {
            this["RechargeMultiBeginTime"] = "";
        }
        if (!("RechargeMultiEndTime" in $$source)) {
            this["RechargeMultiEndTime"] = "";
        }
        if (!("PreSelOutShopId" in $$source)) {
            this["PreSelOutShopId"] = 0;
        }
        if (!("HideWhenSelOut" in $$source)) {
            this["HideWhenSelOut"] = false;
        }
        if (!("LimitZeroWhenHasItem" in $$source)) {
            this["LimitZeroWhenHasItem"] = false;
        }
        if (!("IconDisplayType" in $$source)) {
            this["IconDisplayType"] = 0;
        }
        if (!("ShowItemCount" in $$source)) {
            this["ShowItemCount"] = false;
        }
        if (!("ShowQuality" in $$source)) {
            this["ShowQuality"] = false;
        }
        if (!("IconInBuyWindow" in $$source)) {
            this["IconInBuyWindow"] = "";
        }
        if (!("RechargeMultiGoodsDes" in $$source)) {
            this["RechargeMultiGoodsDes"] = "";
        }
        if (!("RewardID" in $$source)) {
            this["RewardID"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShopGoodsDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): ShopGoodsDiff {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Item" in $$parsedSource) {
            $$parsedSource["Item"] = $$createField3_0($$parsedSource["Item"]);
        }
        if ("ExtraItem" in $$parsedSource) {
            $$parsedSource["ExtraItem"] = $$createField4_0($$parsedSource["ExtraItem"]);
        }
        return new ShopGoodsDiff($$parsedSource as Partial<ShopGoodsDiff>);
    }
}

// Private type creation functions
const $$createType0 = ItemCfg.createFrom;
const $$createType1 = $Create.Array($$createType0);
