// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FuncCaseConfig 功能测试配置
 */
export class FuncCaseConfig {
    "jsons_dir": string;
    "server_addr": string;
    "server_port": number;
    "desc": string;
    "robot_prefix": string;
    "single_case_run_count": number;
    "login_time": number;
    "room_op_time": number;
    "fei_shu_ntf": boolean;
    "fei_shu_guid": string;
    "debug_level": boolean;
    "debug_log": boolean;
    "concurrency": number;
    "auto_save": boolean;

    /**
     * 消息劫持开关
     */
    "intercept_enabled": boolean;

    /**
     * Excel 资源目录（.bytes 文件路径）
     */
    "excel_resources_dir": string;

    /** Creates a new FuncCaseConfig instance. */
    constructor($$source: Partial<FuncCaseConfig> = {}) {
        if (!("jsons_dir" in $$source)) {
            this["jsons_dir"] = "";
        }
        if (!("server_addr" in $$source)) {
            this["server_addr"] = "";
        }
        if (!("server_port" in $$source)) {
            this["server_port"] = 0;
        }
        if (!("desc" in $$source)) {
            this["desc"] = "";
        }
        if (!("robot_prefix" in $$source)) {
            this["robot_prefix"] = "";
        }
        if (!("single_case_run_count" in $$source)) {
            this["single_case_run_count"] = 0;
        }
        if (!("login_time" in $$source)) {
            this["login_time"] = 0;
        }
        if (!("room_op_time" in $$source)) {
            this["room_op_time"] = 0;
        }
        if (!("fei_shu_ntf" in $$source)) {
            this["fei_shu_ntf"] = false;
        }
        if (!("fei_shu_guid" in $$source)) {
            this["fei_shu_guid"] = "";
        }
        if (!("debug_level" in $$source)) {
            this["debug_level"] = false;
        }
        if (!("debug_log" in $$source)) {
            this["debug_log"] = false;
        }
        if (!("concurrency" in $$source)) {
            this["concurrency"] = 0;
        }
        if (!("auto_save" in $$source)) {
            this["auto_save"] = false;
        }
        if (!("intercept_enabled" in $$source)) {
            this["intercept_enabled"] = false;
        }
        if (!("excel_resources_dir" in $$source)) {
            this["excel_resources_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FuncCaseConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): FuncCaseConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FuncCaseConfig($$parsedSource as Partial<FuncCaseConfig>);
    }
}
