// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DrawSkinDiff {
    "Id": number;
    "Name": string;
    "OnceDropRule": number;
    "TenDropRule": number;
    "OnceItemCost": ItemCfg[];
    "TenItemCost": ItemCfg[];
    "ActivityId": number;
    "StartTime": string;
    "EndTime": string;
    "BigAwardCount": number;
    "BigAwardItemId": number;

    /** Creates a new DrawSkinDiff instance. */
    constructor($$source: Partial<DrawSkinDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("OnceDropRule" in $$source)) {
            this["OnceDropRule"] = 0;
        }
        if (!("TenDropRule" in $$source)) {
            this["TenDropRule"] = 0;
        }
        if (!("OnceItemCost" in $$source)) {
            this["OnceItemCost"] = [];
        }
        if (!("TenItemCost" in $$source)) {
            this["TenItemCost"] = [];
        }
        if (!("ActivityId" in $$source)) {
            this["ActivityId"] = 0;
        }
        if (!("StartTime" in $$source)) {
            this["StartTime"] = "";
        }
        if (!("EndTime" in $$source)) {
            this["EndTime"] = "";
        }
        if (!("BigAwardCount" in $$source)) {
            this["BigAwardCount"] = 0;
        }
        if (!("BigAwardItemId" in $$source)) {
            this["BigAwardItemId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DrawSkinDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): DrawSkinDiff {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("OnceItemCost" in $$parsedSource) {
            $$parsedSource["OnceItemCost"] = $$createField4_0($$parsedSource["OnceItemCost"]);
        }
        if ("TenItemCost" in $$parsedSource) {
            $$parsedSource["TenItemCost"] = $$createField5_0($$parsedSource["TenItemCost"]);
        }
        return new DrawSkinDiff($$parsedSource as Partial<DrawSkinDiff>);
    }
}

export class ItemCfg {
    "ItemId": number;
    "Count": number;

    /** Creates a new ItemCfg instance. */
    constructor($$source: Partial<ItemCfg> = {}) {
        if (!("ItemId" in $$source)) {
            this["ItemId"] = 0;
        }
        if (!("Count" in $$source)) {
            this["Count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemCfg instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemCfg {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ItemCfg($$parsedSource as Partial<ItemCfg>);
    }
}

// Private type creation functions
const $$createType0 = ItemCfg.createFrom;
const $$createType1 = $Create.Array($$createType0);
