// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class HeroUIDiff {
    "Id": number;
    "Name": string;
    "VoiceType": number;
    "BelongExpansionPack": string;
    "AwardDes": string;
    "LongIntroduction": string;
    "ShortIntroduction": string;
    "Evidence": string;
    "Evaluation": string;
    "IsNew": boolean;
    "CopyWriter": string;
    "SkillDesigner": string;
    "GetWay": string;
    "Position": string;
    "ExclusiveCard": number[];
    "NewbieShowSkillTag": number[];
    "WinningRateIn2v2": number;
    "WinRateShowPriority": number;

    /** Creates a new HeroUIDiff instance. */
    constructor($$source: Partial<HeroUIDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("VoiceType" in $$source)) {
            this["VoiceType"] = 0;
        }
        if (!("BelongExpansionPack" in $$source)) {
            this["BelongExpansionPack"] = "";
        }
        if (!("AwardDes" in $$source)) {
            this["AwardDes"] = "";
        }
        if (!("LongIntroduction" in $$source)) {
            this["LongIntroduction"] = "";
        }
        if (!("ShortIntroduction" in $$source)) {
            this["ShortIntroduction"] = "";
        }
        if (!("Evidence" in $$source)) {
            this["Evidence"] = "";
        }
        if (!("Evaluation" in $$source)) {
            this["Evaluation"] = "";
        }
        if (!("IsNew" in $$source)) {
            this["IsNew"] = false;
        }
        if (!("CopyWriter" in $$source)) {
            this["CopyWriter"] = "";
        }
        if (!("SkillDesigner" in $$source)) {
            this["SkillDesigner"] = "";
        }
        if (!("GetWay" in $$source)) {
            this["GetWay"] = "";
        }
        if (!("Position" in $$source)) {
            this["Position"] = "";
        }
        if (!("ExclusiveCard" in $$source)) {
            this["ExclusiveCard"] = [];
        }
        if (!("NewbieShowSkillTag" in $$source)) {
            this["NewbieShowSkillTag"] = [];
        }
        if (!("WinningRateIn2v2" in $$source)) {
            this["WinningRateIn2v2"] = 0;
        }
        if (!("WinRateShowPriority" in $$source)) {
            this["WinRateShowPriority"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroUIDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroUIDiff {
        const $$createField14_0 = $$createType0;
        const $$createField15_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ExclusiveCard" in $$parsedSource) {
            $$parsedSource["ExclusiveCard"] = $$createField14_0($$parsedSource["ExclusiveCard"]);
        }
        if ("NewbieShowSkillTag" in $$parsedSource) {
            $$parsedSource["NewbieShowSkillTag"] = $$createField15_0($$parsedSource["NewbieShowSkillTag"]);
        }
        return new HeroUIDiff($$parsedSource as Partial<HeroUIDiff>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
