// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class HeroSkinSpineDiff {
    "SkinItemId": number;
    "None1": string;
    "IsHasSeatSpine": boolean;
    "IsHasBookSpine": boolean;
    "IsHasMainBgSpine": boolean;
    "MainBgFx": string;
    "IsHasSeatKillSpine": boolean;
    "KillFxId": number;
    "IsHasCollitionBgSpine": boolean;
    "IsHasCollitionCardBgSpine": boolean;
    "SpineAnimAudio": string;
    "IsHasCollitionCardBgSpineDuplicate": boolean;
    "KillAudio": string;

    /** Creates a new HeroSkinSpineDiff instance. */
    constructor($$source: Partial<HeroSkinSpineDiff> = {}) {
        if (!("SkinItemId" in $$source)) {
            this["SkinItemId"] = 0;
        }
        if (!("None1" in $$source)) {
            this["None1"] = "";
        }
        if (!("IsHasSeatSpine" in $$source)) {
            this["IsHasSeatSpine"] = false;
        }
        if (!("IsHasBookSpine" in $$source)) {
            this["IsHasBookSpine"] = false;
        }
        if (!("IsHasMainBgSpine" in $$source)) {
            this["IsHasMainBgSpine"] = false;
        }
        if (!("MainBgFx" in $$source)) {
            this["MainBgFx"] = "";
        }
        if (!("IsHasSeatKillSpine" in $$source)) {
            this["IsHasSeatKillSpine"] = false;
        }
        if (!("KillFxId" in $$source)) {
            this["KillFxId"] = 0;
        }
        if (!("IsHasCollitionBgSpine" in $$source)) {
            this["IsHasCollitionBgSpine"] = false;
        }
        if (!("IsHasCollitionCardBgSpine" in $$source)) {
            this["IsHasCollitionCardBgSpine"] = false;
        }
        if (!("SpineAnimAudio" in $$source)) {
            this["SpineAnimAudio"] = "";
        }
        if (!("IsHasCollitionCardBgSpineDuplicate" in $$source)) {
            this["IsHasCollitionCardBgSpineDuplicate"] = false;
        }
        if (!("KillAudio" in $$source)) {
            this["KillAudio"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroSkinSpineDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroSkinSpineDiff {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HeroSkinSpineDiff($$parsedSource as Partial<HeroSkinSpineDiff>);
    }
}
