// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SkillUIDiff {
    /**
     * ESkillId 作为主键
     */
    "Id": string;

    /**
     * 技能名称
     */
    "SkillName": string;

    /**
     * 出牌音效
     */
    "PlayCardAudio": string;

    /**
     * 身份技能台词
     */
    "IdentityLine": string[];

    /**
     * 空列2
     */
    "None": string;

    /**
     * 打牌时触发技能的台词
     */
    "Audio": number[];

    /**
     * 技能文案
     */
    "SkillText": string;

    /**
     * 技能文案（短）
     */
    "ShortSkillText": string;

    /**
     * 技能关键字
     */
    "KeyWords": number[];

    /**
     * 结算详情
     */
    "SettlementDes": string;

    /**
     * 技能典故
     */
    "Allusion": string;

    /**
     * 设计思路
     */
    "DesignThought": string;

    /**
     * 技能标签
     */
    "SkillTag": number[];

    /**
     * 战斗内阶段显示
     */
    "BattleSkillStep": string[];

    /**
     * 是否有关联技能
     */
    "HasRelation": boolean;

    /**
     * 关联技能技能ID
     */
    "RelatedSkill": string[];

    /**
     * 技能特殊音效
     */
    "SpecialAudio": string;

    /**
     * E#SkillId
     */
    "ESkillId": string;

    /**
     * E#AudioId
     */
    "EAudio": string;

    /**
     * E#AudioId[]
     */
    "EAudioId": string;

    /**
     * E#SkillTag[]
     */
    "ESkillTag": string;

    /** Creates a new SkillUIDiff instance. */
    constructor($$source: Partial<SkillUIDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("SkillName" in $$source)) {
            this["SkillName"] = "";
        }
        if (!("PlayCardAudio" in $$source)) {
            this["PlayCardAudio"] = "";
        }
        if (!("IdentityLine" in $$source)) {
            this["IdentityLine"] = [];
        }
        if (!("None" in $$source)) {
            this["None"] = "";
        }
        if (!("Audio" in $$source)) {
            this["Audio"] = [];
        }
        if (!("SkillText" in $$source)) {
            this["SkillText"] = "";
        }
        if (!("ShortSkillText" in $$source)) {
            this["ShortSkillText"] = "";
        }
        if (!("KeyWords" in $$source)) {
            this["KeyWords"] = [];
        }
        if (!("SettlementDes" in $$source)) {
            this["SettlementDes"] = "";
        }
        if (!("Allusion" in $$source)) {
            this["Allusion"] = "";
        }
        if (!("DesignThought" in $$source)) {
            this["DesignThought"] = "";
        }
        if (!("SkillTag" in $$source)) {
            this["SkillTag"] = [];
        }
        if (!("BattleSkillStep" in $$source)) {
            this["BattleSkillStep"] = [];
        }
        if (!("HasRelation" in $$source)) {
            this["HasRelation"] = false;
        }
        if (!("RelatedSkill" in $$source)) {
            this["RelatedSkill"] = [];
        }
        if (!("SpecialAudio" in $$source)) {
            this["SpecialAudio"] = "";
        }
        if (!("ESkillId" in $$source)) {
            this["ESkillId"] = "";
        }
        if (!("EAudio" in $$source)) {
            this["EAudio"] = "";
        }
        if (!("EAudioId" in $$source)) {
            this["EAudioId"] = "";
        }
        if (!("ESkillTag" in $$source)) {
            this["ESkillTag"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillUIDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillUIDiff {
        const $$createField3_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        const $$createField8_0 = $$createType1;
        const $$createField12_0 = $$createType1;
        const $$createField13_0 = $$createType0;
        const $$createField15_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("IdentityLine" in $$parsedSource) {
            $$parsedSource["IdentityLine"] = $$createField3_0($$parsedSource["IdentityLine"]);
        }
        if ("Audio" in $$parsedSource) {
            $$parsedSource["Audio"] = $$createField5_0($$parsedSource["Audio"]);
        }
        if ("KeyWords" in $$parsedSource) {
            $$parsedSource["KeyWords"] = $$createField8_0($$parsedSource["KeyWords"]);
        }
        if ("SkillTag" in $$parsedSource) {
            $$parsedSource["SkillTag"] = $$createField12_0($$parsedSource["SkillTag"]);
        }
        if ("BattleSkillStep" in $$parsedSource) {
            $$parsedSource["BattleSkillStep"] = $$createField13_0($$parsedSource["BattleSkillStep"]);
        }
        if ("RelatedSkill" in $$parsedSource) {
            $$parsedSource["RelatedSkill"] = $$createField15_0($$parsedSource["RelatedSkill"]);
        }
        return new SkillUIDiff($$parsedSource as Partial<SkillUIDiff>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
