// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService Android APK 自动更新服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckUpdate 查询服务端版本,对比 currentVersionCode。
 * currentVersionCode 由前端 getAppVersionCode()(Java 桥读 build.gradle)传入。
 * 返回:有新版 → *UpdateInfo;无新版或当前已最新 → nil。
 * @frontend
 */
export function CheckUpdate(currentVersionCode: number): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(3682186465, currentVersionCode).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DownloadApk 下载 info.ApkUrl 到 app 私有 files/updates/,边下边算 SHA256,
 * 通过 updateProgress 事件推送百分比进度,下载完校验 SHA256(若 info.Sha256 非空)。
 * 返回本地 APK 绝对路径(供前端调 Java installApk)。
 * @frontend
 */
export function DownloadApk(info: $models.UpdateInfo): $CancellablePromise<string> {
    return $Call.ByID(1375130974, info);
}

/**
 * InitWithApp 注入 app 实例(供 Event.Emit 推送下载进度)。
 */
export function InitWithApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1472075997, app);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
