// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HeroWikiResCheckService 武将 Wiki 资源检查服务
 * @frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as diff$0 from "../rain-resources-checker/diff/models.js";

/**
 * Check 检查武将Wiki资源
 * cardDir 表示同级目录的../../client/Master/Card/位置
 * oldJsonPath "tmp/herowiki_test.json"
 * @frontend @mcp
 */
export function Check(excelDir: string, oldJsonPath: string): $CancellablePromise<diff$0.DataContainer | null> {
    return $Call.ByID(3775385108, excelDir, oldJsonPath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Save 保存当前检查结果到指定路径
 * savePath: 保存路径，由前端 oldJsonPath 传入
 * container: 当前检查结果数据
 * @frontend @mcp
 */
export function Save(savePath: string, container: diff$0.DataContainer | null): $CancellablePromise<void> {
    return $Call.ByID(3703109113, savePath, container);
}

// Private type creation functions
const $$createType0 = diff$0.DataContainer.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
