// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as HeroWikiConfigService from "./herowikiconfigservice.js";
import * as HeroWikiResCheckService from "./herowikirescheckservice.js";
export {
    HeroWikiConfigService,
    HeroWikiResCheckService
};

export {
    HeroWikiConfig
} from "./models.js";
