// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * HeroWikiConfig 应用配置结构
 */
export class HeroWikiConfig {
    "excel_dir": string;
    "old_json_dir": string;

    /** Creates a new HeroWikiConfig instance. */
    constructor($$source: Partial<HeroWikiConfig> = {}) {
        if (!("excel_dir" in $$source)) {
            this["excel_dir"] = "";
        }
        if (!("old_json_dir" in $$source)) {
            this["old_json_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeroWikiConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): HeroWikiConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HeroWikiConfig($$parsedSource as Partial<HeroWikiConfig>);
    }
}
