// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FuncCaseConfigService 配置管理服务
 * @frontend @mcp
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as internal$0 from "../models.js";

/**
 * ConfigExists 检查配置是否存在
 */
export function ConfigExists(): $CancellablePromise<boolean> {
    return $Call.ByID(3679389127);
}

/**
 * DeleteConfig 删除配置
 */
export function DeleteConfig(): $CancellablePromise<void> {
    return $Call.ByID(3102027332);
}

/**
 * GetConfig 获取当前配置
 * @frontend @mcp
 */
export function GetConfig(): $CancellablePromise<internal$0.FuncCaseConfig | null> {
    return $Call.ByID(3191173109).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetConfigFilePath 获取配置文件路径
 */
export function GetConfigFilePath(): $CancellablePromise<string> {
    return $Call.ByID(1163619604);
}

/**
 * GetConfigSummary 获取配置摘要（用于前端显示）
 */
export function GetConfigSummary(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2856496003).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ResetToDefault 重置为默认配置
 */
export function ResetToDefault(): $CancellablePromise<internal$0.FuncCaseConfig | null> {
    return $Call.ByID(1395092954).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveConfig 保存配置
 * @frontend @mcp
 */
export function SaveConfig(config: internal$0.FuncCaseConfig | null): $CancellablePromise<void> {
    return $Call.ByID(2825319814, config);
}

/**
 * UpdateConfig 更新配置（部分更新）
 * @frontend @mcp
 */
export function UpdateConfig(updates: { [_ in string]?: any }): $CancellablePromise<internal$0.FuncCaseConfig | null> {
    return $Call.ByID(3856976498, updates).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = internal$0.FuncCaseConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
