// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JsonCaseService JSON 用例服务，提供用例管理、执行等功能
 * @frontend @mcp
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddTestCase 添加新的测试用例到指定文件
 */
export function AddTestCase(filePath: string, newTestCase: $models.QAFuncCase): $CancellablePromise<void> {
    return $Call.ByID(4125450922, filePath, newTestCase);
}

/**
 * ClearTestLogs 清除测试日志缓存
 * @frontend @mcp
 */
export function ClearTestLogs(): $CancellablePromise<void> {
    return $Call.ByID(202684275);
}

/**
 * DeleteJSONFile 删除 JSON 文件
 * @frontend
 */
export function DeleteJSONFile(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(2531289532, filePath);
}

/**
 * DeleteTestCase 删除测试用例
 */
export function DeleteTestCase(filePath: string, caseName: string): $CancellablePromise<void> {
    return $Call.ByID(3318106864, filePath, caseName);
}

/**
 * GenerateAssetDesc 生成单个 asset 的智能描述（前端"应用智能描述"按钮用）。
 * 
 * 流程：构造 GameExcelService（单例感知，查不到名字返回空），调用 reverse_translate.go
 * 中的 generateAiDesc（与原 TS use-asset-ai-desc.ts 行为一致，3662 case 验证通过）。
 * 
 * @frontend
 */
export function GenerateAssetDesc(asset: $models.Asset, step: $models.Step, initYanWu: $models.InitYanWu): $CancellablePromise<string> {
    return $Call.ByID(2672390541, asset, step, initYanWu);
}

/**
 * GetCaseCount 获取用例数量统计
 * @frontend
 */
export function GetCaseCount(filePath: string): $CancellablePromise<$models.GetCaseCountResponse> {
    return $Call.ByID(632358056, filePath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetCaseList 获取用例列表（支持文件和目录）
 * @mcp
 */
export function GetCaseList(filePath: string): $CancellablePromise<$models.CaseInfo[]> {
    return $Call.ByID(2124409853, filePath).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetCategories 获取分类信息
 * @frontend @mcp
 */
export function GetCategories(dirPath: string): $CancellablePromise<$models.CategoryInfo[]> {
    return $Call.ByID(897866605, dirPath).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetTestCase 获取特定测试用例（从整个目录中搜索）
 * @frontend @mcp
 */
export function GetTestCase(filePath: string, caseName: string): $CancellablePromise<$models.QAFuncCase | null> {
    return $Call.ByID(3929518001, filePath, caseName).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetTestLogs 获取测试日志
 * @frontend @mcp
 */
export function GetTestLogs(caseName: string): $CancellablePromise<{ [_ in string]?: $models.LogEntry[] }> {
    return $Call.ByID(504704902, caseName).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * IsRunningRobotTest 检查是否在运行
 * @frontend @mcp
 */
export function IsRunningRobotTest(): $CancellablePromise<boolean> {
    return $Call.ByID(3222939330);
}

/**
 * ReNameJsonFile 重命名 JSON 文件
 */
export function ReNameJsonFile(oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(2569041649, oldPath, newPath);
}

/**
 * ReadJSONFileOrDir 读取 JSON 文件或目录，返回所有用例
 */
export function ReadJSONFileOrDir(filePath: string): $CancellablePromise<$models.QAFuncCase[]> {
    return $Call.ByID(3170562225, filePath).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * RunRobotTest 执行机器人测试
 * @frontend @mcp
 * 
 * maxTimeoutPerCase 为单批用例的整体执行超时；传 0 表示用默认 10 分钟。
 * CLI（cobra.go）把 --timeout 透传至此，避免卡死用例长时间阻塞。
 */
export function RunRobotTest(ip: string, port: string, prefix: string, desc: string, feishuGuid: string, loginTime: number, filterCasesOption: string[], filterCaseNameOption: string[], dir: string | null, filesData: { [_ in string]?: string } | null, opTimeMs: number, feishuNtf: boolean, debugLevel: boolean, debugLog: boolean, concurrency: number, maxTimeoutPerCase: time$0.Duration): $CancellablePromise<void> {
    return $Call.ByID(895925104, ip, port, prefix, desc, feishuGuid, loginTime, filterCasesOption, filterCaseNameOption, dir, filesData, opTimeMs, feishuNtf, debugLevel, debugLog, concurrency, maxTimeoutPerCase);
}

/**
 * SaveCase 保存 QAFuncCase 到 JSON 文件中，支持指定插入位置和去重
 * filePath: JSON 文件路径
 * newCase: 要保存的新用例
 * position: 插入位置，0=第一个，1=第二个，-1=末尾，如果超出数组长度则放在末尾
 * 如果存在相同 Case 名称的用例，则会覆盖原有用例并移动到新位置
 */
export function SaveCase(filePath: string, newCase: $models.QAFuncCase, position: number): $CancellablePromise<void> {
    return $Call.ByID(1525302250, filePath, newCase, position);
}

/**
 * SaveJSONFile 保存 QAFuncCase 数组到 JSON 文件
 * @frontend
 * filePath: 原始文件路径
 * newFileName: 新文件名引用，如果为空则使用原文件名，如果不为空则替换原文件
 * data: 要保存的数据
 */
export function SaveJSONFile(filePath: string, newFileName: string | null, data: $models.QAFuncCase[]): $CancellablePromise<void> {
    return $Call.ByID(3834628374, filePath, newFileName, data);
}

/**
 * SearchCases 搜索用例（支持目录搜索）
 * @frontend @mcp
 */
export function SearchCases(filePath: string, keyword: string): $CancellablePromise<$models.CaseInfo[]> {
    return $Call.ByID(400624692, filePath, keyword).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * StopRobotTest 提供停止方法
 * @frontend @mcp
 */
export function StopRobotTest(): $CancellablePromise<void> {
    return $Call.ByID(1339781825);
}

/**
 * UpdateCase 按 case 名原地更新一条用例（保持数组顺序不变）
 * filePath: JSON 文件路径
 * caseName: 要更新的用例名（用原 Case 字段定位）
 * newCase: 新的用例完整内容
 * 与 SaveCase 区别：保持用例在数组中的原位置不移动；用例不存在则报错。
 * 适用 read-modify-write 流程：先 get_case_by_name 读出 → 修改 → UpdateCase 写回。
 * @frontend @mcp
 */
export function UpdateCase(filePath: string, caseName: string, newCase: $models.QAFuncCase): $CancellablePromise<void> {
    return $Call.ByID(3853978102, filePath, caseName, newCase);
}

/**
 * UpdateJSONData 更新 JSON 数据中的特定字段
 */
export function UpdateJSONData(filePath: string, caseName: string, updates: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(1710039036, filePath, caseName, updates);
}

// Private type creation functions
const $$createType0 = $models.GetCaseCountResponse.createFrom;
const $$createType1 = $models.CaseInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.CategoryInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.QAFuncCase.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.LogEntry.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Map($Create.Any, $$createType8);
const $$createType10 = $Create.Array($$createType5);
