// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Asset {
    /**
     * @json-critical 消息名称，如 AttrChange, PlayCardAck, DrawCard 等
     */
    "msgName": string;

    /**
     * @json-critical 断言描述
     */
    "desc": string;

    /**
     * @json-critical 属性键值对断言，所有值都是字符串类型
     */
    "attr": { [_ in string]?: string };

    /** Creates a new Asset instance. */
    constructor($$source: Partial<Asset> = {}) {
        if (!("msgName" in $$source)) {
            this["msgName"] = "";
        }
        if (!("desc" in $$source)) {
            this["desc"] = "";
        }
        if (!("attr" in $$source)) {
            this["attr"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Asset instance from a string or object.
     */
    static createFrom($$source: any = {}): Asset {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attr" in $$parsedSource) {
            $$parsedSource["attr"] = $$createField2_0($$parsedSource["attr"]);
        }
        return new Asset($$parsedSource as Partial<Asset>);
    }
}

/**
 * CaseInfo 用例基本信息，用于列表展示
 */
export class CaseInfo {
    "case": string;
    "desc": string;
    "stepCount": number;
    "heroCount": number;

    /**
     * 所属的JSON文件名
     */
    "fileName": string;

    /**
     * 分类（目录名）
     */
    "category": string;

    /**
     * 完整文件路径
     */
    "fullPath": string;

    /**
     * 直接全部返回吧
     */
    "qaFuncCase": QAFuncCase;

    /** Creates a new CaseInfo instance. */
    constructor($$source: Partial<CaseInfo> = {}) {
        if (!("case" in $$source)) {
            this["case"] = "";
        }
        if (!("desc" in $$source)) {
            this["desc"] = "";
        }
        if (!("stepCount" in $$source)) {
            this["stepCount"] = 0;
        }
        if (!("heroCount" in $$source)) {
            this["heroCount"] = 0;
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("fullPath" in $$source)) {
            this["fullPath"] = "";
        }
        if (!("qaFuncCase" in $$source)) {
            this["qaFuncCase"] = (new QAFuncCase());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaseInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CaseInfo {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("qaFuncCase" in $$parsedSource) {
            $$parsedSource["qaFuncCase"] = $$createField7_0($$parsedSource["qaFuncCase"]);
        }
        return new CaseInfo($$parsedSource as Partial<CaseInfo>);
    }
}

/**
 * CategoryInfo 分类信息
 */
export class CategoryInfo {
    "name": string;
    "path": string;
    "caseCount": number;
    "cases": CaseInfo[];

    /** Creates a new CategoryInfo instance. */
    constructor($$source: Partial<CategoryInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("caseCount" in $$source)) {
            this["caseCount"] = 0;
        }
        if (!("cases" in $$source)) {
            this["cases"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CategoryInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CategoryInfo {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cases" in $$parsedSource) {
            $$parsedSource["cases"] = $$createField3_0($$parsedSource["cases"]);
        }
        return new CategoryInfo($$parsedSource as Partial<CategoryInfo>);
    }
}

export class CustomHero {
    /**
     * @json-critical 身份标识
     */
    "identity": number;

    /**
     * @json-critical 阵营颜色（身份阵营颜色编号，取值见前端 Identity.ts excelIdentityColorMap，权威定义为游戏配表 IdentityEncodeRule；⚠️ reverse_translate.go 误用 countryMap 国家表翻译，已知 bug）
     */
    "color": number;

    /**
     * @json-critical 英雄配置ID
     */
    "heroId": number;

    /**
     * @json-critical 初始手牌ID列表
     */
    "initCards": number[];

    /**
     * @json-critical 初始装备ID列表
     */
    "initEquips": number[];

    /**
     * @json-critical 卜卦牌ID列表
     */
    "augurCards": number[];

    /**
     * @json-critical 添加技能ID列表
     */
    "addSkills": number[];

    /**
     * @json-critical 移除技能ID列表
     */
    "delSkills": number[];

    /**
     * @json-critical 扩展装备ID列表
     */
    "exEquips": number[];

    /**
     * @json-critical 技能卡牌映射
     */
    "skillCardsMap": { [_ in `${number}`]?: number[] };

    /** Creates a new CustomHero instance. */
    constructor($$source: Partial<CustomHero> = {}) {
        if (!("identity" in $$source)) {
            this["identity"] = 0;
        }
        if (!("color" in $$source)) {
            this["color"] = 0;
        }
        if (!("heroId" in $$source)) {
            this["heroId"] = 0;
        }
        if (!("initCards" in $$source)) {
            this["initCards"] = [];
        }
        if (!("initEquips" in $$source)) {
            this["initEquips"] = [];
        }
        if (!("augurCards" in $$source)) {
            this["augurCards"] = [];
        }
        if (!("addSkills" in $$source)) {
            this["addSkills"] = [];
        }
        if (!("delSkills" in $$source)) {
            this["delSkills"] = [];
        }
        if (!("exEquips" in $$source)) {
            this["exEquips"] = [];
        }
        if (!("skillCardsMap" in $$source)) {
            this["skillCardsMap"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CustomHero instance from a string or object.
     */
    static createFrom($$source: any = {}): CustomHero {
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType4;
        const $$createField8_0 = $$createType4;
        const $$createField9_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("initCards" in $$parsedSource) {
            $$parsedSource["initCards"] = $$createField3_0($$parsedSource["initCards"]);
        }
        if ("initEquips" in $$parsedSource) {
            $$parsedSource["initEquips"] = $$createField4_0($$parsedSource["initEquips"]);
        }
        if ("augurCards" in $$parsedSource) {
            $$parsedSource["augurCards"] = $$createField5_0($$parsedSource["augurCards"]);
        }
        if ("addSkills" in $$parsedSource) {
            $$parsedSource["addSkills"] = $$createField6_0($$parsedSource["addSkills"]);
        }
        if ("delSkills" in $$parsedSource) {
            $$parsedSource["delSkills"] = $$createField7_0($$parsedSource["delSkills"]);
        }
        if ("exEquips" in $$parsedSource) {
            $$parsedSource["exEquips"] = $$createField8_0($$parsedSource["exEquips"]);
        }
        if ("skillCardsMap" in $$parsedSource) {
            $$parsedSource["skillCardsMap"] = $$createField9_0($$parsedSource["skillCardsMap"]);
        }
        return new CustomHero($$parsedSource as Partial<CustomHero>);
    }
}

/**
 * GetCaseCountResponse 获取用例数量统计返回对象
 */
export class GetCaseCountResponse {
    "TotalCases": number;
    "TotalSteps": number;
    "TotalHeroes": number;

    /** Creates a new GetCaseCountResponse instance. */
    constructor($$source: Partial<GetCaseCountResponse> = {}) {
        if (!("TotalCases" in $$source)) {
            this["TotalCases"] = 0;
        }
        if (!("TotalSteps" in $$source)) {
            this["TotalSteps"] = 0;
        }
        if (!("TotalHeroes" in $$source)) {
            this["TotalHeroes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetCaseCountResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): GetCaseCountResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetCaseCountResponse($$parsedSource as Partial<GetCaseCountResponse>);
    }
}

export class InitYanWu {
    /**
     * @json-critical 场景ID
     */
    "presentId": number;

    /**
     * @json-critical 牌堆类型
     */
    "cardPile": number;

    /**
     * @json-critical 初始牌堆卡牌ID列表
     */
    "cards": number[];

    /**
     * @json-critical 操作超时时间(毫秒)
     */
    "operateTimeMs": number;

    /**
     * @json-critical 自定义英雄列表
     */
    "customHeroes": CustomHero[];

    /** Creates a new InitYanWu instance. */
    constructor($$source: Partial<InitYanWu> = {}) {
        if (!("presentId" in $$source)) {
            this["presentId"] = 0;
        }
        if (!("cardPile" in $$source)) {
            this["cardPile"] = 0;
        }
        if (!("cards" in $$source)) {
            this["cards"] = [];
        }
        if (!("operateTimeMs" in $$source)) {
            this["operateTimeMs"] = 0;
        }
        if (!("customHeroes" in $$source)) {
            this["customHeroes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InitYanWu instance from a string or object.
     */
    static createFrom($$source: any = {}): InitYanWu {
        const $$createField2_0 = $$createType6;
        const $$createField4_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cards" in $$parsedSource) {
            $$parsedSource["cards"] = $$createField2_0($$parsedSource["cards"]);
        }
        if ("customHeroes" in $$parsedSource) {
            $$parsedSource["customHeroes"] = $$createField4_0($$parsedSource["customHeroes"]);
        }
        return new InitYanWu($$parsedSource as Partial<InitYanWu>);
    }
}

/**
 * LogEntry 日志条目
 */
export class LogEntry {
    "case": string;
    "id": number;
    "level": string;
    "type": string;
    "robotName": string;
    "msg": string;
    "time": string;
    "codeLocation": string;

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("case" in $$source)) {
            this["case"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("robotName" in $$source)) {
            this["robotName"] = "";
        }
        if (!("msg" in $$source)) {
            this["msg"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("codeLocation" in $$source)) {
            this["codeLocation"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

/**
 * QAFuncCase JSON数据结构体
 * ⚠️ 以下字段名与 cases/fight_cases_schema.json 及前端 use-case-data.ts 强耦合，修改需同步更新
 * ⚠️ 历史问题参考: commit 2ee0e9c (字段名不一致导致功能失效)
 */
export class QAFuncCase {
    /**
     * @json-critical 用例唯一标识，前端 label 映射
     */
    "case": string;

    /**
     * @json-critical 用例描述，前端 caseDesc 映射
     */
    "desc": string;

    /**
     * @json-critical 负责人，前端 caseManager 映射
     */
    "manager": string;

    /**
     * @json-critical 初始演武配置
     */
    "initYanWu": InitYanWu;

    /**
     * @json-critical 执行步骤列表，前端 caseSteps 映射
     */
    "steps": Step[];

    /** Creates a new QAFuncCase instance. */
    constructor($$source: Partial<QAFuncCase> = {}) {
        if (!("case" in $$source)) {
            this["case"] = "";
        }
        if (!("desc" in $$source)) {
            this["desc"] = "";
        }
        if (!("manager" in $$source)) {
            this["manager"] = "";
        }
        if (!("initYanWu" in $$source)) {
            this["initYanWu"] = (new InitYanWu());
        }
        if (!("steps" in $$source)) {
            this["steps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QAFuncCase instance from a string or object.
     */
    static createFrom($$source: any = {}): QAFuncCase {
        const $$createField3_0 = $$createType9;
        const $$createField4_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("initYanWu" in $$parsedSource) {
            $$parsedSource["initYanWu"] = $$createField3_0($$parsedSource["initYanWu"]);
        }
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField4_0($$parsedSource["steps"]);
        }
        return new QAFuncCase($$parsedSource as Partial<QAFuncCase>);
    }
}

export class Step {
    /**
     * @json-critical 步骤编号
     */
    "id"?: number;

    /**
     * @json-critical 步骤描述
     */
    "desc"?: string;

    /**
     * @json-critical 机器人索引，对应局内seatId
     */
    "robotIdx": number;

    /**
     * @json-critical 动作类型，枚举值见 fight_cases_schema.json
     */
    "action": string;

    /**
     * @json-critical 目标玩家ID列表
     */
    "targetsId"?: number[];

    /**
     * @json-critical 使用的卡牌ID列表
     */
    "cards"?: number[];

    /**
     * @json-critical 卡牌拼接，用于多张牌的操作
     */
    "cardsConcat"?: number[];

    /**
     * @json-critical 是否确认，用于OptRoomAction
     */
    "confirm": boolean;

    /**
     * @json-critical 英雄技能UUID
     */
    "heroSkillUuid"?: number;

    /**
     * @json-critical 转化技能ID
     */
    "transCardSkill"?: number;

    /**
     * @json-critical 超时时间(秒)
     */
    "timeout"?: number;

    /**
     * @json-critical 等待时间(秒)
     */
    "sleepTime"?: number;

    /**
     * @json-critical 断言列表
     */
    "assets"?: Asset[];

    /** Creates a new Step instance. */
    constructor($$source: Partial<Step> = {}) {
        if (!("robotIdx" in $$source)) {
            this["robotIdx"] = 0;
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("confirm" in $$source)) {
            this["confirm"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Step instance from a string or object.
     */
    static createFrom($$source: any = {}): Step {
        const $$createField4_0 = $$createType12;
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType4;
        const $$createField12_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("targetsId" in $$parsedSource) {
            $$parsedSource["targetsId"] = $$createField4_0($$parsedSource["targetsId"]);
        }
        if ("cards" in $$parsedSource) {
            $$parsedSource["cards"] = $$createField5_0($$parsedSource["cards"]);
        }
        if ("cardsConcat" in $$parsedSource) {
            $$parsedSource["cardsConcat"] = $$createField6_0($$parsedSource["cardsConcat"]);
        }
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField12_0($$parsedSource["assets"]);
        }
        return new Step($$parsedSource as Partial<Step>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = QAFuncCase.createFrom;
const $$createType2 = CaseInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Map($Create.Any, $$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = CustomHero.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = InitYanWu.createFrom;
const $$createType10 = Step.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Array($Create.Any);
const $$createType13 = Asset.createFrom;
const $$createType14 = $Create.Array($$createType13);
