// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExampleDataService 内置示例数据服务(独立,方便推翻删除)。
 * 仅 Android 端用(桌面端用户有真实数据目录)。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * LoadExampleData 释放内置示例数据到私有目录,并配置 function-test 指向。
 * 系统干净:先清旧 example-data/ 再释放(多次加载不累积)。
 * 调用后用户导航到"战斗测试"页,页面 mount 读新配置加载用例树 + game resources。
 * @frontend
 */
export function LoadExampleData(): $CancellablePromise<$models.LoadResult | null> {
    return $Call.ByID(2065048160).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.LoadResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
