// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIVL
// This file is automatically generated. DO NOT EDIT

import * as ExampleDataService from "./exampledataservice.js";
export {
    ExampleDataService
};

export {
    LoadResult
} from "./models.js";
