// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LoadResult 加载示例结果
 */
export class LoadResult {
    /**
     * 战斗用例目录(配置 JsonsDir 指向)
     */
    "jsonsDir": string;

    /**
     * game .bytes 目录(配置 ExcelResourcesDir 指向)
     */
    "resourcesDir": string;

    /**
     * 释放的战斗用例数
     */
    "fightCaseCount": number;

    /**
     * 释放的总文件数(.bytes + 用例)
     */
    "fileCount": number;

    /** Creates a new LoadResult instance. */
    constructor($$source: Partial<LoadResult> = {}) {
        if (!("jsonsDir" in $$source)) {
            this["jsonsDir"] = "";
        }
        if (!("resourcesDir" in $$source)) {
            this["resourcesDir"] = "";
        }
        if (!("fightCaseCount" in $$source)) {
            this["fightCaseCount"] = 0;
        }
        if (!("fileCount" in $$source)) {
            this["fileCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LoadResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoadResult($$parsedSource as Partial<LoadResult>);
    }
}
