// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ShopDiff {
    /**
     * 商店类型(EShopType枚举)
     */
    "ShopType": string;

    /**
     * 商店名称
     */
    "Name": string;

    /**
     * 商店显示名称
     */
    "ShopName": string;

    /**
     * 商店使用的货币
     */
    "UseCurrency": number[];

    /**
     * 开启时间
     */
    "OpenTime": string;

    /**
     * 关闭时间
     */
    "CloseTime": string;

    /**
     * 是否为限时商店
     */
    "IsLimitedShop": boolean;

    /**
     * 是否为动态商店
     */
    "IsDynamicsShop": boolean;

    /**
     * 主界面中商店顺序
     */
    "InMainShopOrder": number;

    /** Creates a new ShopDiff instance. */
    constructor($$source: Partial<ShopDiff> = {}) {
        if (!("ShopType" in $$source)) {
            this["ShopType"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("ShopName" in $$source)) {
            this["ShopName"] = "";
        }
        if (!("UseCurrency" in $$source)) {
            this["UseCurrency"] = [];
        }
        if (!("OpenTime" in $$source)) {
            this["OpenTime"] = "";
        }
        if (!("CloseTime" in $$source)) {
            this["CloseTime"] = "";
        }
        if (!("IsLimitedShop" in $$source)) {
            this["IsLimitedShop"] = false;
        }
        if (!("IsDynamicsShop" in $$source)) {
            this["IsDynamicsShop"] = false;
        }
        if (!("InMainShopOrder" in $$source)) {
            this["InMainShopOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShopDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): ShopDiff {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("UseCurrency" in $$parsedSource) {
            $$parsedSource["UseCurrency"] = $$createField3_0($$parsedSource["UseCurrency"]);
        }
        return new ShopDiff($$parsedSource as Partial<ShopDiff>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
