// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DropGroupDiff {
    "Id": number;
    "Name": string;
    "Weight": number;
    "WeightInc": number;
    "Deduplication": boolean;
    "ValidDate": string;
    "ExpireDate": string;

    /** Creates a new DropGroupDiff instance. */
    constructor($$source: Partial<DropGroupDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Weight" in $$source)) {
            this["Weight"] = 0;
        }
        if (!("WeightInc" in $$source)) {
            this["WeightInc"] = 0;
        }
        if (!("Deduplication" in $$source)) {
            this["Deduplication"] = false;
        }
        if (!("ValidDate" in $$source)) {
            this["ValidDate"] = "";
        }
        if (!("ExpireDate" in $$source)) {
            this["ExpireDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DropGroupDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): DropGroupDiff {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DropGroupDiff($$parsedSource as Partial<DropGroupDiff>);
    }
}
