// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SkillMeltDiff {
    /**
     * ESkillId 枚举类型
     */
    "Id": string;

    /**
     * 空列1
     */
    "None1": string;

    /**
     * 空列2
     */
    "None2": string;
    "MeltPower": number;
    "CanMelt": boolean;

    /** Creates a new SkillMeltDiff instance. */
    constructor($$source: Partial<SkillMeltDiff> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("None1" in $$source)) {
            this["None1"] = "";
        }
        if (!("None2" in $$source)) {
            this["None2"] = "";
        }
        if (!("MeltPower" in $$source)) {
            this["MeltPower"] = 0;
        }
        if (!("CanMelt" in $$source)) {
            this["CanMelt"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillMeltDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillMeltDiff {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillMeltDiff($$parsedSource as Partial<SkillMeltDiff>);
    }
}
