name: Qodana
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'agent/**'
      - '.github/workflows/qodana_code_quality.yml'
  push:
    branches:
      - main
    paths:
      - 'agent/**'
      - '.github/workflows/qodana_code_quality.yml'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    defaults:
      run:
        working-directory: ./agent
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: --fail-threshold=0
          source-dir: ./agent
